package app.fieldwatch

import app.fieldwatch.domain.DefaultCatalog
import app.fieldwatch.domain.DecodeType
import app.fieldwatch.domain.DecodedFieldValue
import app.fieldwatch.domain.Fleet
import app.fieldwatch.domain.resolvedLength

/** UI-only translation of stock authored catalog text. Stored and exported catalogs remain untouched. */
internal object UiCatalogText {
    private val stockById by lazy { DefaultCatalog.fleets().associateBy { it.id } }

    /** Only unchanged stock text is translated; custom signatures and operator edits pass through. */
    fun forFleet(fleet: Fleet?, source: String, translate: (String) -> String = ::text): String {
        if (fleet?.builtIn != true) return source
        val stock = stockById[fleet.id] ?: return source
        if (source == fleet.notes) return if (fleet.notes == stock.notes) translate(source) else source
        if (source == fleet.attentionNote) return if (fleet.attentionNote == stock.attentionNote) translate(source) else source
        if (source == fleet.name) return if (fleet.name == stock.name) translate(source) else source
        val currentFields = fleet.decode?.fields.orEmpty()
        for (field in stock.decode?.fields.orEmpty()) {
            if (field !in currentFields) continue
            if (source == field.label || source in field.enumNotes.orEmpty().values) return translate(source)
            for (value in field.enumLabels.orEmpty().values) {
                if (source == value) return translate(value)
                val unit = field.unit
                if (!unit.isNullOrBlank() && source == "$value $unit") return "${translate(value)} $unit"
            }
        }
        return source
    }

    /** A decoded display may contain arbitrary radio text; only stock enum values are authored text. */
    fun decoded(fleet: Fleet?, row: DecodedFieldValue, translate: (String) -> String = ::text): String {
        if (fleet?.builtIn != true || fleet.id != row.fleetId) return row.display
        val stock = stockById[fleet.id] ?: return row.display
        val currentFields = fleet.decode?.fields.orEmpty()
        for (field in stock.decode?.fields.orEmpty()) {
            if (field !in currentFields || field.id != row.id || field.offset != row.offset ||
                field.resolvedLength() != row.length || field.label != row.label
            ) continue
            val values = field.enumLabels.orEmpty().values.toMutableList()
            if (field.type == DecodeType.BOOL) values.addAll(listOf("yes", "no"))
            val unit = field.unit.orEmpty().trim()
            for (value in values) {
                val display = if (unit.isEmpty()) value else "$value $unit"
                if (row.display == display) {
                    return if (unit.isEmpty()) translate(value) else "${translate(value)} $unit"
                }
            }
        }
        return row.display
    }

    fun text(source: String): String = when (source) {
        "LYWSD02MMC temperature / humidity monitor. Its MiBeacon product header identifies the model family; encrypted frames do not reveal readings." -> UiText.text(R.string.identity_v92_note_0)
        "CGD1 temperature / humidity monitor. Its MiBeacon product header identifies the model family; measurements are available only in supported plaintext objects." -> UiText.text(R.string.identity_v92_note_1)
        "SJWS01LM water leak sensor. The MiBeacon product header identifies the sensor family; a product identity alone does not prove a leak or an alarm state." -> UiText.text(R.string.identity_v92_note_2)
        "Xiaomi ecosystem door-lock family. MiBeacon product headers distinguish known partner models; they do not identify an owner or prove a locked or unlocked state." -> UiText.text(R.string.identity_v92_note_3)

        "Wi-Fi access point (brand unconfirmed)" -> UiText.text(R.string.identity_v92_0)
        "Chipset platform: %1\$s" -> UiText.text(R.string.identity_v92_1)
        "Payload decode status" -> UiText.text(R.string.identity_v92_2)
        "No advertisement payload captured" -> UiText.text(R.string.identity_v92_3)
        "Payload parser unsupported" -> UiText.text(R.string.identity_v92_4)
        "No catalog signature matched; parsed identity fields may still be available." -> UiText.text(R.string.identity_v92_5)
        "temperature / humidity sensor" -> UiText.text(R.string.identity_v92_6)
        "body composition scale" -> UiText.text(R.string.identity_v92_7)
        "water leak sensor" -> UiText.text(R.string.identity_v92_8)
        "door lock" -> UiText.text(R.string.identity_v92_9)
        "MiBeacon product ID %1\$s identifies %2\$s; encrypted objects do not expose readings." -> UiText.text(R.string.identity_v92_10)
        "MiBeacon light raw value" -> UiText.text(R.string.identity_v92_11)
        "MiBeacon on/off raw state" -> UiText.text(R.string.identity_v92_12)
        "MiBeacon light raw state" -> UiText.text(R.string.identity_v92_13)
        "MiBeacon water detected" -> UiText.text(R.string.identity_v92_14)
        "MiBeacon smoke detected" -> UiText.text(R.string.identity_v92_15)
        "MiBeacon door/window state" -> UiText.text(R.string.identity_v92_16)
        "Open" -> UiText.text(R.string.identity_v92_17)
        "Closed" -> UiText.text(R.string.identity_v92_18)
        "Fiberhome Wi-Fi" -> UiText.text(R.string.identity_v92_19)
        "WPS manufacturer identifies Fiberhome. A repeated manufacturer/model field does not establish an exact retail model." -> UiText.text(R.string.identity_v92_20)
        "WPS primary device type identifies an access point. A chipset manufacturer such as Realtek does not establish the finished product brand." -> UiText.text(R.string.identity_v92_21)
        "LYWSD02MMC thermometer" -> UiText.text(R.string.identity_v92_22)
        "CGD1 thermometer" -> UiText.text(R.string.identity_v92_23)
        "SJWS01LM water leak sensor" -> UiText.text(R.string.identity_v92_24)
        "Mi ecosystem door lock" -> UiText.text(R.string.identity_v92_25)

        "Qi'an / Qingju radio (type unknown)" -> UiText.text(R.string.catalog_v91_qian)
        "QJLF30 name together with public IEEE prefix 24:F1:50 identifies a Guangzhou Qi'an radio associated with Qingju. Lock versus parking infrastructure is unverified; no vehicle or rider identity is inferred. FEE7 or company 0201 alone is not this fingerprint." -> UiText.text(R.string.catalog_v91_qian_note)
        "Bicycle parking beacon" -> UiText.text(R.string.catalog_v91_parking_fence)
        "BJP010?B??? follows the parking-beacon naming example in patent CN114373293B. This is parking infrastructure, not a bicycle or rider. The name does not establish a precise location." -> UiText.text(R.string.catalog_v91_parking_fence_note)
        "NIU Link vehicle" -> UiText.text(R.string.catalog_v91_niu_link)
        "NIU Link BLE name points to a Niu vehicle radio. It does not show the model, owner, lock state or speed." -> UiText.text(R.string.catalog_v91_niu_link_note)
        "CFMOTO vehicle" -> UiText.text(R.string.catalog_v91_cfmoto)
        "CFMOTO-* BLE name points to a CFMOTO vehicle radio or instrument. The suffix is not a verified model or vehicle identity." -> UiText.text(R.string.catalog_v91_cfmoto_note)
        "InGeek digital vehicle key" -> UiText.text(R.string.catalog_v91_ingeek_key)
        "IngeekDK-* BLE name suggests an InGeek vehicle digital-key radio. No vehicle model, owner or unlocked state is inferred." -> UiText.text(R.string.catalog_v91_ingeek_key_note)
        "ZEEKR vehicle radio" -> UiText.text(R.string.catalog_v91_zeekr_vehicle)
        "ZeekrVehicle* BLE name suggests a ZEEKR vehicle radio. It does not identify a model, owner or key state." -> UiText.text(R.string.catalog_v91_zeekr_vehicle_note)
        "RoadBit e-bike radio" -> UiText.text(R.string.catalog_v91_roadbit)
        "ROADBIT BLE name suggests the RoadBit shared e-bike family documented by Red Dot. This is a name-based inference, not a verified operator, model or rider." -> UiText.text(R.string.catalog_v91_roadbit_note)
        "Narwal robot vacuum" -> UiText.text(R.string.catalog_v91_narwal)
        "NARWAL-* BLE name points to a Narwal robot-vacuum family. The name alone does not identify a retail model or cleaning state." -> UiText.text(R.string.catalog_v91_narwal_note)
        "COLMO appliance" -> UiText.text(R.string.catalog_v91_colmo)
        "COLMO BLE name points to a COLMO home-appliance family. Appliance type, model and operating state remain unverified." -> UiText.text(R.string.catalog_v91_colmo_note)
        "PETKIT pet appliance" -> UiText.text(R.string.catalog_v91_petkit)
        "Petkit_* BLE name points to a PETKIT pet-appliance family. The product code alone does not establish feeder, fountain or litter-box type." -> UiText.text(R.string.catalog_v91_petkit_note)
        "HONOR Band wearable" -> UiText.text(R.string.catalog_v91_honor_band)
        "HONOR Band BLE name identifies an Honor fitness-band family. A name suffix is not a wearer identity or health measurement." -> UiText.text(R.string.catalog_v91_honor_band_note)
        "OPPO Watch wearable" -> UiText.text(R.string.catalog_v91_oppo_watch)
        "OPPO Watch BLE name identifies an OPPO smartwatch family. No wearer identity or health measurement is inferred." -> UiText.text(R.string.catalog_v91_oppo_watch_note)
        "MJWSD thermometer" -> UiText.text(R.string.catalog_v91_mi_thermometer)
        "MJWSD05MMC or MJWSD06MMC BLE name identifies a Xiaomi ecosystem temperature/humidity monitor. Encrypted advertisements do not reveal readings." -> UiText.text(R.string.catalog_v91_mi_thermometer_note)
        "Mijia Scale S400" -> UiText.text(R.string.catalog_v91_mijia_s400)
        "Mijia Scale S400 BLE name points to the S400 scale family (MJTZC01YM). The name does not reveal body measurements or a person." -> UiText.text(R.string.catalog_v91_mijia_s400_note)
        "Mi ecosystem smart switch" -> UiText.text(R.string.catalog_v91_mi_switch)
        "Advertised model names are listed as switches by the official MIoT specification. They do not reveal switch state or prove all ecosystem products are made by Xiaomi." -> UiText.text(R.string.catalog_v91_mi_switch_note)
        "Mi ecosystem smart light" -> UiText.text(R.string.catalog_v91_mi_light)
        "Advertised model names are listed as lights by the official MIoT specification. Brightness, color and on/off state are not established." -> UiText.text(R.string.catalog_v91_mi_light_note)
        "Cariot phone holder" -> UiText.text(R.string.catalog_v91_cariot_holder)
        "cariot.holder.wpc100 is listed as a phone holder by the official MIoT specification. No charging state or vehicle identity is inferred." -> UiText.text(R.string.catalog_v91_cariot_holder_note)
        "Haier appliance radio" -> UiText.text(R.string.catalog_v91_haier_radio)
        "IEEE prefixes registered to Qingdao Haier Technology identify a Haier radio family on Wi-Fi or a stable public BLE address. Appliance type and exact model are not established." -> UiText.text(R.string.catalog_v91_haier_radio_note)
        "ZTE Wi-Fi radio" -> UiText.text(R.string.catalog_v91_zte_wifi)
        "ZTE_* SSID or verified IEEE ZTE prefixes identify a ZTE Wi-Fi interface. It may be a gateway, access point or hotspot; no exact model is established." -> UiText.text(R.string.catalog_v91_zte_wifi_note)
        "PHICOMM Wi-Fi" -> UiText.text(R.string.catalog_v91_phicomm_wifi)
        "PHICOMM name or IEEE Phicomm prefixes identify a Phicomm Wi-Fi interface. Renamed networks can match by address; an exact router model is not established." -> UiText.text(R.string.catalog_v91_phicomm_wifi_note)
        "360 Wi-Fi" -> UiText.text(R.string.catalog_v91_qihoo_wifi)
        "360WiFi-* default name or IEEE Qihoo prefixes identify a 360 network family. The name alone does not establish an exact router or portable-hotspot model." -> UiText.text(R.string.catalog_v91_qihoo_wifi_note)

        "Mobike BLE name, company 04B3, or dedicated A000FAA0-0047-005A-0052-6D6F62696B65 service identifies a Mobike lock family. No lock state, location or rider identity is inferred." -> UiText.text(R.string.catalog_v90_mobike_note)
        "Mobike bicycle lock" -> UiText.text(R.string.catalog_v90_mobike)
        "ROMO-* BLE name identifies a DJI ROMO robot vacuum family. It is not an aircraft; the suffix does not identify a retail model or cleaning state." -> UiText.text(R.string.catalog_v90_romo_note)
        "DJI ROMO robot vacuum" -> UiText.text(R.string.catalog_v90_romo)
        "MERCURY* Wi-Fi name identifies a Mercury network family. Shared chipset identifiers do not prove the router brand or model." -> UiText.text(R.string.catalog_v90_mercury_note)
        "MERCURY Wi-Fi" -> UiText.text(R.string.catalog_v90_mercury)
        "Flock-style roadside ALPR / camera pole. IEEE B4:1E:52 or a Flock-* / FLCK / Condor / Falcon / Sparrow name. Current poles are often quiet on Wi-Fi and BLE. LiteOn module prefixes are a separate row, not Extra attention." -> UiText.text(R.string.catalog_001)
        "Flock-style roadside ALPR / camera pole — reads plates and can be used to locate a vehicle. IEEE B4:1E:52 or a Flock-* SSID is the strong hit. Current poles are often quiet on Wi-Fi and BLE. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_002)
        "Wi-Fi module prefixes commonly seen on camera boards (LiteOn and similar). Not Flock's IEEE block. Doorbells and other OEM radios use these chips. A Flock name or B4:1E:52 is Flock Safety Cameras." -> UiText.text(R.string.catalog_003)
        "Flock Raven or ShotSpotter-style acoustic gunshot sensor, usually on a pole with cameras. BLE UUIDs 3100–3500 are the Raven radio. The XUNTONG battery manufacturer ID is Penguin, not this row. Current Flock-family poles are often quiet on Wi-Fi and BLE." -> UiText.text(R.string.catalog_004)
        "Apple AirTag or Find My accessory. iPhones also send Find My so they can be located — that stays on Apple Device unless the name is AirTag. Addresses rotate." -> UiText.text(R.string.catalog_005)
        "Samsung SmartTag / SmartTag+ item finder. Addresses often rotate." -> UiText.text(R.string.catalog_006)
        "Generic proximity beacon. Stores, baskets, TVs, and cars can all send this Apple layout. Mute in a dense mall." -> UiText.text(R.string.catalog_007)
        "Target shopping-basket tag. Dual-labels with generic iBeacon; this row is the store basket." -> UiText.text(R.string.catalog_008)
        "Minew location or asset beacon. Often also sends iBeacon or Eddystone on the same radio." -> UiText.text(R.string.catalog_009)
        "Store or venue location beacon / sticker. Decoded fields can show Nearable vs telemetry." -> UiText.text(R.string.catalog_010)
        "Store or venue location beacon. Decoded fields can show battery, TX, and whether it is moving." -> UiText.text(R.string.catalog_011)
        "Tile item finder. Decoded fields can show a rotating private id — not a serial." -> UiText.text(R.string.catalog_012)
        "Penguin Flock-family external battery. The XUNTONG BLE manufacturer ID is the usual fingerprint; Penguin* names are older firmware. Newer packs often advertise a 10-digit name. Decode fields show the TN serial from manufacturer data when present." -> UiText.text(R.string.catalog_013)
        "Penguin is a Flock-family external battery (XUNTONG manufacturer ID). Name hits are older firmware and low uniqueness. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_014)
        "Pigvision Flock-family / roadside camera name." -> UiText.text(R.string.catalog_015)
        "Pigvision is a Flock-family / roadside camera name. Name-only. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_016)
        "External battery pack usually associated with a Flock-style camera pole. Name hits are stronger. Current poles are often quiet on Wi-Fi and BLE." -> UiText.text(R.string.catalog_017)
        "Usually associated with a Flock-style camera — an external battery pack on the pole. Name hits are stronger. Current poles are often quiet on Wi-Fi and BLE. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_018)
        "iPhone, iPad, or Mac advertising Continuity (Nearby, Handoff, AirDrop, Instant Hotspot). Find My on this radio is the phone locating itself, not a second AirTag. Not AirPods." -> UiText.text(R.string.catalog_019)
        "AirPods, Beats, or an Apple TV/speaker advertising AirPlay. Not an AirTag and not the iPhone itself." -> UiText.text(R.string.catalog_020)
        "Windows PC, Surface, or Xbox advertising Swift Pair / Nearby Sharing." -> UiText.text(R.string.catalog_021)
        "Tesla phone-as-key, vehicle, Wall Connector, or TeslaGW Wi-Fi. iOS also sees an iBeacon layout from the car — that is still Tesla, not a mall beacon. Tire sensors are the tsTPMS row." -> UiText.text(R.string.catalog_022)
        "Ford or Lincoln phone-as-key / infotainment. Not a dealer Wi-Fi name." -> UiText.text(R.string.catalog_023)
        "Honda or Acura phone-as-key / infotainment." -> UiText.text(R.string.catalog_024)
        "Hyundai or Genesis phone-as-key / infotainment. Not a dealer Wi-Fi name." -> UiText.text(R.string.catalog_025)
        "Toyota or Lexus phone-as-key, or a factory TOYOTA / LEXUS hotspot." -> UiText.text(R.string.catalog_026)
        "Nissan or Infiniti phone-as-key / infotainment." -> UiText.text(R.string.catalog_027)
        "Subaru phone-as-key / infotainment. Not Starlink satellite internet." -> UiText.text(R.string.catalog_028)
        "BMW phone-as-key or in-car hotspot. Factory BMW_ Wi-Fi is the car, not a dealer showroom." -> UiText.text(R.string.catalog_029)
        "Volkswagen phone-as-key or My VW hotspot. Skoda, SEAT, and Porsche have their own rows." -> UiText.text(R.string.catalog_030)
        "Porsche phone-as-key or factory Porsche_WLAN hotspot. Separate from Volkswagen." -> UiText.text(R.string.catalog_031)
        "Jaguar, Land Rover, or Range Rover phone-as-key / infotainment." -> UiText.text(R.string.catalog_032)
        "BYD phone-as-key or vehicle BLE. Pattern match, not a specific model." -> UiText.text(R.string.catalog_033)
        "Pixel phone or Chromecast. Fast Pair accessories are the Fast Pair row." -> UiText.text(R.string.catalog_034)
        "Android accessory (buds, watch, phone) advertising Fast Pair. Pairing-mode is tap-to-pair; longer ads are already-paired plaza noise. Not a person. Filters can hide the plaza chips." -> UiText.text(R.string.catalog_035)
        "Sony headphones, TV, or camera. Bravia TVs also send a generic iBeacon for Cast — Fieldwatch keeps Sony." -> UiText.text(R.string.catalog_036)
        "Bose headphones or speaker. Quiet Charge / QC buds advertise even when in the case." -> UiText.text(R.string.catalog_037)
        "Garmin watch, bike computer, or inReach messenger." -> UiText.text(R.string.catalog_038)
        "Amazon Echo, Fire, or Kindle when it advertises. Not every AmazonBasics gadget." -> UiText.text(R.string.catalog_039)
        "Fitbit watch or tracker. Advertisements are identity-only; step counts are not in the broadcast." -> UiText.text(R.string.catalog_040)
        "Oura wellness ring. Always-on BLE while worn. Pattern match, not that person." -> UiText.text(R.string.catalog_041)
        "Logitech mouse, keyboard, or webcam. Office noise." -> UiText.text(R.string.catalog_042)
        "JBL, Harman Kardon, or some car-audio BLE. Headphones, speakers, or a head unit." -> UiText.text(R.string.catalog_043)
        "Sonos home/office speaker. Setup or idle ads. Not a tracker." -> UiText.text(R.string.catalog_044)
        "GoPro action camera. Decoded fields can show whether it is awake, in Wi-Fi AP mode, or pairing." -> UiText.text(R.string.catalog_045)
        "DJI Osmo handheld / action camera (Action, Pocket, 360, Nano). Not a flying DJI aircraft." -> UiText.text(R.string.catalog_046)
        "Insta360 action / 360 camera. The advertised name is often the model plus serial. Consumer camera, not a pole." -> UiText.text(R.string.catalog_047)
        "DJI aircraft, controller, or setup Wi-Fi. Handheld Osmo cameras are the Osmo row. In-flight digital license plate is the Remote ID row." -> UiText.text(R.string.catalog_048)
        "NETGEAR or Orbi home router / mesh. Renamed SSIDs still hit on the board vendor." -> UiText.text(R.string.catalog_049)
        "TP-Link or Deco home router / mesh. A Tapo camera on a TP-Link board can also hit this row." -> UiText.text(R.string.catalog_050)
        "ASUS home router or mesh. An ASUS laptop hotspot can also hit." -> UiText.text(R.string.catalog_051)
        "Linksys or Velop home mesh. Some Velop units use Belkin boards." -> UiText.text(R.string.catalog_052)
        "Amazon Eero mesh. Not an Echo speaker." -> UiText.text(R.string.catalog_053)
        "Google Wifi / Nest Wifi mesh. Not a Pixel phone and not a Nest camera." -> UiText.text(R.string.catalog_054)
        "Huawei home router, or a phone hotspot on a public Huawei address. Randomized hotspots need the factory SSID. Not Honor." -> UiText.text(R.string.catalog_055)
        "Plume SuperPod / HomePass mesh. ISP-branded pods (xFi and similar) often use the carrier OEM board instead." -> UiText.text(R.string.catalog_056)
        "Phone personal hotspot on a factory name (AndroidAP, Galaxy, Pixel). Custom hotspot names miss. iPhone hotspots stay on Apple Device." -> UiText.text(R.string.catalog_057)
        "D-Link home router. Renamed SSIDs still hit on the board vendor." -> UiText.text(R.string.catalog_058)
        "DWnet consumer / SMB access point. Cloud SSIDs are house names, so the board vendor is the hit." -> UiText.text(R.string.catalog_059)
        "Belkin home router. Some Linksys Velop units land here too." -> UiText.text(R.string.catalog_060)
        "Comcast xfinitywifi hotspot or Xfinity / XFSETUP gateway name. Most boxes are Arris / Hitron / Technicolor OEM — those hit the OEM row." -> UiText.text(R.string.catalog_061)
        "Charter Spectrum setup or hotspot Wi-Fi. Boxes are usually Arris / Hitron / Technicolor OEM." -> UiText.text(R.string.catalog_062)
        "AT&T hotspot or gateway (attwifi, ATT-GUEST, Pace-style factory names). Many boxes are Pace / Arris OEM." -> UiText.text(R.string.catalog_063)
        "Verizon or Fios hotspot / gateway name. Many FiOS boxes are Actiontec OEM." -> UiText.text(R.string.catalog_064)
        "Starlink router. The BSSID is often randomized now — the STARLINK name is the usual hit." -> UiText.text(R.string.catalog_065)
        "Cisco Meraki campus / cloud access point. Renamed site SSIDs still hit on the board vendor. Not a camera pole." -> UiText.text(R.string.catalog_066)
        "GL.iNet travel router. Chip-module boards without a GL name miss." -> UiText.text(R.string.catalog_067)
        "Chipolo item finder (Find Hub / Find My). A tag you clip to keys or a bag." -> UiText.text(R.string.catalog_068)
        "Pebblebee or Motorola moto tag item finder. A tag you clip to keys or a bag." -> UiText.text(R.string.catalog_069)
        "Google Find Hub / Find My Device network tag (Chipolo, Pebblebee, moto tag, and other partners). Nearby vs separated frames. Separated mode can hold a MAC about a day. Addresses otherwise rotate. Pattern match, not that bag." -> UiText.text(R.string.catalog_070)
        "IETF DULT location-enabled advertisement (Detecting Unwanted Location Trackers). Chipolo, Pebblebee, moto tag, and other partner tags may dual-label. Near-owner vs separated is a bit in the payload. Separated mode can hold a MAC about a day. Pattern match, not that bag." -> UiText.text(R.string.catalog_071)
        "Verkada cloud camera, including LPR-capable bullets, on buildings and some public sites." -> UiText.text(R.string.catalog_072)
        "Verkada cloud cameras, including LPR-capable bullets. Used on buildings and some public sites — video and sometimes plates. Name-only. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_073)
        "Motorola Vigilant plate reader used by agencies and parking." -> UiText.text(R.string.catalog_074)
        "Motorola Vigilant is LPR — plate readers used by agencies and parking. Name-only when advertised. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_075)
        "eufy home camera or tag. Common in houses. Consumer camera, not a roadside pole." -> UiText.text(R.string.catalog_076)
        "Wyze home camera. Very common consumer gear, not a roadside pole." -> UiText.text(R.string.catalog_077)
        "Amazon Ring doorbell or camera. Common on houses. Consumer camera, not a roadside pole." -> UiText.text(R.string.catalog_078)
        "Arlo home camera or its base-station Wi-Fi. Consumer camera, not a roadside pole. Renamed SSIDs still hit on the board vendor." -> UiText.text(R.string.catalog_079)
        "Google Nest home camera. Consumer camera, not the Nest thermostat row." -> UiText.text(R.string.catalog_080)
        "Nest thermostat. Temperature sensors on some generations can hit this too. Not a Nest camera." -> UiText.text(R.string.catalog_081)
        "Nest Protect, thermostat, or other Weave-over-BLE home device. Randomized address. Decoded fields can show product and pairing." -> UiText.text(R.string.catalog_082)
        "ecobee thermostat. Room sensors can hit the same row. Premium uses BLE for setup / Spotify." -> UiText.text(R.string.catalog_083)
        "Sensi thermostat in BLE setup." -> UiText.text(R.string.catalog_084)
        "Honeywell Home / Lyric / Resideo thermostat (including Amazon Smart Thermostat). Not Honeywell industrial or smoke gear. T9/T10 room sensors are 900 MHz, not BLE." -> UiText.text(R.string.catalog_085)
        "Big Ass Fans Haiku or Mammoth ceiling fan." -> UiText.text(R.string.catalog_086)
        "Tuya plug, light, camera, or sensor. Dense in some apartments. Decoded fields can show whether it is bound." -> UiText.text(R.string.catalog_087)
        "ASSA ABLOY / HID Seos or Yale access credential. Phones on HID Mobile Access can advertise a Seos name." -> UiText.text(R.string.catalog_088)
        "August smart lock (now ASSA-owned). Door lock, not a camera." -> UiText.text(R.string.catalog_089)
        "Schlage / Allegion smart lock (Encode and similar)." -> UiText.text(R.string.catalog_090)
        "Nuki smart lock or opener (retrofit on a European cylinder)." -> UiText.text(R.string.catalog_091)
        "SALTO commercial access lock or reader." -> UiText.text(R.string.catalog_092)
        "dormakaba, Saflok, or Oracode hotel / commercial lock." -> UiText.text(R.string.catalog_093)
        "Lockly smart lock, usually while in BLE setup." -> UiText.text(R.string.catalog_094)
        "Kwikset Kevo smart lock." -> UiText.text(R.string.catalog_095)
        "Master Lock Bluetooth padlock." -> UiText.text(R.string.catalog_096)
        "igloohome keybox or smart lock." -> UiText.text(R.string.catalog_097)
        "Tedee retrofit smart lock." -> UiText.text(R.string.catalog_098)
        "Paxton / Net2 door reader or access panel." -> UiText.text(R.string.catalog_099)
        "Kwikset smart lock. Kevo has its own row." -> UiText.text(R.string.catalog_100)
        "Chamberlain myQ garage-door hub." -> UiText.text(R.string.catalog_101)
        "Chevrolet in-car hotspot (myChevrolet). Cadillac / GMC / Buick are the GM hotspot row. Not a dealer." -> UiText.text(R.string.catalog_102)
        "Stellantis Uconnect in-car hotspot (Chrysler, Jeep, Ram, Dodge, Fiat). BSSID often randomized." -> UiText.text(R.string.catalog_103)
        "In-car CarPlay / Alpine head-unit hotspot. Factory name from the dash, not an ISP." -> UiText.text(R.string.catalog_104)
        "Aftermarket CarPlay / Android Auto adapter hotspot (CARLINK-). Head-unit dongle, not the car’s own modem." -> UiText.text(R.string.catalog_105)
        "Rivian phone-as-key, camp speaker, or sensor. Phones can advertise Rivian Sensor." -> UiText.text(R.string.catalog_106)
        "Govee light or hygrometer. Lights usually only send a name; hygrometers can decode temp / humidity / battery below." -> UiText.text(R.string.catalog_107)
        "HP home/office printer (ENVY, HP-Print). Office noise. Not HPE Aruba campus Wi-Fi." -> UiText.text(R.string.catalog_108)
        "Mercedes MBUX in-car hotspot. Factory name from the car." -> UiText.text(R.string.catalog_109)
        "Motive (KeepTruckin) electronic logging device / fleet Wi-Fi in a truck." -> UiText.text(R.string.catalog_110)
        "PeopleNet truck ELD / fleet Wi-Fi. Separate from Motive." -> UiText.text(R.string.catalog_111)
        "Goodyear intelligent-tire BLE, not the 315/433 MHz valve-stem TPMS in most cars. Pattern match, not that car." -> UiText.text(R.string.catalog_112)
        "Schrader aftermarket BLE TPMS (AirCheck, trailer, RV). Not the 315/433 MHz factory stems." -> UiText.text(R.string.catalog_113)
        "Pacific Industrial OEM tire electronics. BLE TPMS on some newer vehicles." -> UiText.text(R.string.catalog_114)
        "Huf tire sensor or vehicle access (door handle / PEPS). Not only a valve stem." -> UiText.text(R.string.catalog_115)
        "FOBO aftermarket BLE tire-pressure sensor. Motorcycle or car. Pattern match, not that vehicle." -> UiText.text(R.string.catalog_116)
        "Aftermarket BLE valve-cap tire sensor (TPMS1 / FBB0 family). Decoded fields can show wheel, pressure, temperature, battery, and alarm. Pattern match, not that vehicle." -> UiText.text(R.string.catalog_117)
        "SYTPMS / BR bicycle or scooter BLE tire sensor. Decoded fields can show gauge pressure, temperature, battery, and motion. Pattern match, not that vehicle." -> UiText.text(R.string.catalog_118)
        "TireCheck BLE tire-pressure sensor. Pattern match, not that vehicle." -> UiText.text(R.string.catalog_119)
        "Bluetooth SIG Tire Pressure Monitoring System service. Any sensor that advertises that standard service." -> UiText.text(R.string.catalog_120)
        "Ruuvi broadcast sensor tag (temp / humidity / pressure / motion). Decoded fields on this page parse the sensor payload." -> UiText.text(R.string.catalog_121)
        "Blue Maestro Tempo Disc temperature / humidity logger. Decoded fields can show version, battery, and temperature." -> UiText.text(R.string.catalog_122)
        "SensorPush temperature / humidity logger." -> UiText.text(R.string.catalog_123)
        "Samsara fleet tracker or vehicle Wi-Fi. Truck / van telematics, adjacent to Motive." -> UiText.text(R.string.catalog_124)
        "TP-Link Tapo home camera. Consumer camera, not a roadside pole." -> UiText.text(R.string.catalog_125)
        "Reolink home / small-business camera. Consumer camera, not a roadside pole." -> UiText.text(R.string.catalog_126)
        "Hikvision camera. Common on commercial CCTV and some public poles." -> UiText.text(R.string.catalog_127)
        "Hikvision cameras. Common on commercial CCTV and some public poles. Name-only. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_128)
        "Dahua camera. Common on commercial CCTV and some public poles." -> UiText.text(R.string.catalog_129)
        "Dahua cameras. Common on commercial CCTV and some public poles. Name-only. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_130)
        "Meshtastic LoRa mesh node. Off-grid text/location radios, not cellular." -> UiText.text(R.string.catalog_131)
        "Helium / LoRaWAN hotspot when it advertises a name." -> UiText.text(R.string.catalog_132)
        "MeshCore LoRa companion radio. Off-grid text/location, not cellular. Name-only — Nordic UART UUID is every ESP32 serial board and is not this row." -> UiText.text(R.string.catalog_133)
        "goTenna Mesh or Pro companion radio. Pairs over BLE; the mesh itself is UHF and Fieldwatch cannot hear it. Pro is sold to agencies. Pattern match, not that operator." -> UiText.text(R.string.catalog_134)
        "Seeed SenseCAP LoRaWAN / Helium indoor gateway setup AP (SenseCAP_XXXXXX). Quiet once it is on Ethernet. Helium-named units can also hit the Helium row." -> UiText.text(R.string.catalog_135)
        "RAKwireless WisGate LoRaWAN gateway setup AP (RAK7268_XXXX and similar). Quiet once it is on Ethernet." -> UiText.text(R.string.catalog_136)
        "Genetec AutoVu parking or roadside plate reader." -> UiText.text(R.string.catalog_137)
        "Genetec AutoVu is municipal / parking ALPR — reads plates at lots and roadside. Name-only when advertised. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_138)
        "Iteris roadside Bluetooth travel-time reader (Vantage Velocity, now BlueTOAD Spectra / Spectra CV). Samples phones, headsets, and in-car Bluetooth as vehicles pass; matching the same ID at two points gives speed. About 100 m. A sample, not a full count. Quiet or Ethernet-only cabinets may not advertise. Spectra CV also uses 5.9 GHz C-V2X, which Fieldwatch cannot hear. IEEE Iteris OUI can also hit other Iteris roadside kit. Pattern match, not that cabinet." -> UiText.text(R.string.catalog_139)
        "BLIP Systems BlipTrack roadside Bluetooth/Wi-Fi travel-time sensor. Same job as BlueTOAD Spectra: samples passing phones and in-car radios at two points for speed. Quiet or Ethernet-only cabinets may not advertise. Pattern match, not that cabinet." -> UiText.text(R.string.catalog_140)
        "Hanwha Vision / Wisenet camera (ex-Samsung Techwin). Common on commercial CCTV and some public poles." -> UiText.text(R.string.catalog_141)
        "Hanwha Vision / Wisenet cameras. Common on commercial CCTV and some public poles. A *_WISENET setup SSID is the stronger hit; IEEE 00:09:18 is Samsung Techwin. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_142)
        "Uniview / UNV / Uniarch camera. Common on commercial CCTV and some public poles." -> UiText.text(R.string.catalog_143)
        "Uniview / UNV cameras. Common on commercial CCTV and some public poles. IEEE Zhejiang Uniview OUIs or a Uniview / UNV- name. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_144)
        "Rhombus cloud camera. BLE is loudest when the camera is unregistered or offline." -> UiText.text(R.string.catalog_145)
        "Rhombus cloud cameras on buildings and some public sites. IEEE CC:47:BD or a Rhombus name. BLE often only while unregistered or offline. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_146)
        "Rekor highway or transit plate reader." -> UiText.text(R.string.catalog_147)
        "Rekor is highway / transit ALPR — reads plates on roads and at checkpoints. Name-only. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_148)
        "Axon body-worn camera, in-car system, dock, or TASER. Quiet or LTE-only units will not appear." -> UiText.text(R.string.catalog_149)
        "Axon body-worn, in-car (Fleet), dock, or TASER gear. IEEE OUI 00:25:DF is Axon Enterprise. Body 3/4 often advertise BLE on that public OUI while worn. A name like Axon Body is a pattern, not that officer. Quiet or LTE-only units will not appear. The word Axon also hits some ZTE phones. Look with your eyes. Not identity." -> UiText.text(R.string.catalog_150)
        "WatchGuard Video body-worn or in-car camera (now Motorola). Not the WatchGuard firewall company. Patrol units may stay quiet." -> UiText.text(R.string.catalog_151)
        "WatchGuard Video body-worn or in-car (VISTA / V300 family). IEEE OUI 00:1D:96 is WatchGuard Video, not the WatchGuard firewall company. Patrol units may stay quiet. Pattern match, not identity. Look with your eyes." -> UiText.text(R.string.catalog_152)
        "Digital Ally body-worn or in-car camera (FirstVu / EVO). Quiet or LTE-only units will not appear." -> UiText.text(R.string.catalog_153)
        "Digital Ally body-worn or in-car (FirstVu / EVO family). IEEE OUI 00:23:BD is Digital Ally, Inc. — camera gear, not a chip vendor. Patrol units may stay on LTE and stay quiet. Pattern match, not that officer. Look with your eyes. Not identity." -> UiText.text(R.string.catalog_154)
        "Reveal Media / BodyWorn camera. Common in UK and some US agencies. Quiet units will not appear." -> UiText.text(R.string.catalog_155)
        "Reveal Media body-worn camera (D-series / BodyWorn). Name-only when advertised. Patrol units may stay quiet. Pattern match, not that officer. Look with your eyes." -> UiText.text(R.string.catalog_156)
        "Wolfcom body-worn or in-car camera. Quiet units will not appear." -> UiText.text(R.string.catalog_157)
        "Wolfcom body-worn or in-car camera. Name-only when advertised. Patrol units may stay quiet. Pattern match, not that officer. Look with your eyes." -> UiText.text(R.string.catalog_158)
        "Panasonic i-PRO camera or Arbitrator in-car system. Panasonic TVs and phones use other names." -> UiText.text(R.string.catalog_159)
        "Panasonic i-PRO camera or Arbitrator in-car video. Used on buildings and some patrol cars — video and sometimes plates. Name-only (i-PRO / Arbitrator). Not every Panasonic radio. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_160)
        "Avigilon building or municipal camera, sometimes with LPR." -> UiText.text(R.string.catalog_161)
        "Motorola Avigilon cameras / LPR. Used on municipal poles and commercial sites — video and sometimes plates. Name-only. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_162)
        "Axis camera, common on municipal poles and public CCTV." -> UiText.text(R.string.catalog_163)
        "Axis Communications cameras, common on municipal poles and public CCTV. Name-only (AXIS-). Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_164)
        "Hayden AI bus- or vehicle-mounted camera used for parking and traffic enforcement." -> UiText.text(R.string.catalog_165)
        "Hayden AI cameras ride on buses and city vehicles — video and plates. Name-only when advertised. LTE-only units will not appear. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_166)
        "Miovision intersection / traffic camera (SmartLink / Scout)." -> UiText.text(R.string.catalog_167)
        "Miovision traffic cameras at intersections. Video and sometimes plates. Name-only when advertised. Many units are cellular-only and stay quiet. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_168)
        "Tattile ALPR camera, common on European roads and some US sites." -> UiText.text(R.string.catalog_169)
        "Tattile plate readers on roads and at gates. Name-only when advertised. Pattern match, not that camera. Look with your eyes." -> UiText.text(R.string.catalog_170)
        "LiveView Technologies (LVT) solar surveillance trailer. Most units are cellular-only and will not appear." -> UiText.text(R.string.catalog_171)
        "LVT / LiveView solar camera trailer — parking lots, construction, some city parks. Video and sometimes plates. Most units use cellular and stay quiet on Wi-Fi/BLE. A LiveView or LVT- name is a pattern, not that trailer. Look with your eyes." -> UiText.text(R.string.catalog_172)
        "UniFi / Ubiquiti name on Wi-Fi or BLE. Prefer UniFi AP for BSSID hits. Instant cameras stay on UniFi Protect." -> UiText.text(R.string.catalog_173)
        "UniFi / Ubiquiti Wi-Fi access point (including airMAX / AmpliFi). Renamed SSIDs still hit on the board vendor or Ubiquiti vendor tag. Instant cameras stay on UniFi Protect." -> UiText.text(R.string.catalog_174)
        "Cheap hobby UART module advertised under a default name (HM-10, JDY, CC41, ESP32 BLE). Common on printers, cars, and DIY. Fieldwatch does not see Classic HC-05/HC-06." -> UiText.text(R.string.catalog_175)
        "These default BLE serial names are cheap hobby modules. Some pump/ATM overlays have used boards like this so someone nearby can pull data over Bluetooth. The same modules show up on printers, cars, and DIY. If this radio is loud next to a card reader, treat it with caution and look with your eyes. Not proof of a skimmer. A miss is not a clean bill (name changed, Classic HC-05/HC-06, or cellular). Fieldwatch does not connect and does not try default PINs. Fieldwatch does not see Classic HC-05/HC-06." -> UiText.text(R.string.catalog_176)
        "Ray-Ban Meta / Oakley Meta smart glasses, or a Quest / other Meta wearable." -> UiText.text(R.string.catalog_177)
        "Meta / Luxottica BLE — often Ray-Ban Meta smart glasses. The same company IDs show up on Quest headsets and other Meta wearables. Not proof someone is recording. A miss is not a clean bill (paired and quiet, asleep, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_178)
        "Snap Spectacles or other Snap BLE product." -> UiText.text(R.string.catalog_179)
        "Snapchat BLE company ID — used by Snap Spectacles. Other Snap BLE products could match. Not proof of recording. Look with your eyes." -> UiText.text(R.string.catalog_180)
        "Vuzix smart glasses or other Vuzix BLE wearable." -> UiText.text(R.string.catalog_181)
        "Vuzix BLE glasses. Not proof of recording. A miss is not a clean bill (paired and quiet, asleep, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_182)
        "Brilliant Labs Frame AR glasses." -> UiText.text(R.string.catalog_183)
        "Brilliant Labs Frame AR glasses. BLE service 7A230001. Not proof someone is recording. A miss is not a clean bill (off, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_184)
        "Even Realities G1 glasses. Name-only (Even G1). Nordic UART is too common to use as a rule." -> UiText.text(R.string.catalog_185)
        "Even Realities G1 glasses. Name-only when advertised (Even G1). Not proof of recording. A miss is not a clean bill (off, renamed, or paired and quiet). Look with your eyes." -> UiText.text(R.string.catalog_186)
        "Hak5 WiFi Pineapple setup or management AP. Cloned café SSIDs from PineAP look like ordinary Wi-Fi and will not hit this row." -> UiText.text(R.string.catalog_187)
        "Hak5 WiFi Pineapple setup or management AP (Pineapple_XXXX). That is the admin radio, not every rogue SSID PineAP might impersonate — those look like ordinary café Wi-Fi. A miss is not a clean bill (renamed, or only cloning). Pattern match, not identity. Look with your eyes." -> UiText.text(R.string.catalog_188)
        "Flipper Zero (or other Flipper Devices). Default name starts with Flipper; custom firmware can hide it." -> UiText.text(R.string.catalog_189)
        "Flipper Zero (or other Flipper Devices) BLE. Default name starts with Flipper; newer units use IEEE OUI 0C:FA:22. Custom firmware can change the name and MAC. Not proof of an attack. A miss is not a clean bill (Bluetooth off, or renamed). Look with your eyes." -> UiText.text(R.string.catalog_190)
        "Pwnagotchi-style Wi-Fi handshake collector. Classic units use a distinctive BSSID and the name pwnagotchi." -> UiText.text(R.string.catalog_191)
        "Pwnagotchi-style Wi-Fi handshake collector. Classic units beacon BSSID de:ad:be:ef:de:ad. A pwnagotchi name is a pattern. Not proof of an attack. Look with your eyes." -> UiText.text(R.string.catalog_192)
        "ESP32 Marauder or Spacehuhn-style Wi-Fi deauther on a default name. Same boards are DIY; renamed units miss." -> UiText.text(R.string.catalog_193)
        "ESP32 Marauder or Spacehuhn-style Wi-Fi deauther default names. Same boards are DIY. Not proof of an attack. A miss is not a clean bill (renamed). Look with your eyes." -> UiText.text(R.string.catalog_194)
        "GhostESP ESP32 audit firmware. Default setup AP is GhostNet. Same boards are DIY; renamed units miss." -> UiText.text(R.string.catalog_195)
        "GhostESP ESP32 audit firmware default AP (GhostNet). Same boards are DIY. Not proof of an attack. A miss is not a clean bill (renamed). Look with your eyes." -> UiText.text(R.string.catalog_196)
        "Bruce ESP32 pentest firmware. Default setup AP is BruceNet. Same boards are DIY; renamed units and evil-portal SSIDs miss." -> UiText.text(R.string.catalog_197)
        "Bruce ESP32 pentest firmware default AP (BruceNet). Same boards are DIY. Evil-portal SSIDs look like ordinary Wi-Fi and will not hit this row. Not proof of an attack. Look with your eyes." -> UiText.text(R.string.catalog_198)
        "Porkchop pentest firmware on a Cardputer or Cheap Yellow Display. Default AP name PORKCHOP. BLE spam that spoofs Apple/Android is not this row." -> UiText.text(R.string.catalog_199)
        "M5PORKCHOP / Porkchop — pocket Wi-Fi pentest firmware (Cardputer or Cheap Yellow Display). Default CYD remote AP is named PORKCHOP. BACON-mode fake APs brand vendor IE 50:52:4B. A miss is not a clean bill (renamed, passive only, or no AP). Pattern match, not identity, not proof of an attack. Look with your eyes." -> UiText.text(R.string.catalog_200)
        "Nintendo Pokémon GO Plus or Plus + wrist accessory. Not a Joy-Con or Switch." -> UiText.text(R.string.catalog_201)
        "Hatch Rest / Restore / Mini sound machine. Nursery / bedroom noise." -> UiText.text(R.string.catalog_202)
        "Orbit B-hyve hose timer / irrigation." -> UiText.text(R.string.catalog_203)
        "Samsung Family Hub fridge, range, or oven setup Wi-Fi. Not a SmartTag." -> UiText.text(R.string.catalog_204)
        "EcoWater / water-softener setup Wi-Fi. Home plumbing IoT." -> UiText.text(R.string.catalog_205)
        "Fieldy pendant — wearable AI note-taker." -> UiText.text(R.string.catalog_206)
        "Fieldy wearable AI note-taker (pendant). It records conversations and transcribes them. Not proof someone is recording you. A miss is not a clean bill (off, paired and quiet, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_207)
        "Plaud Note / NotePin AI meeting recorder." -> UiText.text(R.string.catalog_208)
        "Plaud Note / NotePin AI recorder. It records meetings. Not proof someone is recording you. A miss is not a clean bill (off, renamed, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_209)
        "Limitless / Rewind AI pendant — wearable conversation recorder." -> UiText.text(R.string.catalog_210)
        "Limitless Pendant wearable recorder. BLE service 632de001. It records conversations. Not proof someone is recording you. A miss is not a clean bill (off, paired and quiet, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_211)
        "Bee Pioneer wearable recorder (now Amazon). Always-on audio capture." -> UiText.text(R.string.catalog_212)
        "Bee Pioneer wearable recorder (Amazon). BLE service 03d5d5c4. It records conversations. Not proof someone is recording you. A miss is not a clean bill (off, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_213)
        "Omi / OpenGlass wearable recorder or camera glasses. Arduino-default 19B10000 is too common to use as a rule." -> UiText.text(R.string.catalog_214)
        "Omi pendant or OpenGlass camera glasses. Name or BLE service 23ba7924. It can record audio (OpenGlass also has a camera). Not proof someone is recording you. A miss is not a clean bill (off, renamed, or a DIY board using other names). Look with your eyes." -> UiText.text(R.string.catalog_215)
        "Friend AI necklace — wearable companion that listens." -> UiText.text(R.string.catalog_216)
        "Friend Pendant / necklace. BLE service 1a3fd0e7. It listens to conversations. Not proof someone is recording you. A miss is not a clean bill (off, or a different brand). Look with your eyes." -> UiText.text(R.string.catalog_217)
        "BLE LED message display. The advertised name is the sign text, not a product name." -> UiText.text(R.string.catalog_218)
        "Electronic shelf label (store price tag) on the Bluetooth ESL service. Most Hanshow / SES-imagotag tags use a private radio and will not hit this." -> UiText.text(R.string.catalog_219)
        "UniFi Protect Instant camera in BLE setup. Not a UniFi Wi-Fi access point." -> UiText.text(R.string.catalog_220)
        "Tesla BLE tire sensor. Decoded fields can show pressure, temperature, and battery when the sensor is awake. Pattern match, not that car. Phone-as-key stays on the Tesla row." -> UiText.text(R.string.catalog_221)
        "RadiaCode handheld radiation detector." -> UiText.text(R.string.catalog_222)
        "LG webOS TV. Unnamed LG radios can also hit this row." -> UiText.text(R.string.catalog_223)
        "Roku streaming stick or Roku TV. Often a hidden Wi-Fi Direct AP for the remote. Not an ISP router." -> UiText.text(R.string.catalog_224)
        "Nespresso machine (Vertuo / Barista)." -> UiText.text(R.string.catalog_225)
        "Epson EcoTank or WorkForce printer (Wi-Fi Direct or BLE)." -> UiText.text(R.string.catalog_226)
        "Shokz bone-conduction headphones (OpenRun / OpenFit). Worn on the head, not a tracker." -> UiText.text(R.string.catalog_227)
        "In-flight drone digital license plate (ASTM / FAA Remote ID). Decoded fields can show ID, position, heading, and operator. Pattern match, not a tail number. Wi-Fi Remote ID often misses on stock Android." -> UiText.text(R.string.catalog_228)
        "Skydio drone (common in US public-safety / enterprise). In-flight Remote ID is often Wi-Fi and easy to miss — the Remote ID row is the license plate." -> UiText.text(R.string.catalog_229)
        "Autel drone, controller, or setup Wi-Fi. In-flight digital license plate is the Remote ID row." -> UiText.text(R.string.catalog_230)
        "Parrot ANAFI or Bebop drone. In-flight digital license plate is the Remote ID row. Not a Parrot car kit." -> UiText.text(R.string.catalog_231)
        "HOVERAir pocket selfie drone. In-flight digital license plate (PRO / PROMAX) is the Remote ID row." -> UiText.text(R.string.catalog_232)
        "Cradlepoint vehicle router (IBR / R-series). Common in police, EMS, utilities, and commercial fleets. Hidden SSIDs still hit on the board vendor." -> UiText.text(R.string.catalog_233)
        "Ericsson Cradlepoint vehicle router (IBR / R-series). Common in US police and public-safety fleets; also utilities, EMS, and commercial fleet. Hidden or renamed SSIDs still hit on the CradlePoint IEEE OUI. Pattern match, not that agency or that car. Look with your eyes." -> UiText.text(R.string.catalog_234)
        "Sierra Wireless AirLink vehicle / fleet gateway. Common in public-safety and commercial fleets. Hidden SSIDs still hit on the board vendor." -> UiText.text(R.string.catalog_235)
        "Sierra Wireless AirLink vehicle gateway. Common in US police and public-safety fleets; also commercial fleet. Hidden or renamed SSIDs still hit on the Sierra Wireless IEEE OUI. Pattern match, not that agency or that car. Look with your eyes." -> UiText.text(R.string.catalog_236)
        "Compex vehicle or agency Wi-Fi access point. Same boards appear on other Compex radios." -> UiText.text(R.string.catalog_237)
        "Compex Wi-Fi AP. Some US public-safety agencies use these in vehicles. The same IEEE OUIs appear on other Compex radios. Pattern match, not that agency. Look with your eyes." -> UiText.text(R.string.catalog_238)
        "Novatel Wireless / Inseego vehicle radio. The same prefix is also on some consumer MiFi hotspots." -> UiText.text(R.string.catalog_239)
        "Novatel Wireless / Inseego OUI 28:80:A2. Reported in public-safety vehicle AP work. Same prefix is also on some Inseego consumer MiFi radios. Pattern match, not that agency. Look with your eyes." -> UiText.text(R.string.catalog_240)
        "Utility, Inc vehicle or public-safety access point." -> UiText.text(R.string.catalog_241)
        "Utility, Inc radio. Reported in public-safety vehicle AP work. Pattern match, not that agency. Look with your eyes." -> UiText.text(R.string.catalog_242)
        "Cisco Aironet / Catalyst / Business access point. Fieldwatch sees AP beacons, not phones or switches. Meraki has its own row." -> UiText.text(R.string.catalog_243)
        "HPE Aruba campus or Instant On Wi-Fi access point. An HPE BSSID here is an AP, not a server. Not an HP printer." -> UiText.text(R.string.catalog_244)
        "RUCKUS Unleashed / ZoneFlex campus access point. Not the Arris cable-modem family." -> UiText.text(R.string.catalog_245)
        "Ruijie / Reyee campus or SMB access point." -> UiText.text(R.string.catalog_246)
        "Fortinet FortiAP / FortiWiFi campus or branch access point." -> UiText.text(R.string.catalog_247)
        "MikroTik RouterOS access point or travel router." -> UiText.text(R.string.catalog_248)
        "EnGenius Cloud / ECW access point." -> UiText.text(R.string.catalog_249)
        "Zyxel home or SMB gateway / access point." -> UiText.text(R.string.catalog_250)
        "Peplink / Pepwave travel or branch router." -> UiText.text(R.string.catalog_251)
        "OpenWrt factory SSID on a flashed travel / DIY router that was never renamed." -> UiText.text(R.string.catalog_252)
        "Arris / SURFboard cable gateway. After the ISP renames the Wi-Fi, the board vendor still hits." -> UiText.text(R.string.catalog_253)
        "Juniper Mist campus access point. Cloud SSIDs are site names; the board vendor is the hit." -> UiText.text(R.string.catalog_254)
        "T-Mobile Home Internet or hotspot. Gateways are often HUMAX / Arcadyan / Askey OEM." -> UiText.text(R.string.catalog_255)
        "HUMAX 5G or cable gateway. Often T-Mobile Home Internet in the field." -> UiText.text(R.string.catalog_256)
        "Sagemcom ISP gateway. Common Comcast / other cable OEM." -> UiText.text(R.string.catalog_257)
        "Arcadyan ISP gateway or mesh. Common Verizon / T-Mobile OEM." -> UiText.text(R.string.catalog_258)
        "Askey 5G / ISP gateway. Common T-Mobile Home Internet OEM." -> UiText.text(R.string.catalog_259)
        "Calix fiber gateway (GigaSpire class). After rename, the board vendor still hits." -> UiText.text(R.string.catalog_260)
        "Nokia ISP gateway or small cell. Not a Nokia phone." -> UiText.text(R.string.catalog_261)
        "AirTies ISP mesh extender. Carrier-issued home mesh." -> UiText.text(R.string.catalog_262)
        "Tenda consumer router or extender." -> UiText.text(R.string.catalog_263)
        "WAVLINK consumer travel / home router." -> UiText.text(R.string.catalog_264)
        "Sercomm ISP gateway. Common cable / fiber OEM." -> UiText.text(R.string.catalog_265)
        "Luxul / Legrand small-business access point." -> UiText.text(R.string.catalog_266)
        "Sophos firewall or access point. Campus / SMB Wi-Fi, not a camera pole." -> UiText.text(R.string.catalog_267)
        "Vehicle Wi-Fi from an AUMOVIO (ex-Continental) module. The car’s AP, not an ISP router." -> UiText.text(R.string.catalog_268)
        "CenturyLink factory gateway name. Renamed fiber Wi-Fi misses this row." -> UiText.text(R.string.catalog_269)
        "GM in-car hotspot (Cadillac, GMC, Buick). myChevrolet has its own row. BSSID is often randomized." -> UiText.text(R.string.catalog_270)
        "Audi in-car MMI hotspot. Factory name from the car, not a dealer." -> UiText.text(R.string.catalog_271)
        "Extreme Networks campus access point. Cloud SSIDs are site names; the board vendor is the hit." -> UiText.text(R.string.catalog_272)
        "Adtran fiber gateway. Common CenturyLink / Lumen / Quantum Fiber OEM." -> UiText.text(R.string.catalog_273)
        "Cambium or IgniteNet outdoor / WISP access point." -> UiText.text(R.string.catalog_274)
        "TRENDnet consumer access point." -> UiText.text(R.string.catalog_275)
        "Cudy travel or home router." -> UiText.text(R.string.catalog_276)
        "Control4 / Wattbox home-AV processor or power unit." -> UiText.text(R.string.catalog_277)
        "Vantiva (ex-Technicolor) ISP gateway. After the ISP renames the Wi-Fi, the board vendor still hits." -> UiText.text(R.string.catalog_278)
        "Hitron cable gateway. Common Xfinity OEM; the Xfinity name row can also hit." -> UiText.text(R.string.catalog_279)
        "Actiontec FiOS / Frontier gateway. Often a Verizon box; the Verizon name row can also hit." -> UiText.text(R.string.catalog_280)
        "Buffalo AirStation home router." -> UiText.text(R.string.catalog_281)
        "Grandstream GWN office access point." -> UiText.text(R.string.catalog_282)
        "Edgecore campus / open Wi-Fi access point. Cloud SSIDs are site names; the board vendor is the hit." -> UiText.text(R.string.catalog_283)
        "WatchGuard firewall or access point. Not WatchGuard Video body-worn cameras." -> UiText.text(R.string.catalog_284)
        "Mojo / Arista Cognitive Wi-Fi campus access point." -> UiText.text(R.string.catalog_285)
        "Winegard RV or marine Wi-Fi antenna / router." -> UiText.text(R.string.catalog_286)
        "Inseego 5G / MiFi hotspot." -> UiText.text(R.string.catalog_287)
        "Franklin 5G / LTE home-internet gateway (often carrier-issued). Guest SSIDs still hit." -> UiText.text(R.string.catalog_288)
        "Synology NAS or router access point." -> UiText.text(R.string.catalog_289)
        "Honeywell Xenon healthcare barcode scanner or its charge base (white, disinfectant-ready). Clinic / hospital kit, not a home thermostat and not a warehouse-only Xenon." -> UiText.text(R.string.catalog_290)
        "Omron blood-pressure cuff or body-composition scale. Home / clinic health kit, not industrial Omron." -> UiText.text(R.string.catalog_291)
        "Withings (Nokia Health) scale or BPM Connect cuff. Not a Nokia phone and not a Nokia ISP gateway." -> UiText.text(R.string.catalog_292)
        "Dexcom continuous glucose monitor (G6 / G7). Pattern match, not a patient." -> UiText.text(R.string.catalog_293)
        "Accel X" -> UiText.text(R.string.catalog_294)
        "Accel Y" -> UiText.text(R.string.catalog_295)
        "Accel Z" -> UiText.text(R.string.catalog_296)
        "Alarm" -> UiText.text(R.string.catalog_297)
        "Altitude (baro)" -> UiText.text(R.string.catalog_298)
        "Altitude (HAE)" -> UiText.text(R.string.catalog_299)
        "App code" -> UiText.text(R.string.catalog_300)
        "Battery" -> UiText.text(R.string.catalog_301)
        "Bound" -> UiText.text(R.string.catalog_302)
        "Channel" -> UiText.text(R.string.catalog_303)
        "Counter" -> UiText.text(R.string.catalog_304)
        "Ephemeral ID" -> UiText.text(R.string.catalog_305)
        "Format" -> UiText.text(R.string.catalog_306)
        "Frame" -> UiText.text(R.string.catalog_307)
        "Heading" -> UiText.text(R.string.catalog_308)
        "Height" -> UiText.text(R.string.catalog_309)
        "Horizontal speed" -> UiText.text(R.string.catalog_310)
        "Humidity" -> UiText.text(R.string.catalog_311)
        "ID type" -> UiText.text(R.string.catalog_312)
        "Latitude" -> UiText.text(R.string.catalog_313)
        "Log interval" -> UiText.text(R.string.catalog_314)
        "Longitude" -> UiText.text(R.string.catalog_315)
        "MAC in payload" -> UiText.text(R.string.catalog_316)
        "Media offload" -> UiText.text(R.string.catalog_317)
        "Message" -> UiText.text(R.string.catalog_318)
        "Mode" -> UiText.text(R.string.catalog_319)
        "Model" -> UiText.text(R.string.catalog_320)
        "Model id" -> UiText.text(R.string.catalog_321)
        "Movement" -> UiText.text(R.string.catalog_322)
        "Moving" -> UiText.text(R.string.catalog_323)
        "Network ID" -> UiText.text(R.string.catalog_324)
        "New media" -> UiText.text(R.string.catalog_325)
        "Operator ID" -> UiText.text(R.string.catalog_326)
        "Operator lat" -> UiText.text(R.string.catalog_327)
        "Operator lon" -> UiText.text(R.string.catalog_328)
        "Packet" -> UiText.text(R.string.catalog_329)
        "Pairing" -> UiText.text(R.string.catalog_330)
        "Pressure" -> UiText.text(R.string.catalog_331)
        "Private ID" -> UiText.text(R.string.catalog_332)
        "Processor" -> UiText.text(R.string.catalog_333)
        "Product" -> UiText.text(R.string.catalog_334)
        "Protocol" -> UiText.text(R.string.catalog_335)
        "Rotating" -> UiText.text(R.string.catalog_336)
        "Schema" -> UiText.text(R.string.catalog_337)
        "Self ID" -> UiText.text(R.string.catalog_338)
        "Sensor id" -> UiText.text(R.string.catalog_339)
        "Sequence" -> UiText.text(R.string.catalog_340)
        "Serial" -> UiText.text(R.string.catalog_341)
        "Standing still" -> UiText.text(R.string.catalog_342)
        "Status" -> UiText.text(R.string.catalog_343)
        "Stored logs" -> UiText.text(R.string.catalog_344)
        "Temperature" -> UiText.text(R.string.catalog_345)
        "TX power" -> UiText.text(R.string.catalog_346)
        "UA type" -> UiText.text(R.string.catalog_347)
        "UAS ID" -> UiText.text(R.string.catalog_348)
        "Vendor" -> UiText.text(R.string.catalog_349)
        "Version" -> UiText.text(R.string.catalog_350)
        "Vertical speed" -> UiText.text(R.string.catalog_351)
        "Weave device id" -> UiText.text(R.string.catalog_352)
        "Wheel" -> UiText.text(R.string.catalog_353)
        "Wi-Fi AP" -> UiText.text(R.string.catalog_354)
        "Aeroplane" -> UiText.text(R.string.catalog_355)
        "Airborne" -> UiText.text(R.string.catalog_356)
        "Airship" -> UiText.text(R.string.catalog_357)
        "Auth" -> UiText.text(R.string.catalog_358)
        "Basic ID" -> UiText.text(R.string.catalog_359)
        "CAA registration" -> UiText.text(R.string.catalog_360)
        "Emergency" -> UiText.text(R.string.catalog_361)
        "Glider" -> UiText.text(R.string.catalog_362)
        "Ground" -> UiText.text(R.string.catalog_363)
        "Gyroplane" -> UiText.text(R.string.catalog_364)
        "Helicopter / multirotor" -> UiText.text(R.string.catalog_365)
        "Hybrid lift" -> UiText.text(R.string.catalog_366)
        "Location" -> UiText.text(R.string.catalog_367)
        "Message pack" -> UiText.text(R.string.catalog_368)
        "Near its owner. With you the whole sit, this is often your own tag. First heard after the sit started, it is more often someone who joined with their own keys." -> UiText.text(R.string.catalog_369)
        "near owner" -> UiText.text(R.string.catalog_370)
        "nearby" -> UiText.text(R.string.catalog_371)
        "Nearby its owner. With you the whole sit, this is often your own tag. First heard after the sit started, it is more often someone who joined with their own keys." -> UiText.text(R.string.catalog_372)
        "Nest Cam IQ indoor" -> UiText.text(R.string.catalog_373)
        "Nest Cam IQ outdoor" -> UiText.text(R.string.catalog_374)
        "Nest Guard backplate" -> UiText.text(R.string.catalog_375)
        "Nest Heat Link (2nd)" -> UiText.text(R.string.catalog_376)
        "Nest Heat Link backplate" -> UiText.text(R.string.catalog_377)
        "Nest Learning Thermostat (1st/2nd)" -> UiText.text(R.string.catalog_378)
        "Nest Learning Thermostat (1st/2nd) backplate" -> UiText.text(R.string.catalog_379)
        "Nest Learning Thermostat (3rd, EU)" -> UiText.text(R.string.catalog_380)
        "Nest Learning Thermostat (3rd, EU) backplate" -> UiText.text(R.string.catalog_381)
        "Nest Learning Thermostat (3rd)" -> UiText.text(R.string.catalog_382)
        "Nest Learning Thermostat (3rd) backplate" -> UiText.text(R.string.catalog_383)
        "Nest Protect (1st gen)" -> UiText.text(R.string.catalog_384)
        "Nest Protect (2nd gen)" -> UiText.text(R.string.catalog_385)
        "no pressure" -> UiText.text(R.string.catalog_386)
        "None" -> UiText.text(R.string.catalog_387)
        "ok" -> UiText.text(R.string.catalog_388)
        "Other" -> UiText.text(R.string.catalog_389)
        "RID failure" -> UiText.text(R.string.catalog_390)
        "separated" -> UiText.text(R.string.catalog_391)
        "Separated from its owner. The address can hold still for about a day." -> UiText.text(R.string.catalog_392)
        "Serial (CTA-2063)" -> UiText.text(R.string.catalog_393)
        "Session ID" -> UiText.text(R.string.catalog_394)
        "sleep" -> UiText.text(R.string.catalog_395)
        "System" -> UiText.text(R.string.catalog_396)
        "Telemetry" -> UiText.text(R.string.catalog_397)
        "Undeclared" -> UiText.text(R.string.catalog_398)
        "asleep" -> UiText.text(R.string.catalog_399)
        "available" -> UiText.text(R.string.catalog_400)
        "awake" -> UiText.text(R.string.catalog_401)
        "bound" -> UiText.text(R.string.catalog_402)
        "moving" -> UiText.text(R.string.catalog_403)
        "no" -> UiText.text(R.string.catalog_404)
        "off" -> UiText.text(R.string.catalog_405)
        "on" -> UiText.text(R.string.catalog_406)
        "paired" -> UiText.text(R.string.catalog_407)
        "still" -> UiText.text(R.string.catalog_408)
        "unbound" -> UiText.text(R.string.catalog_409)
        "unpaired" -> UiText.text(R.string.catalog_410)
        "yes" -> UiText.text(R.string.catalog_411)
        "zero pressure" -> UiText.text(R.string.catalog_412)
        "Flock Safety Cameras" -> UiText.text(R.string.catalog_413)
        "LiteOn camera radio" -> UiText.text(R.string.catalog_414)
        "Apple AirTags" -> UiText.text(R.string.catalog_415)
        "Samsung SmartTags" -> UiText.text(R.string.catalog_416)
        "Target Atrius basket" -> UiText.text(R.string.catalog_417)
        "Tile Trackers" -> UiText.text(R.string.catalog_418)
        "FS Ext Battery" -> UiText.text(R.string.catalog_419)
        "Apple Device" -> UiText.text(R.string.catalog_420)
        "Apple audio" -> UiText.text(R.string.catalog_421)
        "Microsoft Device" -> UiText.text(R.string.catalog_422)
        "Phone hotspot" -> UiText.text(R.string.catalog_423)
        "DULT tracker" -> UiText.text(R.string.catalog_424)
        "Nest Thermostat" -> UiText.text(R.string.catalog_425)
        "Haiku Fan" -> UiText.text(R.string.catalog_426)
        "Chevrolet hotspot" -> UiText.text(R.string.catalog_427)
        "Goodyear TPMS" -> UiText.text(R.string.catalog_428)
        "Schrader TPMS" -> UiText.text(R.string.catalog_429)
        "Pacific TPMS" -> UiText.text(R.string.catalog_430)
        "FOBO TPMS" -> UiText.text(R.string.catalog_431)
        "Aftermarket TPMS" -> UiText.text(R.string.catalog_432)
        "TPMS service" -> UiText.text(R.string.catalog_433)
        "UniFi AP" -> UiText.text(R.string.catalog_434)
        "Hobby BLE serial" -> UiText.text(R.string.catalog_435)
        "Ray-Ban / Meta glasses" -> UiText.text(R.string.catalog_436)
        "Marauder / Deauther" -> UiText.text(R.string.catalog_437)
        "Samsung appliance" -> UiText.text(R.string.catalog_438)
        "Limitless Pendant" -> UiText.text(R.string.catalog_439)
        "Bee Pendant" -> UiText.text(R.string.catalog_440)
        "Friend Pendant" -> UiText.text(R.string.catalog_441)
        "Retail LED sign" -> UiText.text(R.string.catalog_442)
        "Electronic shelf label" -> UiText.text(R.string.catalog_443)
        "LG webOS TV" -> UiText.text(R.string.catalog_444)
        "GM hotspot" -> UiText.text(R.string.catalog_445)
        "WatchGuard AP" -> UiText.text(R.string.catalog_446)
        "New Signature" -> UiText.text(R.string.catalog_447)
        "H3C Wi-Fi" -> UiText.text(R.string.catalog_domestic_1)
        "Xiaomi Wi-Fi" -> UiText.text(R.string.catalog_domestic_2)
        "MiBeacon ecosystem" -> UiText.text(R.string.catalog_domestic_3)
        "LYWSD03MMC thermometer" -> UiText.text(R.string.catalog_domestic_4)
        "MI_SCALE scale" -> UiText.text(R.string.catalog_domestic_5)
        "Lumi / Aqara switch" -> UiText.text(R.string.catalog_domestic_6)
        "Midea appliance" -> UiText.text(R.string.catalog_domestic_7)
        "LuYuan-Smart vehicle" -> UiText.text(R.string.catalog_domestic_8)
        "AIMA vehicle" -> UiText.text(R.string.catalog_domestic_9)
        "hellobike bicycle" -> UiText.text(R.string.catalog_domestic_10)
        "EDIFIER BLE audio" -> UiText.text(R.string.catalog_domestic_11)
        "Keep_CC fitness equipment" -> UiText.text(R.string.catalog_domestic_12)
        "EZVIZ device" -> UiText.text(R.string.catalog_domestic_13)
        "Daikin Wi-Fi appliance" -> UiText.text(R.string.catalog_domestic_14)
        "H3C Wi-Fi access point or router family. H3C_* SSID or IEEE 04:D7:A5; not an exact model." -> UiText.text(R.string.catalog_domestic_15)
        "Xiaomi Wi-Fi access point or hotspot family. Xiaomi* SSID or IEEE EC:41:18; WPS may advertise a model separately." -> UiText.text(R.string.catalog_domestic_16)
        "MiBeacon / Xiaomi ecosystem BLE advertisement (FE95 or company 038F). Partner products also use this ecosystem; it does not prove Xiaomi manufactured the device." -> UiText.text(R.string.catalog_domestic_17)
        "LYWSD03MMC temperature / humidity sensor name. Encrypted MiBeacon frames alone do not expose temperature or humidity." -> UiText.text(R.string.catalog_domestic_18)
        "MI_SCALE advertised name identifies a Xiaomi ecosystem scale family. Weight / body-composition services alone do not identify a brand or a person." -> UiText.text(R.string.catalog_domestic_19)
        "lumi.switch.acn* BLE name points to a Lumi / Aqara switch family. The suffix is a product code, not a switch state." -> UiText.text(R.string.catalog_domestic_20)
        "midea* Wi-Fi or BLE name points to a Midea appliance family. The name alone does not identify appliance type, exact model, or operating state." -> UiText.text(R.string.catalog_domestic_21)
        "LuYuan-Smart BLE name points to a Luyuan electric two-wheeler radio. It does not identify the rider or prove the vehicle is moving." -> UiText.text(R.string.catalog_domestic_22)
        "AIMA-* BLE name points to an Aima electric two-wheeler radio. The name suffix is not a verified registration or owner identity." -> UiText.text(R.string.catalog_domestic_23)
        "hellobike BLE name points to a Hello bicycle or lock radio. This does not show lock state or identify a rider." -> UiText.text(R.string.catalog_domestic_24)
        "EDIFIER BLE advertised name points to an Edifier audio radio. The name alone does not identify headphone versus speaker model." -> UiText.text(R.string.catalog_domestic_25)
        "Keep_CC_* BLE name points to Keep fitness equipment. The suffix does not reveal a workout, user, or operating state." -> UiText.text(R.string.catalog_domestic_26)
        "IEEE 94:EC:13 identifies an EZVIZ device family on Wi-Fi or a public stable BLE address. It does not prove the device is a camera." -> UiText.text(R.string.catalog_domestic_27)
        "Daikin* Wi-Fi name points to a Daikin appliance or controller family. It does not expose an exact model, room temperature, or operating state." -> UiText.text(R.string.catalog_domestic_28)
        else -> source
    }
}
