package app.fieldwatch

/** Authored report prose; radio values and operator notes pass through unchanged. */
internal object UiDeviceReportText {
    fun text(source: String): String = when (source) {
        "saver" -> UiText.text(R.string.device_report_intensity_saver)
        "balanced" -> UiText.text(R.string.device_report_intensity_balanced)
        "performance" -> UiText.text(R.string.device_report_intensity_performance)
        "Fieldwatch device detail\n" -> UiText.text(R.string.device_report_1)
        "Experimental. Not a legal identity. Stock Android radios — this is what the OS exposed, not a guarantee a tracker or camera is present.\n" -> UiText.text(R.string.device_report_2)
        "Advertised name" -> UiText.text(R.string.device_report_3)
        "What this looks like: " -> UiText.text(R.string.device_report_4)
        "EXTRA ATTENTION (%1\$s): " -> UiText.text(R.string.device_report_5)
        "Pattern match, not identity. Not a safety finding.\n" -> UiText.text(R.string.device_report_6)
        "Extra attention" -> UiText.text(R.string.device_report_7)
        "Notes" -> UiText.text(R.string.device_report_8)
        "Identity" -> UiText.text(R.string.device_report_9)
        "Radio" -> UiText.text(R.string.device_report_10)
        "Wi-Fi access point (beaconing a network)" -> UiText.text(R.string.device_report_11)
        "Bluetooth Low Energy advertiser" -> UiText.text(R.string.device_report_12)
        "Address" -> UiText.text(R.string.device_report_13)
        "Who made it" -> UiText.text(R.string.device_report_14)
        "OUI (vendor prefix)" -> UiText.text(R.string.device_report_15)
        "%1\$s — no IEEE match; randomized addresses usually have none" -> UiText.text(R.string.device_report_16)
        "Network name (SSID)" -> UiText.text(R.string.device_report_17)
        "Hidden — the AP is beaconing but not publishing a name" -> UiText.text(R.string.device_report_18)
        "Signal" -> UiText.text(R.string.device_report_19)
        "How loud here (RSSI)" -> UiText.text(R.string.device_report_20)
        "Last heard" -> UiText.text(R.string.device_report_21)
        "Closer to 0 dBm is louder here, not a distance.\n" -> UiText.text(R.string.device_report_22)
        "Heard range this session" -> UiText.text(R.string.device_report_23)
        "Claimed transmit power" -> UiText.text(R.string.device_report_24)
        "%1\$s dBm — how loud it says it transmits, not a distance" -> UiText.text(R.string.device_report_25)
        "Channel / frequency" -> UiText.text(R.string.device_report_26)
        "channel %1\$s" -> UiText.text(R.string.device_report_27)
        "  ·  %1\$s wide" -> UiText.text(R.string.device_report_28)
        "Wi-Fi generation" -> UiText.text(R.string.device_report_29)
        "Center frequencies" -> UiText.text(R.string.device_report_30)
        "Recent RSSI (oldest → newest)" -> UiText.text(R.string.device_report_31)
        "Bluetooth advertisement" -> UiText.text(R.string.device_report_32)
        "Radio PHY" -> UiText.text(R.string.device_report_33)
        "Connectable" -> UiText.text(R.string.device_report_34)
        "Yes — a phone could open a BLE connection" -> UiText.text(R.string.device_report_35)
        "No — broadcast-only (you can hear it, not join it from this scan)" -> UiText.text(R.string.device_report_36)
        "How often it advertises" -> UiText.text(R.string.device_report_37)
        "%.0f ms between bursts (smaller = chattier on the air)" -> UiText.text(R.string.device_report_38)
        "Periodic advertising" -> UiText.text(R.string.device_report_39)
        "Discoverability" -> UiText.text(R.string.device_report_40)
        "Flags (raw)" -> UiText.text(R.string.device_report_41)
        "What it says it is (Appearance)" -> UiText.text(R.string.device_report_42)
        "Unlisted Appearance 0x%04X" -> UiText.text(R.string.device_report_43)
        "Appearance code" -> UiText.text(R.string.device_report_44)
        "Classic Bluetooth class" -> UiText.text(R.string.device_report_45)
        ". Also offers: " -> UiText.text(R.string.device_report_46)
        "Wi-Fi access point" -> UiText.text(R.string.device_report_47)
        "Encryption / login" -> UiText.text(R.string.device_report_48)
        "Security string" -> UiText.text(R.string.device_report_49)
        "Supported rates" -> UiText.text(R.string.device_report_50)
        "%1\$s Mbps  (* = required basic rate)" -> UiText.text(R.string.device_report_51)
        "Capability string" -> UiText.text(R.string.device_report_52)
        "Decoded fields" -> UiText.text(R.string.device_report_53)
        "Note" -> UiText.text(R.string.device_report_54)
        "Services it offers" -> UiText.text(R.string.device_report_55)
        "Service IDs" -> UiText.text(R.string.device_report_56)
        "Service data %1\$s%2\$s" -> UiText.text(R.string.device_report_57)
        "(empty)" -> UiText.text(R.string.device_report_58)
        "Maker data inside the ad" -> UiText.text(R.string.device_report_59)
        "Not in the Bluetooth company list" -> UiText.text(R.string.device_report_60)
        "Bluetooth company 0x%04X" -> UiText.text(R.string.device_report_61)
        "Raw payload (%1\$s bytes)" -> UiText.text(R.string.device_report_62)
        "Wi-Fi vendor tags" -> UiText.text(R.string.device_report_63)
        " type %d" -> UiText.text(R.string.device_report_64)
        "Vendor OUI %1\$s%2\$s" -> UiText.text(R.string.device_report_65)
        "Unknown IEEE OUI" -> UiText.text(R.string.device_report_66)
        " — extra AP information element, not the SSID." -> UiText.text(R.string.device_report_67)
        "Session" -> UiText.text(R.string.device_report_68)
        "First seen" -> UiText.text(R.string.device_report_69)
        "Last seen" -> UiText.text(R.string.device_report_70)
        "Hits" -> UiText.text(R.string.device_report_71)
        "Last fix" -> UiText.text(R.string.device_report_72)
        "Last fix is the phone’s GPS at hear-time, not a fix on this radio.\n" -> UiText.text(R.string.device_report_73)
        "Matched signatures" -> UiText.text(R.string.device_report_74)
        "Raw advertisement" -> UiText.text(R.string.device_report_75)
        "Presence (15 min)" -> UiText.text(R.string.device_report_76)
        "IEEE board/chip vendor: %1\$s (%2\$s). This is who owns the MAC prefix, not always the product brand." -> UiText.text(R.string.device_report_77)
        "Bluetooth company in the ad: %1\$s (0x%2\$04X)." -> UiText.text(R.string.device_report_78)
        "unlisted" -> UiText.text(R.string.device_report_79)
        "now" -> UiText.text(R.string.device_report_80)
        "Operator path" -> UiText.text(R.string.device_report_81)
        "Fieldwatch %1\$s export" -> UiText.text(R.string.device_report_82)
        "ch %1\$s" -> UiText.text(R.string.device_report_83)
        "Observer: %1\$s" -> UiText.text(R.string.device_report_84)
        "Heard at this phone. Not a radio fix." -> UiText.text(R.string.device_report_85)
        "You are a field RF / privacy analyst with deep knowledge of IEEE OUI, Bluetooth SIG assigned numbers, GAP Appearance, known advertisement formats (iBeacon, Eddystone, Apple Continuity / Find My, Google Fast Pair, Microsoft), and common consumer products." -> UiText.text(R.string.device_report_86)
        "The user wants **as much information as possible** about **this one radio** from a Fieldwatch observation. Fieldwatch is a stock-Android, receive-only Wi-Fi + BLE listener. Use the dump below **and** your public knowledge of registries and formats. Cite which field or byte pattern supports each claim." -> UiText.text(R.string.device_report_87)
        "Constraints you must respect:" -> UiText.text(R.string.device_report_88)
        "- This is **one** advertised radio, not a person, vehicle, or legal identity." -> UiText.text(R.string.device_report_89)
        "- Wi-Fi rows are **access points only**. Associated clients are invisible. Stock Android cannot promiscuously capture stations or probe requests." -> UiText.text(R.string.device_report_90)
        "- BLE rows are advertisers. Randomized MACs are not stable identities and will not stitch across rotations." -> UiText.text(R.string.device_report_91)
        "- Signature / OUI / company / UUID matches are **hypotheses**, not proof of a serial, owner, or that a tracker is present." -> UiText.text(R.string.device_report_92)
        "- GPS stamps (if present) are the **operator phone** at hear-time, not this radio’s location." -> UiText.text(R.string.device_report_93)
        "- Place names (if present) are system reverse-geocode of those stamps. Approximate." -> UiText.text(R.string.device_report_94)
        "- RSSI is loudness at the phone, not a measured distance." -> UiText.text(R.string.device_report_95)
        "- Do not invent fields that are not in the dump. If data is thin, say so and say what would help." -> UiText.text(R.string.device_report_96)
        "- Do not claim this radio is following anyone. Do not give safety advice." -> UiText.text(R.string.device_report_97)
        "- Treat this paste as operationally sensitive (MAC, SSID, payload, GPS)." -> UiText.text(R.string.device_report_98)
        "## Collection context" -> UiText.text(R.string.device_report_99)
        "- Tool: Fieldwatch (app.fieldwatch), receive-only, no association / injection / cloud." -> UiText.text(R.string.device_report_100)
        "## Places (operator GPS, optional)" -> UiText.text(R.string.device_report_101)
        "## Observation dump (verbatim from the detail page)" -> UiText.text(R.string.device_report_102)
        "## Your analysis (required sections)" -> UiText.text(R.string.device_report_103)
        "1. **What it likely is** — Product class, likely brand/family, possible model. Confidence 0–100. Hedge (Most likely / Probably / Could be). List the evidence (name, OUI, company ID, Appearance, services, payload). Competing hypotheses if the data fits more than one product." -> UiText.text(R.string.device_report_104)
        "2. **Registry / format decode** — IEEE OUI or CID; Bluetooth SIG company; GAP Appearance; 16-bit UUIDs; iBeacon UUID/major/minor if present; Fast Pair model ID if present; Apple Continuity type if present. Quote the hex you used. If you recognize a well-known UUID or company from public lists, say so and say the list." -> UiText.text(R.string.device_report_105)
        "3. **What that product typically does** — Phone, tag, speaker, car, AP, camera, mesh node, accessory, etc. Typical radio behavior (always-on beacon vs intermittent)." -> UiText.text(R.string.device_report_106)
        "4. **What Fieldwatch actually saw vs what it cannot see** — Stock Android limits (no station/probe capture, no cellular, no DF). Randomized address implications." -> UiText.text(R.string.device_report_107)
        "5. **Signal and presence** — Loud/quiet here; RSSI range this session; on-air windows. Do not convert RSSI to meters." -> UiText.text(R.string.device_report_108)
        "6. **Signature match** — If Fieldwatch matched a signature, treat it as a filter hit, not identity. Say whether the payload also supports that family. If Notes are in the dump, use them as catalog context for that family. If Extra attention is in the dump, quote it and treat it as an operator caution on a pattern, not proof — separate from Notes." -> UiText.text(R.string.device_report_109)
        "7. **Open questions** — What extra observation (another packet, name, GPS path, a second radio) would raise or lower confidence." -> UiText.text(R.string.device_report_110)
        "8. **Must not conclude** — One short list of claims the dump does **not** support (owner, following, legal ID, distance)." -> UiText.text(R.string.device_report_111)
        "End with a single one-line **takeaway** (what this radio most likely is, and one thing to check next). No safety advice." -> UiText.text(R.string.device_report_112)
        "- Subject: %1\$s titled “%2\$s”." -> UiText.text(R.string.device_report_113)
        "- Scan intensity: %1\$s. Stale after %2\$ss. Brief hold %3\$ss." -> UiText.text(R.string.device_report_114)
        "- Location tags: %1\$s." -> UiText.text(R.string.device_report_115)
        "- Online place names: %1\$s." -> UiText.text(R.string.device_report_116)
        "- Randomized MAC flag: %1\$s." -> UiText.text(R.string.device_report_117)
        "- Hits this session: %1\$s. Gone: %2\$s." -> UiText.text(R.string.device_report_118)
        "- Operator GPS trail samples on this radio: %1\$s (phone path while it was heard)." -> UiText.text(R.string.device_report_119)
        "on" -> UiText.text(R.string.device_report_120)
        "off" -> UiText.text(R.string.device_report_121)
        "yes" -> UiText.text(R.string.device_report_122)
        "no" -> UiText.text(R.string.device_report_123)
        "true" -> UiText.text(R.string.device_report_124)
        "false" -> UiText.text(R.string.device_report_125)
        "Not available" -> UiText.text(R.string.device_report_129)
        else -> UiText.explanation(source)
    }
}
