package app.fieldwatch

import app.fieldwatch.domain.SignatureFamilyHint
import app.fieldwatch.domain.translated

/** Translates authored detail labels only; identifiers and unrecognized values remain intact. */
internal object UiDetailText {
    fun family(hint: SignatureFamilyHint): SignatureFamilyHint = hint.translated(::text)

    private val candidateWhyPatterns = listOf(
        Regex("Same name glob on (\\d+) (APs?|advertisers?) — not a house SSID\\.") to R.string.detail_candidate_name_glob,
        Regex("Same vendor IE on (\\d+) BSSIDs\\. Not WPS / P2P\\.") to R.string.detail_candidate_vendor_ie,
        Regex("Same service UUID on (\\d+) BLE advertisers\\.") to R.string.detail_candidate_service_uuid,
        Regex("Same manufacturer data prefix on (\\d+) BLE advertisers\\.") to R.string.detail_candidate_manufacturer_prefix,
        Regex("Same IEEE OUI on (\\d+) stable BSSIDs\\. Not a chip-module prefix\\.") to R.string.detail_candidate_ieee_oui,
    )

    /** Resolve only complete generated explanations; names, examples and saved candidate data stay raw. */
    fun candidateWhy(source: String): String {
        for ((pattern, resource) in candidateWhyPatterns) {
            val match = pattern.matchEntire(source) ?: continue
            val count = match.groupValues[1]
            return if (match.groupValues.size == 3) {
                UiText.text(resource, count, text(match.groupValues[2]))
            } else UiText.text(resource, count)
        }
        return source
    }

    fun text(source: String): String {
        if (UiText.context.resources.configuration.locales[0].language != "zh") return source
        return when (source) {
            "mfg" -> UiText.text(R.string.detail_mfg_word)
            "Unknown" -> UiText.text(R.string.detail_unknown_1)
            "Phone" -> UiText.text(R.string.detail_phone_2)
            "Computer" -> UiText.text(R.string.detail_computer_3)
            "Computer / Desktop Workstation" -> UiText.text(R.string.detail_computer_desktop_workstation_4)
            "Computer / Server-class Computer" -> UiText.text(R.string.detail_computer_server_class_computer_5)
            "Computer / Laptop" -> UiText.text(R.string.detail_computer_laptop_6)
            "Computer / Handheld PC/PDA (clamshell)" -> UiText.text(R.string.detail_computer_handheld_pc_pda_clamshell_7)
            "Computer / Palm-size PC/PDA" -> UiText.text(R.string.detail_computer_palm_size_pc_pda_8)
            "Computer / Wearable computer (watch size)" -> UiText.text(R.string.detail_computer_wearable_computer_watch_size_9)
            "Computer / Tablet" -> UiText.text(R.string.detail_computer_tablet_10)
            "Computer / Docking Station" -> UiText.text(R.string.detail_computer_docking_station_11)
            "Computer / All in One" -> UiText.text(R.string.detail_computer_all_in_one_12)
            "Computer / Blade Server" -> UiText.text(R.string.detail_computer_blade_server_13)
            "Computer / Convertible" -> UiText.text(R.string.detail_computer_convertible_14)
            "Computer / Detachable" -> UiText.text(R.string.detail_computer_detachable_15)
            "Computer / IoT Gateway" -> UiText.text(R.string.detail_computer_iot_gateway_16)
            "Computer / Mini PC" -> UiText.text(R.string.detail_computer_mini_pc_17)
            "Computer / Stick PC" -> UiText.text(R.string.detail_computer_stick_pc_18)
            "Watch" -> UiText.text(R.string.detail_watch_19)
            "Watch / Sports Watch" -> UiText.text(R.string.detail_watch_sports_watch_20)
            "Watch / Smartwatch" -> UiText.text(R.string.detail_watch_smartwatch_21)
            "Clock" -> UiText.text(R.string.detail_clock_22)
            "Display" -> UiText.text(R.string.detail_display_23)
            "Remote Control" -> UiText.text(R.string.detail_remote_control_24)
            "Eye-glasses" -> UiText.text(R.string.detail_eye_glasses_25)
            "Tag" -> UiText.text(R.string.detail_tag_26)
            "Keyring" -> UiText.text(R.string.detail_keyring_27)
            "Media Player" -> UiText.text(R.string.detail_media_player_28)
            "Barcode Scanner" -> UiText.text(R.string.detail_barcode_scanner_29)
            "Thermometer" -> UiText.text(R.string.detail_thermometer_30)
            "Thermometer / Ear Thermometer" -> UiText.text(R.string.detail_thermometer_ear_thermometer_31)
            "Heart Rate Sensor" -> UiText.text(R.string.detail_heart_rate_sensor_32)
            "Heart Rate Sensor / Heart Rate Belt" -> UiText.text(R.string.detail_heart_rate_sensor_heart_rate_belt_33)
            "Blood Pressure" -> UiText.text(R.string.detail_blood_pressure_34)
            "Blood Pressure / Arm Blood Pressure" -> UiText.text(R.string.detail_blood_pressure_arm_blood_pressure_35)
            "Blood Pressure / Wrist Blood Pressure" -> UiText.text(R.string.detail_blood_pressure_wrist_blood_pressure_36)
            "Human Interface Device" -> UiText.text(R.string.detail_human_interface_device_37)
            "Human Interface Device / Keyboard" -> UiText.text(R.string.detail_human_interface_device_keyboard_38)
            "Human Interface Device / Mouse" -> UiText.text(R.string.detail_human_interface_device_mouse_39)
            "Human Interface Device / Joystick" -> UiText.text(R.string.detail_human_interface_device_joystick_40)
            "Human Interface Device / Gamepad" -> UiText.text(R.string.detail_human_interface_device_gamepad_41)
            "Human Interface Device / Digitizer Tablet" -> UiText.text(R.string.detail_human_interface_device_digitizer_tablet_42)
            "Human Interface Device / Card Reader" -> UiText.text(R.string.detail_human_interface_device_card_reader_43)
            "Human Interface Device / Digital Pen" -> UiText.text(R.string.detail_human_interface_device_digital_pen_44)
            "Human Interface Device / Barcode Scanner" -> UiText.text(R.string.detail_human_interface_device_barcode_scanner_45)
            "Human Interface Device / Touchpad" -> UiText.text(R.string.detail_human_interface_device_touchpad_46)
            "Human Interface Device / Presentation Remote" -> UiText.text(R.string.detail_human_interface_device_presentation_remote_47)
            "Glucose Meter" -> UiText.text(R.string.detail_glucose_meter_48)
            "Running Walking Sensor" -> UiText.text(R.string.detail_running_walking_sensor_49)
            "Running Walking Sensor / In-Shoe Running Walking Sensor" -> UiText.text(R.string.detail_running_walking_sensor_in_shoe_running_walking_sensor_50)
            "Running Walking Sensor / On-Shoe Running Walking Sensor" -> UiText.text(R.string.detail_running_walking_sensor_on_shoe_running_walking_sensor_51)
            "Running Walking Sensor / On-Hip Running Walking Sensor" -> UiText.text(R.string.detail_running_walking_sensor_on_hip_running_walking_sensor_52)
            "Cycling" -> UiText.text(R.string.detail_cycling_53)
            "Cycling / Cycling Computer" -> UiText.text(R.string.detail_cycling_cycling_computer_54)
            "Cycling / Speed Sensor" -> UiText.text(R.string.detail_cycling_speed_sensor_55)
            "Cycling / Cadence Sensor" -> UiText.text(R.string.detail_cycling_cadence_sensor_56)
            "Cycling / Power Sensor" -> UiText.text(R.string.detail_cycling_power_sensor_57)
            "Cycling / Speed and Cadence Sensor" -> UiText.text(R.string.detail_cycling_speed_and_cadence_sensor_58)
            "Control Device" -> UiText.text(R.string.detail_control_device_59)
            "Control Device / Switch" -> UiText.text(R.string.detail_control_device_switch_60)
            "Control Device / Multi-switch" -> UiText.text(R.string.detail_control_device_multi_switch_61)
            "Control Device / Button" -> UiText.text(R.string.detail_control_device_button_62)
            "Control Device / Slider" -> UiText.text(R.string.detail_control_device_slider_63)
            "Control Device / Rotary Switch" -> UiText.text(R.string.detail_control_device_rotary_switch_64)
            "Control Device / Touch Panel" -> UiText.text(R.string.detail_control_device_touch_panel_65)
            "Control Device / Single Switch" -> UiText.text(R.string.detail_control_device_single_switch_66)
            "Control Device / Double Switch" -> UiText.text(R.string.detail_control_device_double_switch_67)
            "Control Device / Triple Switch" -> UiText.text(R.string.detail_control_device_triple_switch_68)
            "Control Device / Battery Switch" -> UiText.text(R.string.detail_control_device_battery_switch_69)
            "Control Device / Energy Harvesting Switch" -> UiText.text(R.string.detail_control_device_energy_harvesting_switch_70)
            "Control Device / Push Button" -> UiText.text(R.string.detail_control_device_push_button_71)
            "Control Device / Dial" -> UiText.text(R.string.detail_control_device_dial_72)
            "Network Device" -> UiText.text(R.string.detail_network_device_73)
            "Network Device / Access Point" -> UiText.text(R.string.detail_network_device_access_point_74)
            "Network Device / Mesh Device" -> UiText.text(R.string.detail_network_device_mesh_device_75)
            "Network Device / Mesh Network Proxy" -> UiText.text(R.string.detail_network_device_mesh_network_proxy_76)
            "Sensor" -> UiText.text(R.string.detail_sensor_77)
            "Sensor / Motion Sensor" -> UiText.text(R.string.detail_sensor_motion_sensor_78)
            "Sensor / Air quality Sensor" -> UiText.text(R.string.detail_sensor_air_quality_sensor_79)
            "Sensor / Temperature Sensor" -> UiText.text(R.string.detail_sensor_temperature_sensor_80)
            "Sensor / Humidity Sensor" -> UiText.text(R.string.detail_sensor_humidity_sensor_81)
            "Sensor / Leak Sensor" -> UiText.text(R.string.detail_sensor_leak_sensor_82)
            "Sensor / Smoke Sensor" -> UiText.text(R.string.detail_sensor_smoke_sensor_83)
            "Sensor / Occupancy Sensor" -> UiText.text(R.string.detail_sensor_occupancy_sensor_84)
            "Sensor / Contact Sensor" -> UiText.text(R.string.detail_sensor_contact_sensor_85)
            "Sensor / Carbon Monoxide Sensor" -> UiText.text(R.string.detail_sensor_carbon_monoxide_sensor_86)
            "Sensor / Carbon Dioxide Sensor" -> UiText.text(R.string.detail_sensor_carbon_dioxide_sensor_87)
            "Sensor / Ambient Light Sensor" -> UiText.text(R.string.detail_sensor_ambient_light_sensor_88)
            "Sensor / Energy Sensor" -> UiText.text(R.string.detail_sensor_energy_sensor_89)
            "Sensor / Color Light Sensor" -> UiText.text(R.string.detail_sensor_color_light_sensor_90)
            "Sensor / Rain Sensor" -> UiText.text(R.string.detail_sensor_rain_sensor_91)
            "Sensor / Fire Sensor" -> UiText.text(R.string.detail_sensor_fire_sensor_92)
            "Sensor / Wind Sensor" -> UiText.text(R.string.detail_sensor_wind_sensor_93)
            "Sensor / Proximity Sensor" -> UiText.text(R.string.detail_sensor_proximity_sensor_94)
            "Sensor / Multi-Sensor" -> UiText.text(R.string.detail_sensor_multi_sensor_95)
            "Sensor / Flush Mounted Sensor" -> UiText.text(R.string.detail_sensor_flush_mounted_sensor_96)
            "Sensor / Ceiling Mounted Sensor" -> UiText.text(R.string.detail_sensor_ceiling_mounted_sensor_97)
            "Sensor / Wall Mounted Sensor" -> UiText.text(R.string.detail_sensor_wall_mounted_sensor_98)
            "Sensor / Multisensor" -> UiText.text(R.string.detail_sensor_multisensor_99)
            "Sensor / Energy Meter" -> UiText.text(R.string.detail_sensor_energy_meter_100)
            "Sensor / Flame Detector" -> UiText.text(R.string.detail_sensor_flame_detector_101)
            "Sensor / Vehicle Tire Pressure Sensor" -> UiText.text(R.string.detail_sensor_vehicle_tire_pressure_sensor_102)
            "Light Fixtures" -> UiText.text(R.string.detail_light_fixtures_103)
            "Light Fixtures / Wall Light" -> UiText.text(R.string.detail_light_fixtures_wall_light_104)
            "Light Fixtures / Ceiling Light" -> UiText.text(R.string.detail_light_fixtures_ceiling_light_105)
            "Light Fixtures / Floor Light" -> UiText.text(R.string.detail_light_fixtures_floor_light_106)
            "Light Fixtures / Cabinet Light" -> UiText.text(R.string.detail_light_fixtures_cabinet_light_107)
            "Light Fixtures / Desk Light" -> UiText.text(R.string.detail_light_fixtures_desk_light_108)
            "Light Fixtures / Troffer Light" -> UiText.text(R.string.detail_light_fixtures_troffer_light_109)
            "Light Fixtures / Pendant Light" -> UiText.text(R.string.detail_light_fixtures_pendant_light_110)
            "Light Fixtures / In-ground Light" -> UiText.text(R.string.detail_light_fixtures_in_ground_light_111)
            "Light Fixtures / Flood Light" -> UiText.text(R.string.detail_light_fixtures_flood_light_112)
            "Light Fixtures / Underwater Light" -> UiText.text(R.string.detail_light_fixtures_underwater_light_113)
            "Light Fixtures / Bollard with Light" -> UiText.text(R.string.detail_light_fixtures_bollard_with_light_114)
            "Light Fixtures / Pathway Light" -> UiText.text(R.string.detail_light_fixtures_pathway_light_115)
            "Light Fixtures / Garden Light" -> UiText.text(R.string.detail_light_fixtures_garden_light_116)
            "Light Fixtures / Pole-top Light" -> UiText.text(R.string.detail_light_fixtures_pole_top_light_117)
            "Light Fixtures / Spotlight" -> UiText.text(R.string.detail_light_fixtures_spotlight_118)
            "Light Fixtures / Linear Light" -> UiText.text(R.string.detail_light_fixtures_linear_light_119)
            "Light Fixtures / Street Light" -> UiText.text(R.string.detail_light_fixtures_street_light_120)
            "Light Fixtures / Shelves Light" -> UiText.text(R.string.detail_light_fixtures_shelves_light_121)
            "Light Fixtures / Bay Light" -> UiText.text(R.string.detail_light_fixtures_bay_light_122)
            "Light Fixtures / Emergency Exit Light" -> UiText.text(R.string.detail_light_fixtures_emergency_exit_light_123)
            "Light Fixtures / Light Controller" -> UiText.text(R.string.detail_light_fixtures_light_controller_124)
            "Light Fixtures / Light Driver" -> UiText.text(R.string.detail_light_fixtures_light_driver_125)
            "Light Fixtures / Bulb" -> UiText.text(R.string.detail_light_fixtures_bulb_126)
            "Light Fixtures / Low-bay Light" -> UiText.text(R.string.detail_light_fixtures_low_bay_light_127)
            "Light Fixtures / High-bay Light" -> UiText.text(R.string.detail_light_fixtures_high_bay_light_128)
            "Fan" -> UiText.text(R.string.detail_fan_129)
            "Fan / Ceiling Fan" -> UiText.text(R.string.detail_fan_ceiling_fan_130)
            "Fan / Axial Fan" -> UiText.text(R.string.detail_fan_axial_fan_131)
            "Fan / Exhaust Fan" -> UiText.text(R.string.detail_fan_exhaust_fan_132)
            "Fan / Pedestal Fan" -> UiText.text(R.string.detail_fan_pedestal_fan_133)
            "Fan / Desk Fan" -> UiText.text(R.string.detail_fan_desk_fan_134)
            "Fan / Wall Fan" -> UiText.text(R.string.detail_fan_wall_fan_135)
            "HVAC" -> UiText.text(R.string.detail_hvac_136)
            "HVAC / Thermostat" -> UiText.text(R.string.detail_hvac_thermostat_137)
            "HVAC / Humidifier" -> UiText.text(R.string.detail_hvac_humidifier_138)
            "HVAC / De-humidifier" -> UiText.text(R.string.detail_hvac_de_humidifier_139)
            "HVAC / Heater" -> UiText.text(R.string.detail_hvac_heater_140)
            "HVAC / Radiator" -> UiText.text(R.string.detail_hvac_radiator_141)
            "HVAC / Boiler" -> UiText.text(R.string.detail_hvac_boiler_142)
            "HVAC / Heat Pump" -> UiText.text(R.string.detail_hvac_heat_pump_143)
            "HVAC / Infrared Heater" -> UiText.text(R.string.detail_hvac_infrared_heater_144)
            "HVAC / Radiant Panel Heater" -> UiText.text(R.string.detail_hvac_radiant_panel_heater_145)
            "HVAC / Fan Heater" -> UiText.text(R.string.detail_hvac_fan_heater_146)
            "HVAC / Air Curtain" -> UiText.text(R.string.detail_hvac_air_curtain_147)
            "Air Conditioning" -> UiText.text(R.string.detail_air_conditioning_148)
            "Humidifier" -> UiText.text(R.string.detail_humidifier_149)
            "Heating" -> UiText.text(R.string.detail_heating_150)
            "Heating / Radiator" -> UiText.text(R.string.detail_heating_radiator_151)
            "Heating / Boiler" -> UiText.text(R.string.detail_heating_boiler_152)
            "Heating / Heat Pump" -> UiText.text(R.string.detail_heating_heat_pump_153)
            "Heating / Infrared Heater" -> UiText.text(R.string.detail_heating_infrared_heater_154)
            "Heating / Radiant Panel Heater" -> UiText.text(R.string.detail_heating_radiant_panel_heater_155)
            "Heating / Fan Heater" -> UiText.text(R.string.detail_heating_fan_heater_156)
            "Heating / Air Curtain" -> UiText.text(R.string.detail_heating_air_curtain_157)
            "Access Control" -> UiText.text(R.string.detail_access_control_158)
            "Access Control / Access Door" -> UiText.text(R.string.detail_access_control_access_door_159)
            "Access Control / Garage Door" -> UiText.text(R.string.detail_access_control_garage_door_160)
            "Access Control / Emergency Exit Door" -> UiText.text(R.string.detail_access_control_emergency_exit_door_161)
            "Access Control / Access Lock" -> UiText.text(R.string.detail_access_control_access_lock_162)
            "Access Control / Elevator" -> UiText.text(R.string.detail_access_control_elevator_163)
            "Access Control / Window" -> UiText.text(R.string.detail_access_control_window_164)
            "Access Control / Entrance Gate" -> UiText.text(R.string.detail_access_control_entrance_gate_165)
            "Access Control / Door Lock" -> UiText.text(R.string.detail_access_control_door_lock_166)
            "Access Control / Locker" -> UiText.text(R.string.detail_access_control_locker_167)
            "Motorized Device" -> UiText.text(R.string.detail_motorized_device_168)
            "Motorized Device / Motorized Gate" -> UiText.text(R.string.detail_motorized_device_motorized_gate_169)
            "Motorized Device / Awning" -> UiText.text(R.string.detail_motorized_device_awning_170)
            "Motorized Device / Blinds or Shades" -> UiText.text(R.string.detail_motorized_device_blinds_or_shades_171)
            "Motorized Device / Curtains" -> UiText.text(R.string.detail_motorized_device_curtains_172)
            "Motorized Device / Screen" -> UiText.text(R.string.detail_motorized_device_screen_173)
            "Power Device" -> UiText.text(R.string.detail_power_device_174)
            "Power Device / Power Outlet" -> UiText.text(R.string.detail_power_device_power_outlet_175)
            "Power Device / Power Strip" -> UiText.text(R.string.detail_power_device_power_strip_176)
            "Power Device / Plug" -> UiText.text(R.string.detail_power_device_plug_177)
            "Power Device / Power Supply" -> UiText.text(R.string.detail_power_device_power_supply_178)
            "Power Device / LED Driver" -> UiText.text(R.string.detail_power_device_led_driver_179)
            "Power Device / Fluorescent Lamp Gear" -> UiText.text(R.string.detail_power_device_fluorescent_lamp_gear_180)
            "Power Device / HID Lamp Gear" -> UiText.text(R.string.detail_power_device_hid_lamp_gear_181)
            "Power Device / Charge Case" -> UiText.text(R.string.detail_power_device_charge_case_182)
            "Power Device / Power Bank" -> UiText.text(R.string.detail_power_device_power_bank_183)
            "Light Source" -> UiText.text(R.string.detail_light_source_184)
            "Light Source / Incandescent Light Bulb" -> UiText.text(R.string.detail_light_source_incandescent_light_bulb_185)
            "Light Source / LED Lamp" -> UiText.text(R.string.detail_light_source_led_lamp_186)
            "Light Source / HID Lamp" -> UiText.text(R.string.detail_light_source_hid_lamp_187)
            "Light Source / Fluorescent Lamp" -> UiText.text(R.string.detail_light_source_fluorescent_lamp_188)
            "Light Source / LED Array" -> UiText.text(R.string.detail_light_source_led_array_189)
            "Light Source / Multi-Color LED Array" -> UiText.text(R.string.detail_light_source_multi_color_led_array_190)
            "Light Source / Low voltage halogen" -> UiText.text(R.string.detail_light_source_low_voltage_halogen_191)
            "Light Source / Organic light emitting diode (OLED)" -> UiText.text(R.string.detail_light_source_organic_light_emitting_diode_oled_192)
            "Window Covering" -> UiText.text(R.string.detail_window_covering_193)
            "Window Covering / Window Shades" -> UiText.text(R.string.detail_window_covering_window_shades_194)
            "Window Covering / Window Blinds" -> UiText.text(R.string.detail_window_covering_window_blinds_195)
            "Window Covering / Window Awning" -> UiText.text(R.string.detail_window_covering_window_awning_196)
            "Window Covering / Window Curtain" -> UiText.text(R.string.detail_window_covering_window_curtain_197)
            "Window Covering / Exterior Shutter" -> UiText.text(R.string.detail_window_covering_exterior_shutter_198)
            "Window Covering / Exterior Screen" -> UiText.text(R.string.detail_window_covering_exterior_screen_199)
            "Audio Sink" -> UiText.text(R.string.detail_audio_sink_200)
            "Audio Sink / Standalone Speaker" -> UiText.text(R.string.detail_audio_sink_standalone_speaker_201)
            "Audio Sink / Soundbar" -> UiText.text(R.string.detail_audio_sink_soundbar_202)
            "Audio Sink / Bookshelf Speaker" -> UiText.text(R.string.detail_audio_sink_bookshelf_speaker_203)
            "Audio Sink / Standmounted Speaker" -> UiText.text(R.string.detail_audio_sink_standmounted_speaker_204)
            "Audio Sink / Speakerphone" -> UiText.text(R.string.detail_audio_sink_speakerphone_205)
            "Audio Source" -> UiText.text(R.string.detail_audio_source_206)
            "Audio Source / Microphone" -> UiText.text(R.string.detail_audio_source_microphone_207)
            "Audio Source / Alarm" -> UiText.text(R.string.detail_audio_source_alarm_208)
            "Audio Source / Bell" -> UiText.text(R.string.detail_audio_source_bell_209)
            "Audio Source / Horn" -> UiText.text(R.string.detail_audio_source_horn_210)
            "Audio Source / Broadcasting Device" -> UiText.text(R.string.detail_audio_source_broadcasting_device_211)
            "Audio Source / Service Desk" -> UiText.text(R.string.detail_audio_source_service_desk_212)
            "Audio Source / Kiosk" -> UiText.text(R.string.detail_audio_source_kiosk_213)
            "Audio Source / Broadcasting Room" -> UiText.text(R.string.detail_audio_source_broadcasting_room_214)
            "Audio Source / Auditorium" -> UiText.text(R.string.detail_audio_source_auditorium_215)
            "Motorized Vehicle" -> UiText.text(R.string.detail_motorized_vehicle_216)
            "Motorized Vehicle / Car" -> UiText.text(R.string.detail_motorized_vehicle_car_217)
            "Motorized Vehicle / Large Goods Vehicle" -> UiText.text(R.string.detail_motorized_vehicle_large_goods_vehicle_218)
            "Motorized Vehicle / 2-Wheeled Vehicle" -> UiText.text(R.string.detail_motorized_vehicle_2_wheeled_vehicle_219)
            "Motorized Vehicle / Motorbike" -> UiText.text(R.string.detail_motorized_vehicle_motorbike_220)
            "Motorized Vehicle / Scooter" -> UiText.text(R.string.detail_motorized_vehicle_scooter_221)
            "Motorized Vehicle / Moped" -> UiText.text(R.string.detail_motorized_vehicle_moped_222)
            "Motorized Vehicle / 3-Wheeled Vehicle" -> UiText.text(R.string.detail_motorized_vehicle_3_wheeled_vehicle_223)
            "Motorized Vehicle / Light Vehicle" -> UiText.text(R.string.detail_motorized_vehicle_light_vehicle_224)
            "Motorized Vehicle / Quad Bike" -> UiText.text(R.string.detail_motorized_vehicle_quad_bike_225)
            "Motorized Vehicle / Minibus" -> UiText.text(R.string.detail_motorized_vehicle_minibus_226)
            "Motorized Vehicle / Bus" -> UiText.text(R.string.detail_motorized_vehicle_bus_227)
            "Motorized Vehicle / Trolley" -> UiText.text(R.string.detail_motorized_vehicle_trolley_228)
            "Motorized Vehicle / Agricultural Vehicle" -> UiText.text(R.string.detail_motorized_vehicle_agricultural_vehicle_229)
            "Motorized Vehicle / Camper / Caravan" -> UiText.text(R.string.detail_motorized_vehicle_camper_caravan_230)
            "Motorized Vehicle / Recreational Vehicle / Motor Home" -> UiText.text(R.string.detail_motorized_vehicle_recreational_vehicle_motor_home_231)
            "Domestic Appliance" -> UiText.text(R.string.detail_domestic_appliance_232)
            "Domestic Appliance / Refrigerator" -> UiText.text(R.string.detail_domestic_appliance_refrigerator_233)
            "Domestic Appliance / Freezer" -> UiText.text(R.string.detail_domestic_appliance_freezer_234)
            "Domestic Appliance / Oven" -> UiText.text(R.string.detail_domestic_appliance_oven_235)
            "Domestic Appliance / Microwave" -> UiText.text(R.string.detail_domestic_appliance_microwave_236)
            "Domestic Appliance / Toaster" -> UiText.text(R.string.detail_domestic_appliance_toaster_237)
            "Domestic Appliance / Washing Machine" -> UiText.text(R.string.detail_domestic_appliance_washing_machine_238)
            "Domestic Appliance / Dryer" -> UiText.text(R.string.detail_domestic_appliance_dryer_239)
            "Domestic Appliance / Coffee maker" -> UiText.text(R.string.detail_domestic_appliance_coffee_maker_240)
            "Domestic Appliance / Clothes iron" -> UiText.text(R.string.detail_domestic_appliance_clothes_iron_241)
            "Domestic Appliance / Curling iron" -> UiText.text(R.string.detail_domestic_appliance_curling_iron_242)
            "Domestic Appliance / Hair dryer" -> UiText.text(R.string.detail_domestic_appliance_hair_dryer_243)
            "Domestic Appliance / Vacuum cleaner" -> UiText.text(R.string.detail_domestic_appliance_vacuum_cleaner_244)
            "Domestic Appliance / Robotic vacuum cleaner" -> UiText.text(R.string.detail_domestic_appliance_robotic_vacuum_cleaner_245)
            "Domestic Appliance / Rice cooker" -> UiText.text(R.string.detail_domestic_appliance_rice_cooker_246)
            "Domestic Appliance / Clothes steamer" -> UiText.text(R.string.detail_domestic_appliance_clothes_steamer_247)
            "Wearable Audio Device" -> UiText.text(R.string.detail_wearable_audio_device_248)
            "Wearable Audio Device / Earbud" -> UiText.text(R.string.detail_wearable_audio_device_earbud_249)
            "Wearable Audio Device / Headset" -> UiText.text(R.string.detail_wearable_audio_device_headset_250)
            "Wearable Audio Device / Headphones" -> UiText.text(R.string.detail_wearable_audio_device_headphones_251)
            "Wearable Audio Device / Neck Band" -> UiText.text(R.string.detail_wearable_audio_device_neck_band_252)
            "Wearable Audio Device / Left Earbud" -> UiText.text(R.string.detail_wearable_audio_device_left_earbud_253)
            "Wearable Audio Device / Right Earbud" -> UiText.text(R.string.detail_wearable_audio_device_right_earbud_254)
            "Aircraft" -> UiText.text(R.string.detail_aircraft_255)
            "Aircraft / Light Aircraft" -> UiText.text(R.string.detail_aircraft_light_aircraft_256)
            "Aircraft / Microlight" -> UiText.text(R.string.detail_aircraft_microlight_257)
            "Aircraft / Paraglider" -> UiText.text(R.string.detail_aircraft_paraglider_258)
            "Aircraft / Large Passenger Aircraft" -> UiText.text(R.string.detail_aircraft_large_passenger_aircraft_259)
            "AV Equipment" -> UiText.text(R.string.detail_av_equipment_260)
            "AV Equipment / Amplifier" -> UiText.text(R.string.detail_av_equipment_amplifier_261)
            "AV Equipment / Receiver" -> UiText.text(R.string.detail_av_equipment_receiver_262)
            "AV Equipment / Radio" -> UiText.text(R.string.detail_av_equipment_radio_263)
            "AV Equipment / Tuner" -> UiText.text(R.string.detail_av_equipment_tuner_264)
            "AV Equipment / Turntable" -> UiText.text(R.string.detail_av_equipment_turntable_265)
            "AV Equipment / CD Player" -> UiText.text(R.string.detail_av_equipment_cd_player_266)
            "AV Equipment / DVD Player" -> UiText.text(R.string.detail_av_equipment_dvd_player_267)
            "AV Equipment / Bluray Player" -> UiText.text(R.string.detail_av_equipment_bluray_player_268)
            "AV Equipment / Optical Disc Player" -> UiText.text(R.string.detail_av_equipment_optical_disc_player_269)
            "AV Equipment / Set-Top Box" -> UiText.text(R.string.detail_av_equipment_set_top_box_270)
            "Display Equipment" -> UiText.text(R.string.detail_display_equipment_271)
            "Display Equipment / Television" -> UiText.text(R.string.detail_display_equipment_television_272)
            "Display Equipment / Monitor" -> UiText.text(R.string.detail_display_equipment_monitor_273)
            "Display Equipment / Projector" -> UiText.text(R.string.detail_display_equipment_projector_274)
            "Hearing aid" -> UiText.text(R.string.detail_hearing_aid_275)
            "Hearing aid / In-ear hearing aid" -> UiText.text(R.string.detail_hearing_aid_in_ear_hearing_aid_276)
            "Hearing aid / Behind-ear hearing aid" -> UiText.text(R.string.detail_hearing_aid_behind_ear_hearing_aid_277)
            "Hearing aid / Cochlear Implant" -> UiText.text(R.string.detail_hearing_aid_cochlear_implant_278)
            "Gaming" -> UiText.text(R.string.detail_gaming_279)
            "Gaming / Home Video Game Console" -> UiText.text(R.string.detail_gaming_home_video_game_console_280)
            "Gaming / Portable handheld console" -> UiText.text(R.string.detail_gaming_portable_handheld_console_281)
            "Signage" -> UiText.text(R.string.detail_signage_282)
            "Signage / Digital Signage" -> UiText.text(R.string.detail_signage_digital_signage_283)
            "Signage / Electronic Label" -> UiText.text(R.string.detail_signage_electronic_label_284)
            "Pulse Oximeter" -> UiText.text(R.string.detail_pulse_oximeter_285)
            "Pulse Oximeter / Fingertip Pulse Oximeter" -> UiText.text(R.string.detail_pulse_oximeter_fingertip_pulse_oximeter_286)
            "Pulse Oximeter / Wrist Worn Pulse Oximeter" -> UiText.text(R.string.detail_pulse_oximeter_wrist_worn_pulse_oximeter_287)
            "Weight Scale" -> UiText.text(R.string.detail_weight_scale_288)
            "Personal Mobility Device" -> UiText.text(R.string.detail_personal_mobility_device_289)
            "Personal Mobility Device / Powered Wheelchair" -> UiText.text(R.string.detail_personal_mobility_device_powered_wheelchair_290)
            "Personal Mobility Device / Mobility Scooter" -> UiText.text(R.string.detail_personal_mobility_device_mobility_scooter_291)
            "Continuous Glucose Monitor" -> UiText.text(R.string.detail_continuous_glucose_monitor_292)
            "Insulin Pump" -> UiText.text(R.string.detail_insulin_pump_293)
            "Insulin Pump / Insulin Pump, durable pump" -> UiText.text(R.string.detail_insulin_pump_insulin_pump_durable_pump_294)
            "Insulin Pump / Insulin Pump, patch pump" -> UiText.text(R.string.detail_insulin_pump_insulin_pump_patch_pump_295)
            "Insulin Pump / Insulin Pen" -> UiText.text(R.string.detail_insulin_pump_insulin_pen_296)
            "Medication Delivery" -> UiText.text(R.string.detail_medication_delivery_297)
            "Spirometer" -> UiText.text(R.string.detail_spirometer_298)
            "Spirometer / Handheld Spirometer" -> UiText.text(R.string.detail_spirometer_handheld_spirometer_299)
            "Outdoor Sports Activity" -> UiText.text(R.string.detail_outdoor_sports_activity_300)
            "Outdoor Sports Activity / Location Display" -> UiText.text(R.string.detail_outdoor_sports_activity_location_display_301)
            "Outdoor Sports Activity / Location and Navigation Display" -> UiText.text(R.string.detail_outdoor_sports_activity_location_and_navigation_display_302)
            "Outdoor Sports Activity / Location Pod" -> UiText.text(R.string.detail_outdoor_sports_activity_location_pod_303)
            "Outdoor Sports Activity / Location and Navigation Pod" -> UiText.text(R.string.detail_outdoor_sports_activity_location_and_navigation_pod_304)
            "Industrial Measurement Device" -> UiText.text(R.string.detail_industrial_measurement_device_305)
            "Industrial Measurement Device / Torque Testing Device" -> UiText.text(R.string.detail_industrial_measurement_device_torque_testing_device_306)
            "Industrial Measurement Device / Caliper" -> UiText.text(R.string.detail_industrial_measurement_device_caliper_307)
            "Industrial Measurement Device / Dial Indicator" -> UiText.text(R.string.detail_industrial_measurement_device_dial_indicator_308)
            "Industrial Measurement Device / Micrometer" -> UiText.text(R.string.detail_industrial_measurement_device_micrometer_309)
            "Industrial Measurement Device / Height Gauge" -> UiText.text(R.string.detail_industrial_measurement_device_height_gauge_310)
            "Industrial Measurement Device / Force Gauge" -> UiText.text(R.string.detail_industrial_measurement_device_force_gauge_311)
            "Industrial Tools" -> UiText.text(R.string.detail_industrial_tools_312)
            "Industrial Tools / Machine Tool Holder" -> UiText.text(R.string.detail_industrial_tools_machine_tool_holder_313)
            "Industrial Tools / Generic Clamping Device" -> UiText.text(R.string.detail_industrial_tools_generic_clamping_device_314)
            "Industrial Tools / Clamping Jaws/Jaw Chuck" -> UiText.text(R.string.detail_industrial_tools_clamping_jaws_jaw_chuck_315)
            "Industrial Tools / Clamping (Collet) Chuck" -> UiText.text(R.string.detail_industrial_tools_clamping_collet_chuck_316)
            "Industrial Tools / Clamping Mandrel" -> UiText.text(R.string.detail_industrial_tools_clamping_mandrel_317)
            "Industrial Tools / Vise" -> UiText.text(R.string.detail_industrial_tools_vise_318)
            "Industrial Tools / Zero-Point Clamping System" -> UiText.text(R.string.detail_industrial_tools_zero_point_clamping_system_319)
            "Industrial Tools / Torque Wrench" -> UiText.text(R.string.detail_industrial_tools_torque_wrench_320)
            "Industrial Tools / Torque Screwdriver" -> UiText.text(R.string.detail_industrial_tools_torque_screwdriver_321)
            "Cookware Device" -> UiText.text(R.string.detail_cookware_device_322)
            "Cookware Device / Pot and Jugs" -> UiText.text(R.string.detail_cookware_device_pot_and_jugs_323)
            "Cookware Device / Pressure Cooker" -> UiText.text(R.string.detail_cookware_device_pressure_cooker_324)
            "Cookware Device / Slow Cooker" -> UiText.text(R.string.detail_cookware_device_slow_cooker_325)
            "Cookware Device / Steam Cooker" -> UiText.text(R.string.detail_cookware_device_steam_cooker_326)
            "Cookware Device / Saucepan" -> UiText.text(R.string.detail_cookware_device_saucepan_327)
            "Cookware Device / Frying Pan" -> UiText.text(R.string.detail_cookware_device_frying_pan_328)
            "Cookware Device / Casserole" -> UiText.text(R.string.detail_cookware_device_casserole_329)
            "Cookware Device / Dutch Oven" -> UiText.text(R.string.detail_cookware_device_dutch_oven_330)
            "Cookware Device / Grill Pan/Raclette Grill/Griddle Pan" -> UiText.text(R.string.detail_cookware_device_grill_pan_raclette_grill_griddle_pan_331)
            "Cookware Device / Braising Pan" -> UiText.text(R.string.detail_cookware_device_braising_pan_332)
            "Cookware Device / Wok Pan" -> UiText.text(R.string.detail_cookware_device_wok_pan_333)
            "Cookware Device / Paella Pan" -> UiText.text(R.string.detail_cookware_device_paella_pan_334)
            "Cookware Device / Crepe Pan" -> UiText.text(R.string.detail_cookware_device_crepe_pan_335)
            "Cookware Device / Tagine" -> UiText.text(R.string.detail_cookware_device_tagine_336)
            "Cookware Device / Fondue" -> UiText.text(R.string.detail_cookware_device_fondue_337)
            "Cookware Device / Lid" -> UiText.text(R.string.detail_cookware_device_lid_338)
            "Cookware Device / Wired Probe" -> UiText.text(R.string.detail_cookware_device_wired_probe_339)
            "Cookware Device / Wireless Probe" -> UiText.text(R.string.detail_cookware_device_wireless_probe_340)
            "Cookware Device / Baking Molds" -> UiText.text(R.string.detail_cookware_device_baking_molds_341)
            "Cookware Device / Baking Tray" -> UiText.text(R.string.detail_cookware_device_baking_tray_342)
            "GAP" -> UiText.text(R.string.detail_gap_343)
            "GATT" -> UiText.text(R.string.detail_gatt_344)
            "Immediate Alert" -> UiText.text(R.string.detail_immediate_alert_345)
            "Link Loss" -> UiText.text(R.string.detail_link_loss_346)
            "Tx Power" -> UiText.text(R.string.detail_tx_power_347)
            "Current Time" -> UiText.text(R.string.detail_current_time_348)
            "Reference Time Update" -> UiText.text(R.string.detail_reference_time_update_349)
            "Next DST Change" -> UiText.text(R.string.detail_next_dst_change_350)
            "Glucose" -> UiText.text(R.string.detail_glucose_351)
            "Health Thermometer" -> UiText.text(R.string.detail_health_thermometer_352)
            "Device Information" -> UiText.text(R.string.detail_device_information_353)
            "Heart Rate" -> UiText.text(R.string.detail_heart_rate_354)
            "Phone Alert Status" -> UiText.text(R.string.detail_phone_alert_status_355)
            "Battery" -> UiText.text(R.string.detail_battery_356)
            "Alert Notification" -> UiText.text(R.string.detail_alert_notification_357)
            "Scan Parameters" -> UiText.text(R.string.detail_scan_parameters_358)
            "Running Speed and Cadence" -> UiText.text(R.string.detail_running_speed_and_cadence_359)
            "Automation IO" -> UiText.text(R.string.detail_automation_io_360)
            "Cycling Speed and Cadence" -> UiText.text(R.string.detail_cycling_speed_and_cadence_361)
            "Cycling Power" -> UiText.text(R.string.detail_cycling_power_362)
            "Location and Navigation" -> UiText.text(R.string.detail_location_and_navigation_363)
            "Environmental Sensing" -> UiText.text(R.string.detail_environmental_sensing_364)
            "Body Composition" -> UiText.text(R.string.detail_body_composition_365)
            "User Data" -> UiText.text(R.string.detail_user_data_366)
            "Bond Management" -> UiText.text(R.string.detail_bond_management_367)
            "Continuous Glucose Monitoring" -> UiText.text(R.string.detail_continuous_glucose_monitoring_368)
            "Internet Protocol Support" -> UiText.text(R.string.detail_internet_protocol_support_369)
            "Indoor Positioning" -> UiText.text(R.string.detail_indoor_positioning_370)
            "HTTP Proxy" -> UiText.text(R.string.detail_http_proxy_371)
            "Transport Discovery" -> UiText.text(R.string.detail_transport_discovery_372)
            "Object Transfer" -> UiText.text(R.string.detail_object_transfer_373)
            "Fitness Machine" -> UiText.text(R.string.detail_fitness_machine_374)
            "Mesh Provisioning" -> UiText.text(R.string.detail_mesh_provisioning_375)
            "Mesh Proxy" -> UiText.text(R.string.detail_mesh_proxy_376)
            "Reconnection Configuration" -> UiText.text(R.string.detail_reconnection_configuration_377)
            "Insulin Delivery" -> UiText.text(R.string.detail_insulin_delivery_378)
            "Binary Sensor" -> UiText.text(R.string.detail_binary_sensor_379)
            "Emergency Configuration" -> UiText.text(R.string.detail_emergency_configuration_380)
            "Authorization Control" -> UiText.text(R.string.detail_authorization_control_381)
            "Physical Activity Monitor" -> UiText.text(R.string.detail_physical_activity_monitor_382)
            "Elapsed Time" -> UiText.text(R.string.detail_elapsed_time_383)
            "Generic Health Sensor" -> UiText.text(R.string.detail_generic_health_sensor_384)
            "Audio Input Control" -> UiText.text(R.string.detail_audio_input_control_385)
            "Volume Control" -> UiText.text(R.string.detail_volume_control_386)
            "Volume Offset Control" -> UiText.text(R.string.detail_volume_offset_control_387)
            "Coordinated Set Identification" -> UiText.text(R.string.detail_coordinated_set_identification_388)
            "Device Time" -> UiText.text(R.string.detail_device_time_389)
            "Media Control" -> UiText.text(R.string.detail_media_control_390)
            "Generic Media Control" -> UiText.text(R.string.detail_generic_media_control_391)
            "Constant Tone Extension" -> UiText.text(R.string.detail_constant_tone_extension_392)
            "Telephone Bearer" -> UiText.text(R.string.detail_telephone_bearer_393)
            "Generic Telephone Bearer" -> UiText.text(R.string.detail_generic_telephone_bearer_394)
            "Microphone Control" -> UiText.text(R.string.detail_microphone_control_395)
            "Audio Stream Control" -> UiText.text(R.string.detail_audio_stream_control_396)
            "Broadcast Audio Scan" -> UiText.text(R.string.detail_broadcast_audio_scan_397)
            "Published Audio Capabilities" -> UiText.text(R.string.detail_published_audio_capabilities_398)
            "Basic Audio Announcement" -> UiText.text(R.string.detail_basic_audio_announcement_399)
            "Broadcast Audio Announcement" -> UiText.text(R.string.detail_broadcast_audio_announcement_400)
            "Common Audio" -> UiText.text(R.string.detail_common_audio_401)
            "Hearing Access" -> UiText.text(R.string.detail_hearing_access_402)
            "Telephony and Media Audio" -> UiText.text(R.string.detail_telephony_and_media_audio_403)
            "Public Broadcast Announcement" -> UiText.text(R.string.detail_public_broadcast_announcement_404)
            "Electronic Shelf Label" -> UiText.text(R.string.detail_electronic_shelf_label_405)
            "Gaming Audio" -> UiText.text(R.string.detail_gaming_audio_406)
            "Mesh Proxy Solicitation" -> UiText.text(R.string.detail_mesh_proxy_solicitation_407)
            "Ranging" -> UiText.text(R.string.detail_ranging_408)
            "HID ISO" -> UiText.text(R.string.detail_hid_iso_409)
            "Cookware" -> UiText.text(R.string.detail_cookware_410)
            "Voice Assistant" -> UiText.text(R.string.detail_voice_assistant_411)
            "Generic Voice Assistant" -> UiText.text(R.string.detail_generic_voice_assistant_412)
            "Tire Pressure Monitoring System" -> UiText.text(R.string.detail_tire_pressure_monitoring_system_413)
            "Miscellaneous" -> UiText.text(R.string.detail_miscellaneous_414)
            "LAN / Network AP" -> UiText.text(R.string.detail_lan_network_ap_415)
            "Audio / Video" -> UiText.text(R.string.detail_audio_video_416)
            "Peripheral" -> UiText.text(R.string.detail_peripheral_417)
            "Imaging" -> UiText.text(R.string.detail_imaging_418)
            "Wearable" -> UiText.text(R.string.detail_wearable_419)
            "Toy" -> UiText.text(R.string.detail_toy_420)
            "Health" -> UiText.text(R.string.detail_health_421)
            "Uncategorized" -> UiText.text(R.string.detail_uncategorized_422)
            "Major 0x%02X" -> UiText.text(R.string.detail_major_0x_02x_423)
            "Desktop" -> UiText.text(R.string.detail_desktop_424)
            "Server" -> UiText.text(R.string.detail_server_425)
            "Laptop" -> UiText.text(R.string.detail_laptop_426)
            "Handheld PC/PDA" -> UiText.text(R.string.detail_handheld_pc_pda_427)
            "Palm-size PDA" -> UiText.text(R.string.detail_palm_size_pda_428)
            "Wearable computer" -> UiText.text(R.string.detail_wearable_computer_429)
            "Tablet" -> UiText.text(R.string.detail_tablet_430)
            "Computer 0x%02X" -> UiText.text(R.string.detail_computer_0x_02x_431)
            "Cellular" -> UiText.text(R.string.detail_cellular_432)
            "Cordless" -> UiText.text(R.string.detail_cordless_433)
            "Smartphone" -> UiText.text(R.string.detail_smartphone_434)
            "Wired modem / voice gateway" -> UiText.text(R.string.detail_wired_modem_voice_gateway_435)
            "Common ISDN access" -> UiText.text(R.string.detail_common_isdn_access_436)
            "Phone 0x%02X" -> UiText.text(R.string.detail_phone_0x_02x_437)
            "Fully available" -> UiText.text(R.string.detail_fully_available_438)
            "1–17% utilized" -> UiText.text(R.string.detail_1_17_utilized_439)
            "17–33% utilized" -> UiText.text(R.string.detail_17_33_utilized_440)
            "33–50% utilized" -> UiText.text(R.string.detail_33_50_utilized_441)
            "50–67% utilized" -> UiText.text(R.string.detail_50_67_utilized_442)
            "67–83% utilized" -> UiText.text(R.string.detail_67_83_utilized_443)
            "83–99% utilized" -> UiText.text(R.string.detail_83_99_utilized_444)
            "No service available" -> UiText.text(R.string.detail_no_service_available_445)
            "Wearable headset" -> UiText.text(R.string.detail_wearable_headset_446)
            "Hands-free" -> UiText.text(R.string.detail_hands_free_447)
            "Microphone" -> UiText.text(R.string.detail_microphone_448)
            "Loudspeaker" -> UiText.text(R.string.detail_loudspeaker_449)
            "Headphones" -> UiText.text(R.string.detail_headphones_450)
            "Portable audio" -> UiText.text(R.string.detail_portable_audio_451)
            "Car audio" -> UiText.text(R.string.detail_car_audio_452)
            "Set-top box" -> UiText.text(R.string.detail_set_top_box_453)
            "HiFi audio" -> UiText.text(R.string.detail_hifi_audio_454)
            "VCR" -> UiText.text(R.string.detail_vcr_455)
            "Video camera" -> UiText.text(R.string.detail_video_camera_456)
            "Camcorder" -> UiText.text(R.string.detail_camcorder_457)
            "Video monitor" -> UiText.text(R.string.detail_video_monitor_458)
            "Video display and loudspeaker" -> UiText.text(R.string.detail_video_display_and_loudspeaker_459)
            "Video conferencing" -> UiText.text(R.string.detail_video_conferencing_460)
            "Gaming / toy" -> UiText.text(R.string.detail_gaming_toy_461)
            "A/V 0x%02X" -> UiText.text(R.string.detail_a_v_0x_02x_462)
            "Joystick" -> UiText.text(R.string.detail_joystick_463)
            "Gamepad" -> UiText.text(R.string.detail_gamepad_464)
            "Remote control" -> UiText.text(R.string.detail_remote_control_465)
            "Sensing device" -> UiText.text(R.string.detail_sensing_device_466)
            "Digitizer tablet" -> UiText.text(R.string.detail_digitizer_tablet_467)
            "Card reader" -> UiText.text(R.string.detail_card_reader_468)
            "Digital pen" -> UiText.text(R.string.detail_digital_pen_469)
            "Handheld scanner" -> UiText.text(R.string.detail_handheld_scanner_470)
            "Handheld gestural input" -> UiText.text(R.string.detail_handheld_gestural_input_471)
            "Peripheral 0x%X" -> UiText.text(R.string.detail_peripheral_0x_x_472)
            "keyboard" -> UiText.text(R.string.detail_keyboard_473)
            "pointing" -> UiText.text(R.string.detail_pointing_474)
            "keyboard/pointing" -> UiText.text(R.string.detail_keyboard_pointing_475)
            "Camera" -> UiText.text(R.string.detail_camera_476)
            "Scanner" -> UiText.text(R.string.detail_scanner_477)
            "Printer" -> UiText.text(R.string.detail_printer_478)
            "Wristwatch" -> UiText.text(R.string.detail_wristwatch_479)
            "Pager" -> UiText.text(R.string.detail_pager_480)
            "Jacket" -> UiText.text(R.string.detail_jacket_481)
            "Helmet" -> UiText.text(R.string.detail_helmet_482)
            "Glasses" -> UiText.text(R.string.detail_glasses_483)
            "Wearable 0x%02X" -> UiText.text(R.string.detail_wearable_0x_02x_484)
            "Robot" -> UiText.text(R.string.detail_robot_485)
            "Vehicle" -> UiText.text(R.string.detail_vehicle_486)
            "Doll / action figure" -> UiText.text(R.string.detail_doll_action_figure_487)
            "Controller" -> UiText.text(R.string.detail_controller_488)
            "Game" -> UiText.text(R.string.detail_game_489)
            "Toy 0x%02X" -> UiText.text(R.string.detail_toy_0x_02x_490)
            "Blood pressure monitor" -> UiText.text(R.string.detail_blood_pressure_monitor_491)
            "Weighing scale" -> UiText.text(R.string.detail_weighing_scale_492)
            "Glucose meter" -> UiText.text(R.string.detail_glucose_meter_493)
            "Pulse oximeter" -> UiText.text(R.string.detail_pulse_oximeter_494)
            "Heart / pulse rate monitor" -> UiText.text(R.string.detail_heart_pulse_rate_monitor_495)
            "Health data display" -> UiText.text(R.string.detail_health_data_display_496)
            "Step counter" -> UiText.text(R.string.detail_step_counter_497)
            "Body composition analyzer" -> UiText.text(R.string.detail_body_composition_analyzer_498)
            "Peak flow monitor" -> UiText.text(R.string.detail_peak_flow_monitor_499)
            "Medication monitor" -> UiText.text(R.string.detail_medication_monitor_500)
            "Knee prosthesis" -> UiText.text(R.string.detail_knee_prosthesis_501)
            "Ankle prosthesis" -> UiText.text(R.string.detail_ankle_prosthesis_502)
            "Generic health manager" -> UiText.text(R.string.detail_generic_health_manager_503)
            "Personal mobility device" -> UiText.text(R.string.detail_personal_mobility_device_504)
            "Health 0x%02X" -> UiText.text(R.string.detail_health_0x_02x_505)
            "Limited Discoverable" -> UiText.text(R.string.detail_limited_discoverable_506)
            "Positioning" -> UiText.text(R.string.detail_positioning_507)
            "Networking" -> UiText.text(R.string.detail_networking_508)
            "Rendering" -> UiText.text(R.string.detail_rendering_509)
            "Capturing" -> UiText.text(R.string.detail_capturing_510)
            "Audio" -> UiText.text(R.string.detail_audio_511)
            "Telephony" -> UiText.text(R.string.detail_telephony_512)
            "Information" -> UiText.text(R.string.detail_information_513)
            "Not available" -> UiText.text(R.string.detail_not_available_514)
            "%1\$s to %2\$s dBm" -> UiText.text(R.string.detail_1_s_to_2_s_dbm_515)
            "format %1\$s" -> UiText.text(R.string.detail_format_1_s_516)
            "Already tagged" -> UiText.text(R.string.detail_already_tagged_517)
            "This radio only" -> UiText.text(R.string.detail_this_radio_only_518)
            "Strong family" -> UiText.text(R.string.detail_strong_family_519)
            "Possible family" -> UiText.text(R.string.detail_possible_family_520)
            "a catalog signature" -> UiText.text(R.string.detail_a_catalog_signature_521)
            "Matched %1\$s. A second signature can still dual-label this radio (store UUID, product OUI)." -> UiText.text(R.string.detail_matched_1_s_a_second_signature_can_still_dual_label_this_radio_store_uuid_p_522)
            "No unique on-air ID to cluster on. Randomized addresses, house-like names, and generic chips are skipped." -> UiText.text(R.string.detail_no_unique_on_air_id_to_cluster_on_randomized_addresses_house_like_names_and_523)
            "No other MAC in the log or on the air shares this %1\$s. A signature from here will mostly tag this address." -> UiText.text(R.string.detail_no_other_mac_in_the_log_or_on_the_air_shares_this_1_s_a_signature_from_here_524)
            "Same %1\$s on %2\$s. That is a catalog pattern, not this MAC." -> UiText.text(R.string.detail_same_1_s_on_2_s_that_is_a_catalog_pattern_not_this_mac_525)
            "Same %1\$s on %2\$s. Thin sample — a possible catalog family." -> UiText.text(R.string.detail_same_1_s_on_2_s_thin_sample_a_possible_catalog_family_526)
            "name glob" -> UiText.text(R.string.detail_name_glob_527)
            "vendor IE" -> UiText.text(R.string.detail_vendor_ie_528)
            "service UUID" -> UiText.text(R.string.detail_service_uuid_529)
            "manufacturer data prefix" -> UiText.text(R.string.detail_manufacturer_data_prefix_530)
            "on-air ID" -> UiText.text(R.string.detail_on_air_id_531)
            "AP" -> UiText.text(R.string.detail_ap_532)
            "APs" -> UiText.text(R.string.detail_aps_533)
            "advertiser" -> UiText.text(R.string.detail_advertiser_534)
            "advertisers" -> UiText.text(R.string.detail_advertisers_535)
            "%1\$s %2\$s in the log (%3\$s on the air now)" -> UiText.text(R.string.detail_1_s_2_s_in_the_log_3_s_on_the_air_now_536)
            "%1\$s %2\$s in the log" -> UiText.text(R.string.detail_1_s_2_s_in_the_log_537)
            "%1\$s %2\$s on the air now" -> UiText.text(R.string.detail_1_s_2_s_on_the_air_now_538)
            "%1\$s %2\$s" -> UiText.text(R.string.detail_1_s_2_s_539)
            "vendor IE %1\$s" -> UiText.text(R.string.detail_vendor_ie_1_s_540)
            "svc contains %1\$s" -> UiText.text(R.string.detail_svc_contains_1_s_541)
            "mfg 0x%04X %s" -> UiText.text(R.string.detail_mfg_0x_04x_s_542)
            "mfg 0x%04X" -> UiText.text(R.string.detail_mfg_0x_04x_543)
            "Joystick + keyboard" -> UiText.text(R.string.detail_joystick_keyboard_544)
            "Joystick + pointing" -> UiText.text(R.string.detail_joystick_pointing_545)
            "Joystick + keyboard/pointing" -> UiText.text(R.string.detail_joystick_keyboard_pointing_546)
            "Gamepad + keyboard" -> UiText.text(R.string.detail_gamepad_keyboard_547)
            "Gamepad + pointing" -> UiText.text(R.string.detail_gamepad_pointing_548)
            "Gamepad + keyboard/pointing" -> UiText.text(R.string.detail_gamepad_keyboard_pointing_549)
            "Remote control + keyboard" -> UiText.text(R.string.detail_remote_control_keyboard_550)
            "Remote control + pointing" -> UiText.text(R.string.detail_remote_control_pointing_551)
            "Remote control + keyboard/pointing" -> UiText.text(R.string.detail_remote_control_keyboard_pointing_552)
            "Sensing device + keyboard" -> UiText.text(R.string.detail_sensing_device_keyboard_553)
            "Sensing device + pointing" -> UiText.text(R.string.detail_sensing_device_pointing_554)
            "Sensing device + keyboard/pointing" -> UiText.text(R.string.detail_sensing_device_keyboard_pointing_555)
            "Digitizer tablet + keyboard" -> UiText.text(R.string.detail_digitizer_tablet_keyboard_556)
            "Digitizer tablet + pointing" -> UiText.text(R.string.detail_digitizer_tablet_pointing_557)
            "Digitizer tablet + keyboard/pointing" -> UiText.text(R.string.detail_digitizer_tablet_keyboard_pointing_558)
            "Card reader + keyboard" -> UiText.text(R.string.detail_card_reader_keyboard_559)
            "Card reader + pointing" -> UiText.text(R.string.detail_card_reader_pointing_560)
            "Card reader + keyboard/pointing" -> UiText.text(R.string.detail_card_reader_keyboard_pointing_561)
            "Digital pen + keyboard" -> UiText.text(R.string.detail_digital_pen_keyboard_562)
            "Digital pen + pointing" -> UiText.text(R.string.detail_digital_pen_pointing_563)
            "Digital pen + keyboard/pointing" -> UiText.text(R.string.detail_digital_pen_keyboard_pointing_564)
            "Handheld scanner + keyboard" -> UiText.text(R.string.detail_handheld_scanner_keyboard_565)
            "Handheld scanner + pointing" -> UiText.text(R.string.detail_handheld_scanner_pointing_566)
            "Handheld scanner + keyboard/pointing" -> UiText.text(R.string.detail_handheld_scanner_keyboard_pointing_567)
            "Handheld gestural input + keyboard" -> UiText.text(R.string.detail_handheld_gestural_input_keyboard_568)
            "Handheld gestural input + pointing" -> UiText.text(R.string.detail_handheld_gestural_input_pointing_569)
            "Handheld gestural input + keyboard/pointing" -> UiText.text(R.string.detail_handheld_gestural_input_keyboard_pointing_570)
            "Display + Camera" -> UiText.text(R.string.detail_display_camera_571)
            "Display + Scanner" -> UiText.text(R.string.detail_display_scanner_572)
            "Display + Printer" -> UiText.text(R.string.detail_display_printer_573)
            "Camera + Scanner" -> UiText.text(R.string.detail_camera_scanner_574)
            "Camera + Printer" -> UiText.text(R.string.detail_camera_printer_575)
            "Scanner + Printer" -> UiText.text(R.string.detail_scanner_printer_576)
            "Display + Camera + Scanner" -> UiText.text(R.string.detail_display_camera_scanner_577)
            "Display + Camera + Printer" -> UiText.text(R.string.detail_display_camera_printer_578)
            "Display + Scanner + Printer" -> UiText.text(R.string.detail_display_scanner_printer_579)
            "Camera + Scanner + Printer" -> UiText.text(R.string.detail_camera_scanner_printer_580)
            "Display + Camera + Scanner + Printer" -> UiText.text(R.string.detail_display_camera_scanner_printer_581)
            else -> source
        }
    }
}
