package app.fieldwatch

/** Fixed discovery labels only; advertised identity strings remain unchanged. */
internal object UiDiscoveryText {
    fun text(source: String): String = when (source) {
        "Wi-Fi access point (brand unconfirmed)" -> UiText.text(R.string.identity_v92_0)
        "Chipset platform: %1\$s" -> UiText.text(R.string.identity_v92_1)
        "Payload decode status" -> UiText.text(R.string.identity_v92_2)
        "No advertisement payload captured" -> UiText.text(R.string.identity_v92_3)
        "Payload parser unsupported" -> UiText.text(R.string.identity_v92_4)
        "No catalog signature matched; parsed identity fields may still be available." -> UiText.text(R.string.identity_v92_5)
        "temperature / humidity sensor" -> UiText.text(R.string.identity_v92_6)
        "body composition scale" -> UiText.text(R.string.identity_v92_7)
        "water leak sensor" -> UiText.text(R.string.identity_v92_8)
        "door lock" -> UiText.text(R.string.identity_v92_9)
        "MiBeacon product ID %1\$s identifies %2\$s; encrypted objects do not expose readings." -> UiText.text(R.string.identity_v92_10)
        "MiBeacon light raw value" -> UiText.text(R.string.identity_v92_11)
        "MiBeacon on/off raw state" -> UiText.text(R.string.identity_v92_12)
        "MiBeacon light raw state" -> UiText.text(R.string.identity_v92_13)
        "MiBeacon water detected" -> UiText.text(R.string.identity_v92_14)
        "MiBeacon smoke detected" -> UiText.text(R.string.identity_v92_15)
        "MiBeacon door/window state" -> UiText.text(R.string.identity_v92_16)
        "Open" -> UiText.text(R.string.identity_v92_17)
        "Closed" -> UiText.text(R.string.identity_v92_18)
        "Fiberhome Wi-Fi" -> UiText.text(R.string.identity_v92_19)
        "WPS manufacturer identifies Fiberhome. A repeated manufacturer/model field does not establish an exact retail model." -> UiText.text(R.string.identity_v92_20)
        "WPS primary device type identifies an access point. A chipset manufacturer such as Realtek does not establish the finished product brand." -> UiText.text(R.string.identity_v92_21)
        "LYWSD02MMC thermometer" -> UiText.text(R.string.identity_v92_22)
        "CGD1 thermometer" -> UiText.text(R.string.identity_v92_23)
        "SJWS01LM water leak sensor" -> UiText.text(R.string.identity_v92_24)
        "Mi ecosystem door lock" -> UiText.text(R.string.identity_v92_25)

        "a Qi'an / Qingju radio of unknown device type" -> UiText.text(R.string.discovery_v91_qian)
        "The advertised name and public registered prefix identify the operator family; lock versus parking infrastructure is unverified." -> UiText.text(R.string.discovery_v91_qian_reason)
        "a bicycle parking-area beacon" -> UiText.text(R.string.discovery_v91_parking_fence)
        "a NIU vehicle radio" -> UiText.text(R.string.discovery_v91_niu_link)
        "a CFMOTO vehicle radio or instrument" -> UiText.text(R.string.discovery_v91_cfmoto)
        "an InGeek vehicle digital-key radio" -> UiText.text(R.string.discovery_v91_ingeek_key)
        "a ZEEKR vehicle radio" -> UiText.text(R.string.discovery_v91_zeekr_vehicle)
        "a possible RoadBit e-bike radio" -> UiText.text(R.string.discovery_v91_roadbit)
        "a Narwal robot vacuum" -> UiText.text(R.string.discovery_v91_narwal)
        "a COLMO home appliance" -> UiText.text(R.string.discovery_v91_colmo)
        "a PETKIT pet appliance" -> UiText.text(R.string.discovery_v91_petkit)
        "an Honor fitness band" -> UiText.text(R.string.discovery_v91_honor_band)
        "an OPPO smartwatch" -> UiText.text(R.string.discovery_v91_oppo_watch)
        "a Xiaomi ecosystem temperature/humidity monitor" -> UiText.text(R.string.discovery_v91_mi_thermometer)
        "a Mijia S400 body-composition scale" -> UiText.text(R.string.discovery_v91_mijia_s400)
        "a Mi ecosystem smart switch" -> UiText.text(R.string.discovery_v91_mi_switch)
        "a Mi ecosystem smart light" -> UiText.text(R.string.discovery_v91_mi_light)
        "a Cariot phone holder" -> UiText.text(R.string.discovery_v91_cariot_holder)
        "a Haier appliance radio" -> UiText.text(R.string.discovery_v91_haier_radio)
        "a ZTE Wi-Fi gateway, access point or hotspot" -> UiText.text(R.string.discovery_v91_zte_wifi)
        "a Phicomm Wi-Fi access point or router" -> UiText.text(R.string.discovery_v91_phicomm_wifi)
        "a 360 Wi-Fi router or hotspot" -> UiText.text(R.string.discovery_v91_qihoo_wifi)

        "A MERCURY name identifies a network family; it does not identify an exact model." -> UiText.text(R.string.discovery_v90_mercury_reason)
        "a Mercury Wi-Fi access point" -> UiText.text(R.string.discovery_v90_mercury)
        "Mobike uses a dedicated BLE lock service and company identifier." -> UiText.text(R.string.discovery_v90_mobike_reason)
        "a Mobike bicycle lock" -> UiText.text(R.string.discovery_v90_mobike)
        "The ROMO name identifies a robot vacuum family, not a flying aircraft." -> UiText.text(R.string.discovery_v90_romo_reason)
        "a DJI ROMO robot vacuum" -> UiText.text(R.string.discovery_v90_romo)
        "WPS manufacturer" -> UiText.text(R.string.discovery_wps_manufacturer)
        "WPS model" -> UiText.text(R.string.discovery_wps_model)
        "WPS model number" -> UiText.text(R.string.discovery_wps_model_number)
        "WPS device name" -> UiText.text(R.string.discovery_wps_device_name)
        "WPS advertised serial number" -> UiText.text(R.string.discovery_wps_serial)
        "WPS primary device type" -> UiText.text(R.string.discovery_wps_primary_type)
        "WPS configuration state" -> UiText.text(R.string.discovery_wps_config_state)
        "WPS unconfigured" -> UiText.text(R.string.discovery_wps_unconfigured)
        "WPS configured" -> UiText.text(R.string.discovery_wps_configured)
        "WPS access point" -> UiText.text(R.string.discovery_wps_access_point)
        "WPS parse status" -> UiText.text(R.string.discovery_wps_parse_status)
        "No WPS attributes" -> UiText.text(R.string.discovery_wps_empty)
        "Truncated WPS attributes" -> UiText.text(R.string.discovery_wps_truncated)
        "Malformed WPS attributes" -> UiText.text(R.string.discovery_wps_malformed)
        "WPS advertises manufacturer %1\$s and model %2\$s. These are broadcast fields, not a visual identification." -> UiText.text(R.string.discovery_wps_identity_reason)
        " — Wi-Fi protocol tag, not the AP manufacturer." -> UiText.text(R.string.discovery_wifi_protocol_tag)
        "an H3C Wi-Fi access point or router" -> UiText.text(R.string.discovery_domestic_1)
        "a Xiaomi Wi-Fi access point or hotspot" -> UiText.text(R.string.discovery_domestic_2)
        "a MiBeacon ecosystem device" -> UiText.text(R.string.discovery_domestic_3)
        "an LYWSD03MMC temperature / humidity sensor" -> UiText.text(R.string.discovery_domestic_4)
        "a Xiaomi ecosystem scale" -> UiText.text(R.string.discovery_domestic_5)
        "a Lumi / Aqara switch" -> UiText.text(R.string.discovery_domestic_6)
        "a Midea appliance" -> UiText.text(R.string.discovery_domestic_7)
        "a Luyuan electric two-wheeler radio" -> UiText.text(R.string.discovery_domestic_8)
        "an Aima electric two-wheeler radio" -> UiText.text(R.string.discovery_domestic_9)
        "a Hello bicycle or lock radio" -> UiText.text(R.string.discovery_domestic_10)
        "an Edifier audio radio" -> UiText.text(R.string.discovery_domestic_11)
        "Keep fitness equipment" -> UiText.text(R.string.discovery_domestic_12)
        "an EZVIZ device" -> UiText.text(R.string.discovery_domestic_13)
        "a Daikin appliance or controller" -> UiText.text(R.string.discovery_domestic_14)
        "Matched a device-family fingerprint; the exact model and operating state are not established." -> UiText.text(R.string.discovery_domestic_15)
        "MiBeacon is an ecosystem advertisement; partner manufacturers also use it." -> UiText.text(R.string.discovery_domestic_16)
        "The advertised LYWSD03MMC name identifies a sensor family; encrypted frames do not expose readings." -> UiText.text(R.string.discovery_domestic_17)
        "The MI_SCALE name identifies a scale family; it does not identify a person." -> UiText.text(R.string.discovery_domestic_18)
        "Matched a vehicle-family name; this does not identify a rider or show motion." -> UiText.text(R.string.discovery_domestic_19)
        "The address prefix identifies a device family; it does not prove the device is a camera." -> UiText.text(R.string.discovery_domestic_20)
        "a weight scale" -> UiText.text(R.string.discovery_domestic_21)
        "a body-composition scale" -> UiText.text(R.string.discovery_domestic_22)
        "It offers the Weight Scale service; the service does not specify a brand or a person." -> UiText.text(R.string.discovery_domestic_23)
        "It offers the Body Composition service; the service does not specify a brand or a person." -> UiText.text(R.string.discovery_domestic_24)
        "weight-scale measurements (brand not specified)" -> UiText.text(R.string.discovery_domestic_25)
        "body-composition measurements (brand not specified)" -> UiText.text(R.string.discovery_domestic_26)
        "Google vendor service (not proof of a Find Hub tag)" -> UiText.text(R.string.discovery_domestic_27)
        "MiBeacon parse status" -> UiText.text(R.string.discovery_ble_1)
        "Malformed MiBeacon payload" -> UiText.text(R.string.discovery_ble_2)
        "Truncated MiBeacon header" -> UiText.text(R.string.discovery_ble_3)
        "MiBeacon version" -> UiText.text(R.string.discovery_ble_4)
        "MiBeacon product ID" -> UiText.text(R.string.discovery_ble_5)
        "MiBeacon frame counter" -> UiText.text(R.string.discovery_ble_6)
        "MiBeacon encryption" -> UiText.text(R.string.discovery_ble_7)
        "Encrypted — readings unavailable" -> UiText.text(R.string.discovery_ble_8)
        "Plaintext" -> UiText.text(R.string.discovery_ble_9)
        "MiBeacon advertised MAC" -> UiText.text(R.string.discovery_ble_10)
        "MiBeacon capability" -> UiText.text(R.string.discovery_ble_11)
        "MiBeacon I/O capability" -> UiText.text(R.string.discovery_ble_12)
        "Unsupported MiBeacon version" -> UiText.text(R.string.discovery_ble_13)
        "Truncated MiBeacon encrypted payload" -> UiText.text(R.string.discovery_ble_14)
        "Truncated MiBeacon object" -> UiText.text(R.string.discovery_ble_15)
        "Malformed MiBeacon object" -> UiText.text(R.string.discovery_ble_16)
        "MiBeacon temperature" -> UiText.text(R.string.discovery_ble_17)
        "MiBeacon humidity" -> UiText.text(R.string.discovery_ble_18)
        "MiBeacon battery" -> UiText.text(R.string.discovery_ble_19)
        "MiBeacon unknown object" -> UiText.text(R.string.discovery_ble_20)
        "Mi Scale parse status" -> UiText.text(R.string.discovery_ble_21)
        "Malformed Mi Scale payload" -> UiText.text(R.string.discovery_ble_22)
        "Truncated Mi Scale payload" -> UiText.text(R.string.discovery_ble_23)
        "Unsupported Mi Scale payload length" -> UiText.text(R.string.discovery_ble_24)
        "jin" -> UiText.text(R.string.discovery_ble_25)
        "Mi Scale weighing state" -> UiText.text(R.string.discovery_ble_26)
        "Empty / load removed — no current weight" -> UiText.text(R.string.discovery_ble_27)
        "Stable weight" -> UiText.text(R.string.discovery_ble_28)
        "Unstable weight — measurement in progress" -> UiText.text(R.string.discovery_ble_29)
        "Mi Scale weight" -> UiText.text(R.string.discovery_ble_30)
        "Mi Scale provisional weight" -> UiText.text(R.string.discovery_ble_31)
        "Mi Scale impedance" -> UiText.text(R.string.discovery_ble_32)
        "MiBeacon product ID 0x055B identifies LYWSD03MMC; encrypted objects do not expose readings." -> UiText.text(R.string.discovery_ble_33)
        "Company identifier carried in manufacturer-specific data; the current list cannot confirm the assigning organization." -> UiText.text(R.string.discovery_ble_34)
        else -> source
    }
}
