package app.fieldwatch

/** Resolves fixed authored explanation tokens; radio and user values pass through. */
internal object UiExplanations {
    fun text(source: String): String = when (source) {
        "Apple device type" -> UiText.text(R.string.apple_device_type)
        "Apple device (type unconfirmed)" -> UiText.text(R.string.apple_type_unknown)
        "Apple audio (model unconfirmed)" -> UiText.text(R.string.apple_audio_unknown)
        "Find My device (type unconfirmed)" -> UiText.text(R.string.apple_findmy_unknown)
        "AirPlay receiver (type unconfirmed)" -> UiText.text(R.string.apple_airplay_unknown)
        "AWDL device (type unconfirmed)" -> UiText.text(R.string.apple_awdl_unknown)
        "Hey Siri device class identifies %1\$s; the exact model is unconfirmed." -> UiText.text(R.string.apple_siri_class)
        "Nearby Info reports a watch worn and unlocked; the exact model is unconfirmed." -> UiText.text(R.string.apple_watch_activity)
        "Apple device type cannot be determined from this Continuity frame." -> UiText.text(R.string.apple_continuity_unknown)
        "AirPods (1st generation)" -> UiText.text(R.string.apple_airpods_gen1)
        "AirPods (2nd generation)" -> UiText.text(R.string.apple_airpods_gen2)
        "AirPods (3rd generation)" -> UiText.text(R.string.apple_airpods_gen3)
        "AirPods (4th generation)" -> UiText.text(R.string.apple_airpods_gen4)
        "AirPods Pro (2nd generation)" -> UiText.text(R.string.apple_airpods_pro2)
        "AirPods 4 (ANC)" -> UiText.text(R.string.apple_airpods_anc)
        "Wi-Fi access point" -> UiText.text(R.string.ui_wi_fi_access_point)
        "Bluetooth LE advertiser" -> UiText.text(R.string.explain_bluetooth_le_advertiser)
        "It is on the air, but it did not advertise a product class " -> UiText.text(R.string.explain_it_is_on_the_air_but_it_did_not_advertise_a_product_class)
        "(no Appearance, Class of Device, or well-known service that names a type)." -> UiText.text(R.string.explain_no_appearance_class_of_device_or_well_known_service_that_names_a)
        "Most likely" -> UiText.text(R.string.explain_most_likely)
        "Could be" -> UiText.text(R.string.explain_could_be)
        " This is what the device is advertising, not a visual ID." -> UiText.text(R.string.explain_this_is_what_the_device_is_advertising_not_a_visual_id)
        "Limited-discoverable: briefly looking for a nearby connection." -> UiText.text(R.string.explain_limited_discoverable_briefly_looking_for_a_nearby_connection)
        "Discoverable: other BLE devices can find it." -> UiText.text(R.string.explain_discoverable_other_ble_devices_can_find_it)
        "BLE-only: no classic Bluetooth (headsets/file-send radio)." -> UiText.text(R.string.explain_ble_only_no_classic_bluetooth_headsets_file_send_radio)
        "May also do classic Bluetooth (BR/EDR) as well as BLE." -> UiText.text(R.string.explain_may_also_do_classic_bluetooth_br_edr_as_well_as_ble)
        "Dual-mode chip: BLE and classic can run together." -> UiText.text(R.string.explain_dual_mode_chip_ble_and_classic_can_run_together)
        "Locally administered BSSID. Vehicle, mesh, and guest APs often keep this address. Not a rotating phone MAC." -> UiText.text(R.string.explain_locally_administered_bssid_vehicle_mesh_and_guest_aps_often_keep)
        "Public factory address (stable, IEEE-assigned)." -> UiText.text(R.string.explain_public_factory_address_stable_ieee_assigned)
        "Random / privacy address. The MAC can change, so this is not a lasting identity." -> UiText.text(R.string.explain_random_privacy_address_the_mac_can_change_so_this_is_not_a_lasti)
        "Anonymous: the stack hid the address." -> UiText.text(R.string.explain_anonymous_the_stack_hid_the_address)
        "Universal IEEE address (stable OUI)." -> UiText.text(R.string.explain_universal_ieee_address_stable_oui)
        "not available" -> UiText.text(R.string.explain_not_available)
        "very strong" -> UiText.text(R.string.explain_very_strong)
        "very weak" -> UiText.text(R.string.explain_very_weak)
        "Not available" -> UiText.text(R.string.ui_not_available)
        "WPA3 password (SAE handshake)" -> UiText.text(R.string.explain_wpa3_password_sae_handshake)
        "Enhanced Open (encrypted, no password)" -> UiText.text(R.string.explain_enhanced_open_encrypted_no_password)
        "WPA2 password (PSK)" -> UiText.text(R.string.explain_wpa2_password_psk)
        "Wi-Fi password (WPA/PSK)" -> UiText.text(R.string.explain_wi_fi_password_wpa_psk)
        "Enterprise login (802.1X)" -> UiText.text(R.string.explain_enterprise_login_802_1x)
        "WEP (old, weak)" -> UiText.text(R.string.explain_wep_old_weak)
        "Open or encryption not parsed" -> UiText.text(R.string.explain_open_or_encryption_not_parsed)
        "AES encryption" -> UiText.text(R.string.explain_aes_encryption)
        "TKIP (older, weaker cipher)" -> UiText.text(R.string.explain_tkip_older_weaker_cipher)
        "WPS setup is enabled" -> UiText.text(R.string.explain_wps_setup_is_enabled)
        "mesh node" -> UiText.text(R.string.explain_mesh_node)
        "ad-hoc network" -> UiText.text(R.string.explain_ad_hoc_network)
        "infrastructure access point" -> UiText.text(R.string.explain_infrastructure_access_point)
        "connection basics" -> UiText.text(R.string.explain_connection_basics)
        "attribute protocol" -> UiText.text(R.string.explain_attribute_protocol)
        "model / serial / firmware" -> UiText.text(R.string.explain_model_serial_firmware)
        "battery level" -> UiText.text(R.string.explain_battery_level)
        "keyboard, mouse, or gamepad" -> UiText.text(R.string.explain_keyboard_mouse_or_gamepad)
        "heart-rate sensor" -> UiText.text(R.string.explain_heart_rate_sensor)
        "blood-pressure sensor" -> UiText.text(R.string.explain_blood_pressure_sensor)
        "temperature / humidity style sensor" -> UiText.text(R.string.explain_temperature_humidity_style_sensor)
        "LE cycling power/speed" -> UiText.text(R.string.explain_le_cycling_power_speed)
        "Google Fast Pair (often buds/speakers)" -> UiText.text(R.string.explain_google_fast_pair_often_buds_speakers)
        "Apple Find My related" -> UiText.text(R.string.explain_apple_find_my_related)
        "Tile tracker" -> UiText.text(R.string.explain_tile_tracker)
        "Tuya IoT" -> UiText.text(R.string.explain_tuya_iot)
        "HP printer" -> UiText.text(R.string.explain_hp_printer)
        "Sonos speaker" -> UiText.text(R.string.explain_sonos_speaker)
        "August Home lock" -> UiText.text(R.string.explain_august_home_lock)
        "Apple (not ASSA ABLOY)" -> UiText.text(R.string.explain_apple_not_assa_abloy)
        "earbuds or headphones" -> UiText.text(R.string.explain_earbuds_or_headphones)
        "a speaker" -> UiText.text(R.string.explain_a_speaker)
        "a mouse" -> UiText.text(R.string.explain_a_mouse)
        "a keyboard" -> UiText.text(R.string.explain_a_keyboard)
        "a game controller" -> UiText.text(R.string.explain_a_game_controller)
        "a watch or wrist wearable" -> UiText.text(R.string.explain_a_watch_or_wrist_wearable)
        "a phone" -> UiText.text(R.string.explain_a_phone)
        "a computer or tablet" -> UiText.text(R.string.explain_a_computer_or_tablet)
        "a finder tag / tracker" -> UiText.text(R.string.explain_a_finder_tag_tracker)
        "a remote control" -> UiText.text(R.string.explain_a_remote_control)
        "an input device (keyboard, mouse, or similar)" -> UiText.text(R.string.explain_an_input_device_keyboard_mouse_or_similar)
        "a heart-rate monitor" -> UiText.text(R.string.explain_a_heart_rate_monitor)
        "a health sensor" -> UiText.text(R.string.explain_a_health_sensor)
        "a display or TV stick" -> UiText.text(R.string.explain_a_display_or_tv_stick)
        "a clock" -> UiText.text(R.string.explain_a_clock)
        "smart glasses" -> UiText.text(R.string.explain_smart_glasses)
        "earbuds or a headset" -> UiText.text(R.string.explain_earbuds_or_a_headset)
        "a computer" -> UiText.text(R.string.explain_a_computer)
        "a watch" -> UiText.text(R.string.explain_a_watch)
        "an audio device" -> UiText.text(R.string.explain_an_audio_device)
        "an input accessory" -> UiText.text(R.string.explain_an_input_accessory)
        "a keyboard, mouse, or gamepad" -> UiText.text(R.string.explain_a_keyboard_mouse_or_gamepad)
        "It offers the HID (human-interface) service." -> UiText.text(R.string.explain_it_offers_the_hid_human_interface_service)
        "headphones, a headset, or a speaker" -> UiText.text(R.string.explain_headphones_a_headset_or_a_speaker)
        "It offers a classic audio / headset service." -> UiText.text(R.string.explain_it_offers_a_classic_audio_headset_service)
        "LE Audio earbuds or a speaker" -> UiText.text(R.string.explain_le_audio_earbuds_or_a_speaker)
        "It offers Bluetooth LE Audio services." -> UiText.text(R.string.explain_it_offers_bluetooth_le_audio_services)
        "It offers the Heart Rate service." -> UiText.text(R.string.explain_it_offers_the_heart_rate_service)
        "a blood-pressure monitor" -> UiText.text(R.string.explain_a_blood_pressure_monitor)
        "It offers the Blood Pressure service." -> UiText.text(R.string.explain_it_offers_the_blood_pressure_service)
        "an environmental sensor" -> UiText.text(R.string.explain_an_environmental_sensor)
        "It offers Environmental Sensing." -> UiText.text(R.string.explain_it_offers_environmental_sensing)
        "earbuds or a speaker" -> UiText.text(R.string.explain_earbuds_or_a_speaker)
        "Google Fast Pair is present (common on buds and speakers)." -> UiText.text(R.string.explain_google_fast_pair_is_present_common_on_buds_and_speakers)
        "a Samsung SmartTag" -> UiText.text(R.string.explain_a_samsung_smarttag)
        "SmartTag service UUID." -> UiText.text(R.string.explain_smarttag_service_uuid)
        "an Apple Find My accessory" -> UiText.text(R.string.explain_an_apple_find_my_accessory)
        "Find My related UUID." -> UiText.text(R.string.explain_find_my_related_uuid)
        "a Tile tracker" -> UiText.text(R.string.explain_a_tile_tracker)
        "Tile service UUID." -> UiText.text(R.string.explain_tile_service_uuid)
        "a DULT finder tag" -> UiText.text(R.string.explain_a_dult_finder_tag)
        "a Google Find Hub tag" -> UiText.text(R.string.explain_a_google_find_hub_tag)
        "an Apple AirTag / Find My tag" -> UiText.text(R.string.explain_an_apple_airtag_find_my_tag)
        "an iPhone, iPad, or Mac" -> UiText.text(R.string.explain_an_iphone_ipad_or_mac)
        "a Windows / Surface / Xbox radio" -> UiText.text(R.string.explain_a_windows_surface_xbox_radio)
        "a Tesla BLE tire sensor" -> UiText.text(R.string.explain_a_tesla_ble_tire_sensor)
        "a BLE tire-pressure sensor" -> UiText.text(R.string.explain_a_ble_tire_pressure_sensor)
        "Vuzix smart glasses" -> UiText.text(R.string.explain_vuzix_smart_glasses)
        "a Tesla vehicle (including Cybertruck) or phone-as-key" -> UiText.text(R.string.explain_a_tesla_vehicle_including_cybertruck_or_phone_as_key)
        "a Pixel or other Google radio" -> UiText.text(R.string.explain_a_pixel_or_other_google_radio)
        "Sony headphones, a TV, or a camera" -> UiText.text(R.string.explain_sony_headphones_a_tv_or_a_camera)
        "Bose headphones or a speaker" -> UiText.text(R.string.explain_bose_headphones_or_a_speaker)
        "a Garmin watch or inReach" -> UiText.text(R.string.explain_a_garmin_watch_or_inreach)
        "an Echo, Fire, or other Amazon radio" -> UiText.text(R.string.explain_an_echo_fire_or_other_amazon_radio)
        "a Fitbit" -> UiText.text(R.string.explain_a_fitbit)
        "an Oura ring" -> UiText.text(R.string.explain_an_oura_ring)
        "a Logitech mouse, keyboard, or webcam" -> UiText.text(R.string.explain_a_logitech_mouse_keyboard_or_webcam)
        "JBL or Harman audio" -> UiText.text(R.string.explain_jbl_or_harman_audio)
        "a Sonos speaker" -> UiText.text(R.string.explain_a_sonos_speaker)
        "a GoPro" -> UiText.text(R.string.explain_a_gopro)
        "a DJI Osmo action camera" -> UiText.text(R.string.explain_a_dji_osmo_action_camera)
        "an Insta360 camera" -> UiText.text(R.string.explain_an_insta360_camera)
        "a DJI drone or controller" -> UiText.text(R.string.explain_a_dji_drone_or_controller)
        "a drone broadcasting ASTM Remote ID" -> UiText.text(R.string.explain_a_drone_broadcasting_astm_remote_id)
        "a Skydio drone" -> UiText.text(R.string.explain_a_skydio_drone)
        "an Autel drone" -> UiText.text(R.string.explain_an_autel_drone)
        "a Parrot ANAFI or Bebop drone" -> UiText.text(R.string.explain_a_parrot_anafi_or_bebop_drone)
        "a HOVERAir flying camera" -> UiText.text(R.string.explain_a_hoverair_flying_camera)
        "a NETGEAR or Orbi access point" -> UiText.text(R.string.explain_a_netgear_or_orbi_access_point)
        "a TP-Link access point" -> UiText.text(R.string.explain_a_tp_link_access_point)
        "an ASUS access point" -> UiText.text(R.string.explain_an_asus_access_point)
        "a Linksys or Velop access point" -> UiText.text(R.string.explain_a_linksys_or_velop_access_point)
        "an Eero mesh node" -> UiText.text(R.string.explain_an_eero_mesh_node)
        "a Google Wifi or Nest Wifi point" -> UiText.text(R.string.explain_a_google_wifi_or_nest_wifi_point)
        "a D-Link access point" -> UiText.text(R.string.explain_a_d_link_access_point)
        "a Belkin access point" -> UiText.text(R.string.explain_a_belkin_access_point)
        "an Xfinity gateway or hotspot" -> UiText.text(R.string.explain_an_xfinity_gateway_or_hotspot)
        "a Spectrum gateway or Spectrum Mobile hotspot" -> UiText.text(R.string.explain_a_spectrum_gateway_or_spectrum_mobile_hotspot)
        "an AT&T gateway or attwifi hotspot" -> UiText.text(R.string.explain_an_at_t_gateway_or_attwifi_hotspot)
        "a Verizon or Fios gateway" -> UiText.text(R.string.explain_a_verizon_or_fios_gateway)
        "a Starlink router" -> UiText.text(R.string.explain_a_starlink_router)
        "a Cisco Meraki access point" -> UiText.text(R.string.explain_a_cisco_meraki_access_point)
        "a Cisco Aironet, Catalyst, Business, RV, or SPVTG access point" -> UiText.text(R.string.explain_a_cisco_aironet_catalyst_business_rv_or_spvtg_access_point)
        "a Juniper Mist access point" -> UiText.text(R.string.explain_a_juniper_mist_access_point)
        "a T-Mobile Home Internet gateway or hotspot" -> UiText.text(R.string.explain_a_t_mobile_home_internet_gateway_or_hotspot)
        "a HUMAX gateway (often T-Mobile Home Internet)" -> UiText.text(R.string.explain_a_humax_gateway_often_t_mobile_home_internet)
        "a Sagemcom ISP gateway" -> UiText.text(R.string.explain_a_sagemcom_isp_gateway)
        "an Arcadyan ISP gateway" -> UiText.text(R.string.explain_an_arcadyan_isp_gateway)
        "an Askey ISP / 5G gateway" -> UiText.text(R.string.explain_an_askey_isp_5g_gateway)
        "a Calix fiber gateway" -> UiText.text(R.string.explain_a_calix_fiber_gateway)
        "a Nokia Solutions and Networks gateway" -> UiText.text(R.string.explain_a_nokia_solutions_and_networks_gateway)
        "an AirTies ISP mesh node" -> UiText.text(R.string.explain_an_airties_isp_mesh_node)
        "a Tenda access point" -> UiText.text(R.string.explain_a_tenda_access_point)
        "a Ruijie or Reyee access point" -> UiText.text(R.string.explain_a_ruijie_or_reyee_access_point)
        "a DWnet access point" -> UiText.text(R.string.explain_a_dwnet_access_point)
        "a WAVLINK access point" -> UiText.text(R.string.explain_a_wavlink_access_point)
        "a Sercomm ISP gateway" -> UiText.text(R.string.explain_a_sercomm_isp_gateway)
        "a Luxul access point" -> UiText.text(R.string.explain_a_luxul_access_point)
        "a Sophos firewall or access point" -> UiText.text(R.string.explain_a_sophos_firewall_or_access_point)
        "an AUMOVIO / Continental vehicle Wi-Fi radio" -> UiText.text(R.string.explain_an_aumovio_continental_vehicle_wi_fi_radio)
        "a CenturyLink gateway" -> UiText.text(R.string.explain_a_centurylink_gateway)
        "a GM in-car hotspot (Cadillac / GMC / Buick / Chevrolet)" -> UiText.text(R.string.explain_a_gm_in_car_hotspot_cadillac_gmc_buick_chevrolet)
        "an Audi MMI in-car hotspot" -> UiText.text(R.string.explain_an_audi_mmi_in_car_hotspot)
        "an Extreme Networks access point" -> UiText.text(R.string.explain_an_extreme_networks_access_point)
        "an Adtran fiber gateway (often CenturyLink / Quantum Fiber OEM)" -> UiText.text(R.string.explain_an_adtran_fiber_gateway_often_centurylink_quantum_fiber_oem)
        "a Cambium or IgniteNet access point" -> UiText.text(R.string.explain_a_cambium_or_ignitenet_access_point)
        "a TRENDnet access point" -> UiText.text(R.string.explain_a_trendnet_access_point)
        "a Cudy travel or home router" -> UiText.text(R.string.explain_a_cudy_travel_or_home_router)
        "a SnapAV / Control4 / Wattbox access point" -> UiText.text(R.string.explain_a_snapav_control4_wattbox_access_point)
        "an Arlo camera or VMB base station" -> UiText.text(R.string.explain_an_arlo_camera_or_vmb_base_station)
        "a Vantiva or Technicolor ISP gateway" -> UiText.text(R.string.explain_a_vantiva_or_technicolor_isp_gateway)
        "a Hitron cable gateway (often Xfinity OEM)" -> UiText.text(R.string.explain_a_hitron_cable_gateway_often_xfinity_oem)
        "an Actiontec FiOS or Frontier gateway" -> UiText.text(R.string.explain_an_actiontec_fios_or_frontier_gateway)
        "a Buffalo AirStation or router" -> UiText.text(R.string.explain_a_buffalo_airstation_or_router)
        "a Grandstream GWN access point" -> UiText.text(R.string.explain_a_grandstream_gwn_access_point)
        "an Edgecore access point" -> UiText.text(R.string.explain_an_edgecore_access_point)
        "a WatchGuard firewall or access point" -> UiText.text(R.string.explain_a_watchguard_firewall_or_access_point)
        "a Mojo Networks / Arista Cognitive Wi-Fi access point" -> UiText.text(R.string.explain_a_mojo_networks_arista_cognitive_wi_fi_access_point)
        "a Winegard RV or marine Wi-Fi radio" -> UiText.text(R.string.explain_a_winegard_rv_or_marine_wi_fi_radio)
        "an Inseego 5G or MiFi hotspot" -> UiText.text(R.string.explain_an_inseego_5g_or_mifi_hotspot)
        "a Franklin Technology 5G home-internet gateway (RG3100 class)" -> UiText.text(R.string.explain_a_franklin_technology_5g_home_internet_gateway_rg3100_class)
        "a Synology NAS or router access point" -> UiText.text(R.string.explain_a_synology_nas_or_router_access_point)
        "an HPE Aruba Instant or Instant On access point" -> UiText.text(R.string.explain_an_hpe_aruba_instant_or_instant_on_access_point)
        "a RUCKUS access point" -> UiText.text(R.string.explain_a_ruckus_access_point)
        "a Fortinet FortiAP or FortiWiFi" -> UiText.text(R.string.explain_a_fortinet_fortiap_or_fortiwifi)
        "a MikroTik router or access point" -> UiText.text(R.string.explain_a_mikrotik_router_or_access_point)
        "an EnGenius access point" -> UiText.text(R.string.explain_an_engenius_access_point)
        "a Zyxel gateway or access point" -> UiText.text(R.string.explain_a_zyxel_gateway_or_access_point)
        "a Peplink or Pepwave router" -> UiText.text(R.string.explain_a_peplink_or_pepwave_router)
        "an OpenWrt router" -> UiText.text(R.string.explain_an_openwrt_router)
        "an Arris or SURFboard cable gateway" -> UiText.text(R.string.explain_an_arris_or_surfboard_cable_gateway)
        "a Ubiquiti UniFi access point" -> UiText.text(R.string.explain_a_ubiquiti_unifi_access_point)
        "a UniFi Protect Instant camera" -> UiText.text(R.string.explain_a_unifi_protect_instant_camera)
        "a UniFi / Ubiquiti name" -> UiText.text(R.string.explain_a_unifi_ubiquiti_name)
        "an ecobee thermostat" -> UiText.text(R.string.explain_an_ecobee_thermostat)
        "a Sensi thermostat" -> UiText.text(R.string.explain_a_sensi_thermostat)
        "a Honeywell Home or Lyric thermostat" -> UiText.text(R.string.explain_a_honeywell_home_or_lyric_thermostat)
        "a Honeywell Xenon healthcare barcode scanner" -> UiText.text(R.string.explain_a_honeywell_xenon_healthcare_barcode_scanner)
        "an Omron blood-pressure cuff or scale" -> UiText.text(R.string.explain_an_omron_blood_pressure_cuff_or_scale)
        "a Withings scale or blood-pressure monitor" -> UiText.text(R.string.explain_a_withings_scale_or_blood_pressure_monitor)
        "a Dexcom glucose sensor" -> UiText.text(R.string.explain_a_dexcom_glucose_sensor)
        "a Nest thermostat or Nest Labs BLE sensor" -> UiText.text(R.string.explain_a_nest_thermostat_or_nest_labs_ble_sensor)
        "a Nest Protect, camera, or other Weave BLE device" -> UiText.text(R.string.explain_a_nest_protect_camera_or_other_weave_ble_device)
        "a Haiku or Mammoth ceiling fan" -> UiText.text(R.string.explain_a_haiku_or_mammoth_ceiling_fan)
        "a Tuya BLE gadget (plug, light, camera, sensor)" -> UiText.text(R.string.explain_a_tuya_ble_gadget_plug_light_camera_sensor)
        "an ASSA ABLOY lock, Yale lock, HID reader, or Seos credential" -> UiText.text(R.string.explain_an_assa_abloy_lock_yale_lock_hid_reader_or_seos_credential)
        "an August smart lock" -> UiText.text(R.string.explain_an_august_smart_lock)
        "a Schlage or Allegion lock" -> UiText.text(R.string.explain_a_schlage_or_allegion_lock)
        "a Nuki lock or opener" -> UiText.text(R.string.explain_a_nuki_lock_or_opener)
        "a SALTO access reader or lock" -> UiText.text(R.string.explain_a_salto_access_reader_or_lock)
        "a dormakaba, Saflok, or Oracode lock" -> UiText.text(R.string.explain_a_dormakaba_saflok_or_oracode_lock)
        "a Lockly smart lock" -> UiText.text(R.string.explain_a_lockly_smart_lock)
        "a Kwikset Kevo or Unikey lock" -> UiText.text(R.string.explain_a_kwikset_kevo_or_unikey_lock)
        "a Master Lock padlock" -> UiText.text(R.string.explain_a_master_lock_padlock)
        "an igloohome lock or keybox" -> UiText.text(R.string.explain_an_igloohome_lock_or_keybox)
        "a Tedee smart lock" -> UiText.text(R.string.explain_a_tedee_smart_lock)
        "a Paxton reader or Net2 access point" -> UiText.text(R.string.explain_a_paxton_reader_or_net2_access_point)
        "a Kwikset lock" -> UiText.text(R.string.explain_a_kwikset_lock)
        "a Chamberlain myQ garage hub" -> UiText.text(R.string.explain_a_chamberlain_myq_garage_hub)
        "a Chevrolet in-car Wi-Fi hotspot" -> UiText.text(R.string.explain_a_chevrolet_in_car_wi_fi_hotspot)
        "a Rivian vehicle, phone key, or sensor" -> UiText.text(R.string.explain_a_rivian_vehicle_phone_key_or_sensor)
        "a Ford or Lincoln vehicle or phone-as-key" -> UiText.text(R.string.explain_a_ford_or_lincoln_vehicle_or_phone_as_key)
        "a Honda or Acura vehicle or phone-as-key" -> UiText.text(R.string.explain_a_honda_or_acura_vehicle_or_phone_as_key)
        "a Hyundai or Genesis vehicle or phone-as-key" -> UiText.text(R.string.explain_a_hyundai_or_genesis_vehicle_or_phone_as_key)
        "a Toyota or Lexus vehicle or phone-as-key" -> UiText.text(R.string.explain_a_toyota_or_lexus_vehicle_or_phone_as_key)
        "a Nissan or Infiniti vehicle or phone-as-key" -> UiText.text(R.string.explain_a_nissan_or_infiniti_vehicle_or_phone_as_key)
        "a Subaru vehicle or phone-as-key" -> UiText.text(R.string.explain_a_subaru_vehicle_or_phone_as_key)
        "a BMW vehicle, phone-as-key, or factory hotspot" -> UiText.text(R.string.explain_a_bmw_vehicle_phone_as_key_or_factory_hotspot)
        "a Volkswagen vehicle or phone-as-key" -> UiText.text(R.string.explain_a_volkswagen_vehicle_or_phone_as_key)
        "a Porsche vehicle or phone-as-key" -> UiText.text(R.string.explain_a_porsche_vehicle_or_phone_as_key)
        "a Jaguar, Land Rover, or Range Rover" -> UiText.text(R.string.explain_a_jaguar_land_rover_or_range_rover)
        "a BYD vehicle or phone-as-key" -> UiText.text(R.string.explain_a_byd_vehicle_or_phone_as_key)
        "a Govee light or sensor" -> UiText.text(R.string.explain_a_govee_light_or_sensor)
        "an HP printer" -> UiText.text(R.string.explain_an_hp_printer)
        "an Epson EcoTank or WorkForce printer" -> UiText.text(R.string.explain_an_epson_ecotank_or_workforce_printer)
        "an LG webOS TV" -> UiText.text(R.string.explain_an_lg_webos_tv)
        "a Roku streaming stick or Roku TV (often a hidden Wi-Fi Direct remote AP)" -> UiText.text(R.string.explain_a_roku_streaming_stick_or_roku_tv_often_a_hidden_wi_fi_direct_re)
        "a Samsung fridge, range, oven, or cooktop (setup AP)" -> UiText.text(R.string.explain_a_samsung_fridge_range_oven_or_cooktop_setup_ap)
        "an EcoWater water softener (setup AP)" -> UiText.text(R.string.explain_an_ecowater_water_softener_setup_ap)
        "a Nespresso coffee machine" -> UiText.text(R.string.explain_a_nespresso_coffee_machine)
        "a RadiaCode radiation detector" -> UiText.text(R.string.explain_a_radiacode_radiation_detector)
        "Shokz OpenRun or OpenFit headphones" -> UiText.text(R.string.explain_shokz_openrun_or_openfit_headphones)
        "a Mercedes MBUX in-car hotspot" -> UiText.text(R.string.explain_a_mercedes_mbux_in_car_hotspot)
        "a Motive / KeepTruckin fleet ELD hotspot" -> UiText.text(R.string.explain_a_motive_keeptruckin_fleet_eld_hotspot)
        "a PeopleNet fleet ELD hotspot" -> UiText.text(R.string.explain_a_peoplenet_fleet_eld_hotspot)
        "a Uconnect in-car hotspot" -> UiText.text(R.string.explain_a_uconnect_in_car_hotspot)
        "a CarPlay in-car hotspot" -> UiText.text(R.string.explain_a_carplay_in_car_hotspot)
        "a Cradlepoint vehicle router (often public-safety / fleet)" -> UiText.text(R.string.explain_a_cradlepoint_vehicle_router_often_public_safety_fleet)
        "a Sierra Wireless AirLink vehicle gateway" -> UiText.text(R.string.explain_a_sierra_wireless_airlink_vehicle_gateway)
        "a Compex access point (sometimes public-safety / fleet)" -> UiText.text(R.string.explain_a_compex_access_point_sometimes_public_safety_fleet)
        "a Novatel Wireless / Inseego vehicle radio" -> UiText.text(R.string.explain_a_novatel_wireless_inseego_vehicle_radio)
        "a Utility, Inc vehicle or public-safety radio" -> UiText.text(R.string.explain_a_utility_inc_vehicle_or_public_safety_radio)
        "a GL.iNet travel router" -> UiText.text(R.string.explain_a_gl_inet_travel_router)
        "an iBeacon" -> UiText.text(R.string.explain_an_ibeacon)
        "a Target Atrius basket tag" -> UiText.text(R.string.explain_a_target_atrius_basket_tag)
        "a Minew BLE beacon or sensor" -> UiText.text(R.string.explain_a_minew_ble_beacon_or_sensor)
        "an Estimote beacon" -> UiText.text(R.string.explain_an_estimote_beacon)
        "a Kontakt.io beacon" -> UiText.text(R.string.explain_a_kontakt_io_beacon)
        "an Iteris BlueTOAD / Vantage Velocity roadside Bluetooth travel-time reader" -> UiText.text(R.string.explain_an_iteris_bluetoad_vantage_velocity_roadside_bluetooth_travel_ti)
        "a BLIP Systems BlipTrack roadside travel-time sensor" -> UiText.text(R.string.explain_a_blip_systems_bliptrack_roadside_travel_time_sensor)
        "a Flock Raven or ShotSpotter acoustic gunshot sensor" -> UiText.text(R.string.explain_a_flock_raven_or_shotspotter_acoustic_gunshot_sensor)
        "a Digital Ally body-worn or in-car camera" -> UiText.text(R.string.explain_a_digital_ally_body_worn_or_in_car_camera)
        "a Reveal Media body-worn camera" -> UiText.text(R.string.explain_a_reveal_media_body_worn_camera)
        "a Wolfcom body-worn or in-car camera" -> UiText.text(R.string.explain_a_wolfcom_body_worn_or_in_car_camera)
        "a Panasonic i-PRO camera or Arbitrator in-car system" -> UiText.text(R.string.explain_a_panasonic_i_pro_camera_or_arbitrator_in_car_system)
        "a Limitless Pendant conversation recorder" -> UiText.text(R.string.explain_a_limitless_pendant_conversation_recorder)
        "a Bee Pioneer wearable recorder" -> UiText.text(R.string.explain_a_bee_pioneer_wearable_recorder)
        "an Omi pendant or OpenGlass camera glasses" -> UiText.text(R.string.explain_an_omi_pendant_or_openglass_camera_glasses)
        "a Friend Pendant necklace" -> UiText.text(R.string.explain_a_friend_pendant_necklace)
        "Brilliant Labs Frame AR glasses" -> UiText.text(R.string.explain_brilliant_labs_frame_ar_glasses)
        "Even Realities G1 glasses" -> UiText.text(R.string.explain_even_realities_g1_glasses)
        "a Hayden AI bus- or vehicle-mounted camera" -> UiText.text(R.string.explain_a_hayden_ai_bus_or_vehicle_mounted_camera)
        "a Miovision intersection traffic camera" -> UiText.text(R.string.explain_a_miovision_intersection_traffic_camera)
        "a Tattile plate reader" -> UiText.text(R.string.explain_a_tattile_plate_reader)
        "an LVT / LiveView solar surveillance trailer" -> UiText.text(R.string.explain_an_lvt_liveview_solar_surveillance_trailer)
        "a Hanwha Vision / Wisenet camera" -> UiText.text(R.string.explain_a_hanwha_vision_wisenet_camera)
        "a Uniview / UNV camera" -> UiText.text(R.string.explain_a_uniview_unv_camera)
        "a Rhombus cloud camera" -> UiText.text(R.string.explain_a_rhombus_cloud_camera)
        "a MeshCore LoRa companion radio" -> UiText.text(R.string.explain_a_meshcore_lora_companion_radio)
        "a goTenna Mesh or Pro radio" -> UiText.text(R.string.explain_a_gotenna_mesh_or_pro_radio)
        "a SenseCAP LoRaWAN / Helium gateway" -> UiText.text(R.string.explain_a_sensecap_lorawan_helium_gateway)
        "a RAK WisGate LoRaWAN gateway" -> UiText.text(R.string.explain_a_rak_wisgate_lorawan_gateway)
        "a GhostESP ESP32 audit board" -> UiText.text(R.string.explain_a_ghostesp_esp32_audit_board)
        "a Bruce ESP32 pentest board" -> UiText.text(R.string.explain_a_bruce_esp32_pentest_board)
        "a camera-module radio (LiteOn or similar)" -> UiText.text(R.string.explain_a_camera_module_radio_liteon_or_similar)
        "a finder tag" -> UiText.text(R.string.explain_a_finder_tag)
        "a Wi-Fi Direct access point" -> UiText.text(R.string.explain_a_wi_fi_direct_access_point)
        "SSID starts with DIRECT-." -> UiText.text(R.string.explain_ssid_starts_with_direct)
        "a phone or TV using Wi-Fi Direct" -> UiText.text(R.string.explain_a_phone_or_tv_using_wi_fi_direct)
        "a phone hotspot" -> UiText.text(R.string.explain_a_phone_hotspot)
        "SSID looks like a phone hotspot." -> UiText.text(R.string.explain_ssid_looks_like_a_phone_hotspot)
        "a mesh Wi-Fi node" -> UiText.text(R.string.explain_a_mesh_wi_fi_node)
        "Capability list includes mesh." -> UiText.text(R.string.explain_capability_list_includes_mesh)
        "a hidden Wi-Fi access point" -> UiText.text(R.string.explain_a_hidden_wi_fi_access_point)
        "SSID is hidden; the radio is still beaconing." -> UiText.text(R.string.explain_ssid_is_hidden_the_radio_is_still_beaconing)
        "a Wi-Fi access point" -> UiText.text(R.string.explain_a_wi_fi_access_point)
        "Stock Android only reports beaconing APs." -> UiText.text(R.string.explain_stock_android_only_reports_beaconing_aps)
        "Probably" -> UiText.text(R.string.explain_probably)
        "strong" -> UiText.text(R.string.explain_strong)
        "medium" -> UiText.text(R.string.explain_medium)
        "weak" -> UiText.text(R.string.explain_weak)
        "It advertises Appearance as %1\$s." -> UiText.text(R.string.explain_it_advertises_appearance_as_1_s)
        "Class of Device says %1\$s." -> UiText.text(R.string.explain_class_of_device_says_1_s)
        "Matched signature %1\$s." -> UiText.text(R.string.explain_matched_signature_1_s)
        "%1\$s — long-range BLE (slower, farther)" -> UiText.text(R.string.explain_1_s_long_range_ble_slower_farther)
        "%1\$s — faster BLE (Bluetooth 5)" -> UiText.text(R.string.explain_1_s_faster_ble_bluetooth_5)
        "%1\$s — standard BLE radio" -> UiText.text(R.string.explain_1_s_standard_ble_radio)
        "Google manufacturer data" -> UiText.text(R.string.payload_google_manufacturer_data)
        "%1\$s bytes" -> UiText.text(R.string.payload_1_s_bytes)
        "a Tesla vehicle or phone-as-key" -> UiText.text(R.string.payload_a_tesla_vehicle_or_phone_as_key)
        "Tesla phone-key iBeacon UUID (iOS background find)." -> UiText.text(R.string.payload_tesla_phone_key_ibeacon_uuid_ios_background_find)
        "Target / Atrius iBeacon UUID (shopping-basket asset tag)." -> UiText.text(R.string.payload_target_atrius_ibeacon_uuid_shopping_basket_asset_tag)
        "Apple iBeacon payload." -> UiText.text(R.string.payload_apple_ibeacon_payload)
        "an iPhone or iPad offering AirDrop" -> UiText.text(R.string.payload_an_iphone_or_ipad_offering_airdrop)
        "Apple AirDrop advertisement." -> UiText.text(R.string.payload_apple_airdrop_advertisement)
        "AirPods or Beats headphones" -> UiText.text(R.string.payload_airpods_or_beats_headphones)
        "Apple Proximity Pairing: %1\$s." -> UiText.text(R.string.payload_apple_proximity_pairing_1_s)
        "Apple Proximity Pairing (AirPods / Beats)." -> UiText.text(R.string.payload_apple_proximity_pairing_airpods_beats)
        "an Apple device that just heard “Hey Siri”" -> UiText.text(R.string.payload_an_apple_device_that_just_heard_hey_siri)
        "Hey Siri advertisement." -> UiText.text(R.string.payload_hey_siri_advertisement)
        "an AirPlay speaker or Apple TV" -> UiText.text(R.string.payload_an_airplay_speaker_or_apple_tv)
        "AirPlay advertisement." -> UiText.text(R.string.payload_airplay_advertisement)
        "an Apple device doing Handoff" -> UiText.text(R.string.payload_an_apple_device_doing_handoff)
        "Handoff advertisement." -> UiText.text(R.string.payload_handoff_advertisement)
        "an Apple device looking for Instant Hotspot" -> UiText.text(R.string.payload_an_apple_device_looking_for_instant_hotspot)
        "Tethering-target advertisement." -> UiText.text(R.string.payload_tethering_target_advertisement)
        "an iPhone/iPad offering Instant Hotspot" -> UiText.text(R.string.payload_an_iphone_ipad_offering_instant_hotspot)
        "Tethering-source advertisement." -> UiText.text(R.string.payload_tethering_source_advertisement)
        "an Apple device (Nearby Action)" -> UiText.text(R.string.payload_an_apple_device_nearby_action)
        "an iPhone / iPad / Mac (Nearby Info)" -> UiText.text(R.string.payload_an_iphone_ipad_mac_nearby_info)
        "a Find My network radio" -> UiText.text(R.string.payload_a_find_my_network_radio)
        "Apple Offline Finding — AirTag, Find My accessory, or an Apple device locating itself." -> UiText.text(R.string.payload_apple_offline_finding_airtag_find_my_accessory_or_an_apple_devic)
        "a Fast Pair accessory (often earbuds or a speaker)" -> UiText.text(R.string.payload_a_fast_pair_accessory_often_earbuds_or_a_speaker)
        "Google Fast Pair model 0x%06X, in pairing mode." -> UiText.text(R.string.payload_google_fast_pair_model_0x_06x_in_pairing_mode)
        "a Fast Pair accessory already paired to someone" -> UiText.text(R.string.payload_a_fast_pair_accessory_already_paired_to_someone)
        "Google Fast Pair account-key broadcast (not in pairing mode)." -> UiText.text(R.string.payload_google_fast_pair_account_key_broadcast_not_in_pairing_mode)
        "Find Hub separated (unwanted-tracking) frame." -> UiText.text(R.string.payload_find_hub_separated_unwanted_tracking_frame)
        "Find Hub nearby frame." -> UiText.text(R.string.payload_find_hub_nearby_frame)
        "an Eddystone beacon" -> UiText.text(R.string.payload_an_eddystone_beacon)
        "Eddystone service data." -> UiText.text(R.string.payload_eddystone_service_data)
        "Apple payload" -> UiText.text(R.string.payload_apple_payload)
        "%1\$s bytes (unparsed)" -> UiText.text(R.string.payload_1_s_bytes_unparsed)
        "Apple Continuity type" -> UiText.text(R.string.payload_apple_continuity_type)
        "%1\$s bytes of HomeKit setup data" -> UiText.text(R.string.payload_1_s_bytes_of_homekit_setup_data)
        "This device is advertising as an AirPlay source or target." -> UiText.text(R.string.payload_this_device_is_advertising_as_an_airplay_source_or_target)
        "Apple Watch wrist / unlock related." -> UiText.text(R.string.payload_apple_watch_wrist_unlock_related)
        "Payload" -> UiText.text(R.string.payload_payload)
        "Proximity Pairing (AirPods / Beats)" -> UiText.text(R.string.payload_proximity_pairing_airpods_beats)
        "Magic Switch (Watch)" -> UiText.text(R.string.payload_magic_switch_watch)
        "Handoff or Instant Hotspot (target)" -> UiText.text(R.string.payload_handoff_or_instant_hotspot_target)
        "Instant Hotspot (source)" -> UiText.text(R.string.payload_instant_hotspot_source)
        "Find My / Offline Finding" -> UiText.text(R.string.payload_find_my_offline_finding)
        "Nearby Action (extended)" -> UiText.text(R.string.payload_nearby_action_extended)
        "unlisted" -> UiText.text(R.string.label_unlisted)
        "truncated (%1\$s bytes)" -> UiText.text(R.string.payload_truncated_1_s_bytes)
        "%1\$s — Tesla phone-as-key (iOS background find). Not a mall beacon." -> UiText.text(R.string.payload_1_s_tesla_phone_as_key_ios_background_find_not_a_mall_beacon)
        "iBeacon major / minor" -> UiText.text(R.string.payload_ibeacon_major_minor)
        "iBeacon calibrated TX" -> UiText.text(R.string.payload_ibeacon_calibrated_tx)
        "%1\$s dBm at 1 m (used to estimate range)" -> UiText.text(R.string.payload_1_s_dbm_at_1_m_used_to_estimate_range)
        "Someone nearby is offering AirDrop (%1\$s bytes)." -> UiText.text(R.string.payload_someone_nearby_is_offering_airdrop_1_s_bytes)
        "Someone nearby has AirDrop receiving on. Hashes are truncated IDs, not names." -> UiText.text(R.string.payload_someone_nearby_has_airdrop_receiving_on_hashes_are_truncated_ids)
        "Apple ID hash (2 bytes)" -> UiText.text(R.string.payload_apple_id_hash_2_bytes)
        "Proximity Pairing, truncated." -> UiText.text(R.string.payload_proximity_pairing_truncated)
        "Proximity Pairing." -> UiText.text(R.string.payload_proximity_pairing)
        "Product" -> UiText.text(R.string.payload_product)
        "Apple audio 0x%04X" -> UiText.text(R.string.payload_apple_audio_0x_04x)
        "Pod position" -> UiText.text(R.string.payload_pod_position)
        "Battery (left / right)" -> UiText.text(R.string.payload_battery_left_right)
        "case" -> UiText.text(R.string.payload_case)
        "right" -> UiText.text(R.string.payload_right)
        "left" -> UiText.text(R.string.payload_left)
        "Case battery" -> UiText.text(R.string.payload_case_battery)
        "Charging" -> UiText.text(R.string.payload_charging)
        "Color" -> UiText.text(R.string.ui_color)
        "One or both out of the case" -> UiText.text(R.string.payload_one_or_both_out_of_the_case)
        "Case open" -> UiText.text(R.string.payload_case_open)
        "Taken out / in-ear transition" -> UiText.text(R.string.payload_taken_out_in_ear_transition)
        "One in ear" -> UiText.text(R.string.payload_one_in_ear)
        "Both out, not in ear" -> UiText.text(R.string.payload_both_out_not_in_ear)
        "In-ear activity" -> UiText.text(R.string.payload_in_ear_activity)
        "Both in ear" -> UiText.text(R.string.payload_both_in_ear)
        "One in ear (sharing?)" -> UiText.text(R.string.payload_one_in_ear_sharing)
        "Both in case, lid open" -> UiText.text(R.string.payload_both_in_case_lid_open)
        "Both in case, lid closed" -> UiText.text(R.string.payload_both_in_case_lid_closed)
        "In case" -> UiText.text(R.string.payload_in_case)
        "Status 0x%02X" -> UiText.text(R.string.payload_status_0x_02x)
        "White" -> UiText.text(R.string.payload_white)
        "Black" -> UiText.text(R.string.payload_black)
        "Red" -> UiText.text(R.string.payload_red)
        "Blue" -> UiText.text(R.string.payload_blue)
        "Pink" -> UiText.text(R.string.payload_pink)
        "Gray" -> UiText.text(R.string.payload_gray)
        "Silver" -> UiText.text(R.string.payload_silver)
        "Gold" -> UiText.text(R.string.payload_gold)
        "Rose gold" -> UiText.text(R.string.payload_rose_gold)
        "Space gray" -> UiText.text(R.string.payload_space_gray)
        "Dark blue" -> UiText.text(R.string.payload_dark_blue)
        "Light blue" -> UiText.text(R.string.payload_light_blue)
        "Yellow" -> UiText.text(R.string.payload_yellow)
        "unknown / not present" -> UiText.text(R.string.payload_unknown_not_present)
        "Siri was just triggered on a nearby Apple device." -> UiText.text(R.string.payload_siri_was_just_triggered_on_a_nearby_apple_device)
        "class 0x%04X" -> UiText.text(R.string.payload_class_0x_04x)
        "A %1\$s just heard a Siri trigger. The packet carries a short voice hash, not the words." -> UiText.text(R.string.payload_a_1_s_just_heard_a_siri_trigger_the_packet_carries_a_short_voice)
        "Continuity Handoff: a task can be continued on another Apple device. Payload is encrypted." -> UiText.text(R.string.payload_continuity_handoff_a_task_can_be_continued_on_another_apple_devi)
        "Instant Hotspot (looking)" -> UiText.text(R.string.payload_instant_hotspot_looking)
        "This Apple device is searching for a paired phone’s hotspot." -> UiText.text(R.string.payload_this_apple_device_is_searching_for_a_paired_phone_s_hotspot)
        "An iPhone/iPad is offering a personal hotspot." -> UiText.text(R.string.payload_an_iphone_ipad_is_offering_a_personal_hotspot)
        "type %1\$s" -> UiText.text(R.string.payload_type_1_s)
        "Instant Hotspot (offering)" -> UiText.text(R.string.payload_instant_hotspot_offering)
        "Paired iPhone/iPad hotspot" -> UiText.text(R.string.payload_paired_iphone_ipad_hotspot)
        " · %1\$s/5 bars" -> UiText.text(R.string.payload_1_s_5_bars)
        "Nearby Action advertisement." -> UiText.text(R.string.payload_nearby_action_advertisement)
        "Nearby Action: %1\$s." -> UiText.text(R.string.payload_nearby_action_1_s)
        "Apple TV setup" -> UiText.text(R.string.payload_apple_tv_setup)
        "Mobile backup" -> UiText.text(R.string.payload_mobile_backup)
        "Watch setup" -> UiText.text(R.string.payload_watch_setup)
        "Apple TV pair" -> UiText.text(R.string.payload_apple_tv_pair)
        "Wi-Fi password sharing (prompting nearby iPhones)" -> UiText.text(R.string.payload_wi_fi_password_sharing_prompting_nearby_iphones)
        "iOS setup" -> UiText.text(R.string.payload_ios_setup)
        "Repair" -> UiText.text(R.string.payload_repair)
        "Speaker setup" -> UiText.text(R.string.payload_speaker_setup)
        "Whole-home audio setup" -> UiText.text(R.string.payload_whole_home_audio_setup)
        "Answered a call" -> UiText.text(R.string.payload_answered_a_call)
        "Ended a call" -> UiText.text(R.string.payload_ended_a_call)
        "Remote AutoFill" -> UiText.text(R.string.payload_remote_autofill)
        "Companion Link proximity" -> UiText.text(R.string.payload_companion_link_proximity)
        "Remote display" -> UiText.text(R.string.payload_remote_display)
        "action 0x%02X" -> UiText.text(R.string.payload_action_0x_02x)
        "Apple device usage state." -> UiText.text(R.string.payload_apple_device_usage_state)
        "activity unknown" -> UiText.text(R.string.payload_activity_unknown)
        "activity reporting off" -> UiText.text(R.string.payload_activity_reporting_off)
        "idle (screen locked)" -> UiText.text(R.string.payload_idle_screen_locked)
        "audio playing, screen locked" -> UiText.text(R.string.payload_audio_playing_screen_locked)
        "active (screen on)" -> UiText.text(R.string.payload_active_screen_on)
        "screen on, video playing" -> UiText.text(R.string.payload_screen_on_video_playing)
        "Watch on wrist and unlocked" -> UiText.text(R.string.payload_watch_on_wrist_and_unlocked)
        "recent interaction" -> UiText.text(R.string.payload_recent_interaction)
        "user is driving" -> UiText.text(R.string.payload_user_is_driving)
        "phone or FaceTime call" -> UiText.text(R.string.payload_phone_or_facetime_call)
        "activity 0x%X" -> UiText.text(R.string.payload_activity_0x_x)
        "primary iCloud device" -> UiText.text(R.string.payload_primary_icloud_device)
        "AirDrop receiving on" -> UiText.text(R.string.payload_airdrop_receiving_on)
        "Wi-Fi on" -> UiText.text(R.string.payload_wi_fi_on)
        "AirPods connected" -> UiText.text(R.string.payload_airpods_connected)
        "Watch locked" -> UiText.text(R.string.payload_watch_locked)
        "What the Apple device is doing" -> UiText.text(R.string.payload_what_the_apple_device_is_doing)
        "Nearby Info advertisement." -> UiText.text(R.string.payload_nearby_info_advertisement)
        "Phone is idle / locked." -> UiText.text(R.string.payload_phone_is_idle_locked)
        "Audio playing with the screen locked." -> UiText.text(R.string.payload_audio_playing_with_the_screen_locked)
        "Screen is on — someone is using it." -> UiText.text(R.string.payload_screen_is_on_someone_is_using_it)
        "Device reports the user is driving." -> UiText.text(R.string.payload_device_reports_the_user_is_driving)
        "In a phone or FaceTime call." -> UiText.text(R.string.payload_in_a_phone_or_facetime_call)
        "Offline Finding advertisement." -> UiText.text(R.string.payload_offline_finding_advertisement)
        "full" -> UiText.text(R.string.payload_full)
        "low" -> UiText.text(R.string.payload_low)
        "critical" -> UiText.text(R.string.payload_critical)
        "Broadcasting a public key so the Find My network can report a location. " -> UiText.text(R.string.payload_broadcasting_a_public_key_so_the_find_my_network_can_report_a_lo)
        "Used by AirTags, Find My accessories, and Apple devices locating themselves. " -> UiText.text(R.string.payload_used_by_airtags_find_my_accessories_and_apple_devices_locating_t)
        "Owner seen recently. " -> UiText.text(R.string.payload_owner_seen_recently)
        "Owner not seen in the current key window. " -> UiText.text(R.string.payload_owner_not_seen_in_the_current_key_window)
        "Battery %1\$s. " -> UiText.text(R.string.payload_battery_1_s)
        "(%1\$s-byte key fragment — not a serial number.)" -> UiText.text(R.string.payload_1_s_byte_key_fragment_not_a_serial_number)
        "In pairing mode — Android will pop a tap-to-pair card." -> UiText.text(R.string.payload_in_pairing_mode_android_will_pop_a_tap_to_pair_card)
        "Model ID" -> UiText.text(R.string.payload_model_id)
        "0x%06X (not in the local name list)" -> UiText.text(R.string.payload_0x_06x_not_in_the_local_name_list)
        "wants to show a pairing card" -> UiText.text(R.string.payload_wants_to_show_a_pairing_card)
        "hiding the pairing card (e.g. buds back in the case)" -> UiText.text(R.string.payload_hiding_the_pairing_card_e_g_buds_back_in_the_case)
        "filter type %1\$s" -> UiText.text(R.string.payload_filter_type_1_s)
        "account-key bloom filter" -> UiText.text(R.string.payload_account_key_bloom_filter)
        "Already paired to an account (not in pairing mode). %1\$s. Version %2\$s." -> UiText.text(R.string.payload_already_paired_to_an_account_not_in_pairing_mode_1_s_version_2_s)
        "truncated" -> UiText.text(R.string.payload_truncated)
        "Eddystone-UID namespace" -> UiText.text(R.string.payload_eddystone_uid_namespace)
        "Eddystone-UID instance" -> UiText.text(R.string.payload_eddystone_uid_instance)
        "telemetry (battery / temperature / advert count)" -> UiText.text(R.string.payload_telemetry_battery_temperature_advert_count)
        "ephemeral ID (rotating)" -> UiText.text(R.string.payload_ephemeral_id_rotating)
        "separated (unwanted-tracking mode)" -> UiText.text(R.string.payload_separated_unwanted_tracking_mode)
        "nearby / with owner" -> UiText.text(R.string.payload_nearby_with_owner)
        "frame 0x%02X" -> UiText.text(R.string.payload_frame_0x_02x)
        "Windows desktop" -> UiText.text(R.string.payload_windows_desktop)
        "Windows phone" -> UiText.text(R.string.payload_windows_phone)
        "Windows laptop" -> UiText.text(R.string.payload_windows_laptop)
        "Windows tablet" -> UiText.text(R.string.payload_windows_tablet)
        "Microsoft Nearby Sharing / Swift Pair" -> UiText.text(R.string.payload_microsoft_nearby_sharing_swift_pair)
        "A %1\$s is advertising for quick pairing or sharing." -> UiText.text(R.string.payload_a_1_s_is_advertising_for_quick_pairing_or_sharing)
        "Microsoft manufacturer data" -> UiText.text(R.string.payload_microsoft_manufacturer_data)
        "AltBeacon major / minor" -> UiText.text(R.string.payload_altbeacon_major_minor)
        "<hidden>" -> UiText.text(R.string.payload_hidden)
        "unnamed LE" -> UiText.text(R.string.ui_unnamed_le)
        "%1\$s device" -> UiText.text(R.string.payload_1_s_device)
        "unnamed" -> UiText.text(R.string.payload_unnamed)
        "Google Fast Pair model %1\$s (0x%2\$06X), in pairing mode." -> UiText.text(R.string.payload_google_fast_pair_model_1_s_0x_2_06x_in_pairing_mode)
        " · phone battery %1\$s%%" -> UiText.text(R.string.payload_phone_battery_1_s)
        "rand" -> UiText.text(R.string.status_random)
        "pair" -> UiText.text(R.string.status_pairing)
        "gone" -> UiText.text(R.string.status_gone)
        "Shows on Live. Bookmark (top-right) is the alert; this does not turn it on." -> UiText.text(R.string.detail_custom_name_hint)
        "Looking up place names (%1\$s of %2\$s)…" -> UiText.text(R.string.lookup_place_progress)
        "0 eligible radios (need Extra attention / payload latlon / GPS stamp)" -> UiText.text(R.string.detail_tak_no_eligible_radios)
        "Pinned to this BSSID. Vehicle, mesh, and guest APs often keep a locally administered address." -> UiText.text(R.string.detail_custom_name_bssid_hint)
        else -> UiDiscoveryText.text(source).let { if (it != source) it else UiDetailText.text(source) }
    }
}
