package app.fieldwatch

/** Exact author templates; interpolated device and user text never enters this lookup. */
object UiReportText {
    fun text(source: String): String = when (source) {
        "DISCLAIMER" -> UiText.text(R.string.report_disclaimer)
        "Takeaway: {0}" -> UiText.text(R.string.report_takeaway_0)
        "MAC tails (**:**:**) and GPS coordinates masked. Logs on the phone are unchanged." -> UiText.text(R.string.report_mac_tails_and_gps_coordinates_masked_logs_on_the_phone_are_unchan)
        "Privacy" -> UiText.text(R.string.report_privacy)
        "Heard {0} AP(s); {1} hidden SSID; {2} sat most of the window." -> UiText.text(R.string.report_heard_0_ap_s_1_hidden_ssid_2_sat_most_of_the_window)
        "Channel occupancy:" -> UiText.text(R.string.report_channel_occupancy)
        "unknown" -> UiText.text(R.string.report_unknown)
        "ch {0}" -> UiText.text(R.string.report_ch_0)
        "  {0} — {1} AP(s), strongest {2} dBm" -> UiText.text(R.string.report_0_1_ap_s_strongest_2_dbm)
        "Loudest APs:" -> UiText.text(R.string.report_loudest_aps)
        "    extra attention ({0}): {1}" -> UiText.text(R.string.report_extra_attention_0_1)
        "Hidden SSIDs:" -> UiText.text(R.string.report_hidden_ssids)
        "  · {0}  {1}  {2} dBm  ch {3}" -> UiText.text(R.string.report_0_1_2_dbm_ch_3)
        "Heard {0} advertiser(s); {1} with randomized addresses; {2} signature-matched." -> UiText.text(R.string.report_heard_0_advertiser_s_1_with_randomized_addresses_2_signature_matc)
        "Unmatched rotating BLE omitted from lists ({0}). Counts include them. Sit export has every radio." -> UiText.text(R.string.report_unmatched_rotating_ble_omitted_from_lists_0_counts_include_them_s)
        "Notable BLE:" -> UiText.text(R.string.report_notable_ble)
        "None in this window." -> UiText.text(R.string.report_none_in_this_window)
        "  · {0}  {1}  {2} dBm" -> UiText.text(R.string.report_0_1_2_dbm)
        "  extra attention ({0}): {1}" -> UiText.text(R.string.report_extra_attention_0_1_18)
        "Sat most of this window: {0}" -> UiText.text(R.string.report_sat_most_of_this_window_0)
        "  · {0}  {1}  dwell {2}" -> UiText.text(R.string.report_0_1_dwell_2)
        "  · None." -> UiText.text(R.string.report_none)
        "First seen in this window: {0} (loudest 8 below)" -> UiText.text(R.string.report_first_seen_in_this_window_0_loudest_8_below)
        "No extra flags. Signature hits, Extra attention, and tracking callouts already cover named pattern matches." -> UiText.text(R.string.report_no_extra_flags_signature_hits_extra_attention_and_tracking_callou)
        "GPS tagging off — no path" -> UiText.text(R.string.report_gps_tagging_off_no_path)
        "GPS tagging on, fewer than 2 fixes in this window" -> UiText.text(R.string.report_gps_tagging_on_fewer_than_2_fixes_in_this_window)
        "traveled {0} along path · span {1} · {2} fixes" -> UiText.text(R.string.report_traveled_0_along_path_span_1_2_fixes)
        "off" -> UiText.text(R.string.report_off)
        "Executive summary" -> UiText.text(R.string.report_executive_summary)
        "Where you were" -> UiText.text(R.string.report_where_you_were)
        "Aircraft" -> UiText.text(R.string.report_aircraft)
        "Observer notes" -> UiText.text(R.string.report_observer_notes)
        "Tracking assessment" -> UiText.text(R.string.report_tracking_assessment)
        "Possible trackers with you" -> UiText.text(R.string.report_possible_trackers_with_you)
        "Finder tags (AirTag / Find My, SmartTag, Tile, Chipolo, Pebblebee) and loud pocket Apple BLE. " -> UiText.text(R.string.report_finder_tags_airtag_find_my_smarttag_tile_chipolo_pebblebee_and_lo)
        "These radios stayed with your GPS path for this sit. " -> UiText.text(R.string.report_these_radios_stayed_with_your_gps_path_for_this_sit)
        "Fieldwatch cannot tell your own tag or phone from a tracker planted in the car, bag, or on you before you started. " -> UiText.text(R.string.report_fieldwatch_cannot_tell_your_own_tag_or_phone_from_a_tracker_plant)
        "Account for each MAC. Not a finding and not identity." -> UiText.text(R.string.report_account_for_each_mac_not_a_finding_and_not_identity)
        "Possible tail" -> UiText.text(R.string.report_possible_tail)
        "Finder tags that were not heard when this sit started, then stayed with your path. " -> UiText.text(R.string.report_finder_tags_that_were_not_heard_when_this_sit_started_then_stayed)
        "That can mean someone started following you (their phone or tag), or a device was added during the trip. " -> UiText.text(R.string.report_that_can_mean_someone_started_following_you_their_phone_or_tag_or)
        "Not a finding and not identity." -> UiText.text(R.string.report_not_a_finding_and_not_identity)
        "Retail beacons with you" -> UiText.text(R.string.report_retail_beacons_with_you)
        "iBeacon / Minew / Estimote / Kontakt.io / Target Atrius basket radios that stayed with your GPS path. " -> UiText.text(R.string.report_ibeacon_minew_estimote_kontakt_io_target_atrius_basket_radios_tha)
        "Location beacons are usually fixtures in a store or venue — they do not typically move with you. " -> UiText.text(R.string.report_location_beacons_are_usually_fixtures_in_a_store_or_venue_they_do)
        "If one did, account for it (a Target basket you pushed, your own test tag, a badge, or a short path that still overlaps a fixture). " -> UiText.text(R.string.report_if_one_did_account_for_it_a_target_basket_you_pushed_your_own_tes)
        "Not the same as a Find My tail. Not a finding and not identity." -> UiText.text(R.string.report_not_the_same_as_a_find_my_tail_not_a_finding_and_not_identity)
        "Wearables with you" -> UiText.text(R.string.report_wearables_with_you)
        "Garmin / Fitbit / Oura radios that stayed with your GPS path. " -> UiText.text(R.string.report_garmin_fitbit_oura_radios_that_stayed_with_your_gps_path)
        "Watches and rings usually move with the person wearing them — often your own kit or someone walking with you. " -> UiText.text(R.string.report_watches_and_rings_usually_move_with_the_person_wearing_them_often)
        "They are not typically planted trackers. Account for each MAC. Not a finding and not identity." -> UiText.text(R.string.report_they_are_not_typically_planted_trackers_account_for_each_mac_not_)
        "Environment" -> UiText.text(R.string.report_environment)
        "Networks (Wi-Fi access points)" -> UiText.text(R.string.report_networks_wi_fi_access_points)
        "Bluetooth LE" -> UiText.text(R.string.report_bluetooth_le)
        "Signature hits" -> UiText.text(R.string.report_signature_hits)
        "Persistence" -> UiText.text(R.string.report_persistence)
        "Extra attention" -> UiText.text(R.string.report_extra_attention)
        "Pattern match, not identity, not a skimmer detector, not a safety finding." -> UiText.text(R.string.report_pattern_match_not_identity_not_a_skimmer_detector_not_a_safety_fi)
        "  · {0}  {1}  {2} dBm  [{3}]" -> UiText.text(R.string.report_0_1_2_dbm_3)
        "Anomalies" -> UiText.text(R.string.report_anomalies)
        "Recommended actions" -> UiText.text(R.string.report_recommended_actions)
        "sit {0} ({1} → {2} UTC)" -> UiText.text(R.string.report_sit_0_1_2_utc)
        "last 15 minutes ({0} → {1} UTC)" -> UiText.text(R.string.report_last_15_minutes_0_1_utc)
        "FIELDWATCH SIT — {0}" -> UiText.text(R.string.report_fieldwatch_sit_0)
        "FIELDWATCH FIELD DEBRIEF" -> UiText.text(R.string.report_fieldwatch_field_debrief)
        "Generated" -> UiText.text(R.string.report_generated)
        "{0} UTC" -> UiText.text(R.string.report_0_utc)
        "Sit" -> UiText.text(R.string.report_sit)
        "Window" -> UiText.text(R.string.report_window)
        "Radios" -> UiText.text(R.string.report_radios)
        "Tool" -> UiText.text(R.string.report_tool)
        "Fieldwatch (app.fieldwatch) · stock Android · receive-only Wi-Fi AP + BLE advertiser" -> UiText.text(R.string.report_fieldwatch_app_fieldwatch_stock_android_receive_only_wi_fi_ap_ble)
        "Scan" -> UiText.text(R.string.report_scan)
        "{0} · stale {1}s · brief hold {2}s" -> UiText.text(R.string.report_0_stale_1_s_brief_hold_2_s)
        "GPS tag" -> UiText.text(R.string.report_gps_tag)
        "on" -> UiText.text(R.string.report_on)
        "Distance" -> UiText.text(R.string.report_distance)
        "Places" -> UiText.text(R.string.report_places)
        "Classification" -> UiText.text(R.string.report_classification)
        "Operationally sensitive — neighbor SSIDs, MACs, operator GPS, advertised aircraft track" -> UiText.text(R.string.report_operationally_sensitive_neighbor_ssids_macs_operator_gps_advertis)
        "Operationally sensitive — neighbor SSIDs, MACs, operator GPS" -> UiText.text(R.string.report_operationally_sensitive_neighbor_ssids_macs_operator_gps)
        "{0}  {1}  {2} dBm" -> UiText.text(R.string.report_0_1_2_dbm_81)
        "SIT" -> UiText.text(R.string.report_sit_82)
        "FIELD DEBRIEF" -> UiText.text(R.string.report_field_debrief)
        "Sit — {0}" -> UiText.text(R.string.report_sit_0)
        "Field debrief" -> UiText.text(R.string.report_field_debrief_85)
        "Last 15 minutes" -> UiText.text(R.string.report_last_15_minutes)
        "OPERATOR PATH" -> UiText.text(R.string.report_operator_path)
        "North-up. Line is this phone ({0}). A MAC alert or a signature alert is drawn once. A decoded latitude and longitude is the last advertised position. Anything else is the strongest hear. A number is that place (Path key)." -> UiText.text(R.string.report_north_up_line_is_this_phone_0_a_mac_alert_or_a_signature_alert_is)
        "## Where you were (operator GPS)" -> UiText.text(R.string.report_where_you_were_operator_gps)
        "- Tag detections with GPS: {0}." -> UiText.text(R.string.report_tag_detections_with_gps_0)
        "- Online place names: " -> UiText.text(R.string.report_online_place_names)
        "off (Settings → Online place names in Debrief). No reverse-geocode this export." -> UiText.text(R.string.report_off_settings_online_place_names_in_debrief_no_reverse_geocode_thi)
        "- Following test: insufficient movement (need ~45 m span). Do not infer a tail." -> UiText.text(R.string.report_following_test_insufficient_movement_need_45_m_span_do_not_infer_)
        "## GPS co-travel" -> UiText.text(R.string.report_gps_co_travel)
        "Only radios that stayed with the operator path are listed. " -> UiText.text(R.string.report_only_radios_that_stayed_with_the_operator_path_are_listed)
        "House tags and other radios the operator only passed are omitted — they are not tracking. " -> UiText.text(R.string.report_house_tags_and_other_radios_the_operator_only_passed_are_omitted_)
        "Not identity. Find My MAC rotation will not stitch a tail that changes address. " -> UiText.text(R.string.report_not_identity_find_my_mac_rotation_will_not_stitch_a_tail_that_cha)
        "Possible tail extra gates (walks): trail covers ≥ half the operator path, " -> UiText.text(R.string.report_possible_tail_extra_gates_walks_trail_covers_half_the_operator_pa)
        "≥ 2/3 of GPS stamps at −75 dBm or louder, last stamp not 12 dB below loudest. " -> UiText.text(R.string.report_2_3_of_gps_stamps_at_75_dbm_or_louder_last_stamp_not_12_db_below_)
        "Fail any one → omit (pass-by), not a tail. " -> UiText.text(R.string.report_fail_any_one_omit_pass_by_not_a_tail)
        "Finder tags (AirTag / SmartTag / Tile / Chipolo / Pebblebee / Find My / loud pocket Apple) " -> UiText.text(R.string.report_finder_tags_airtag_smarttag_tile_chipolo_pebblebee_find_my_loud_p)
        "are the tracking test. Retail beacons and wearables that co-travel are listed separately — " -> UiText.text(R.string.report_are_the_tracking_test_retail_beacons_and_wearables_that_co_travel)
        "they do not typically move with you (beacons) or are usually own kit (wearables)." -> UiText.text(R.string.report_they_do_not_typically_move_with_you_beacons_or_are_usually_own_ki)
        "- None stayed with the path." -> UiText.text(R.string.report_none_stayed_with_the_path)
        "- {0}  {1}  {2}  RSSI {3} dBm " -> UiText.text(R.string.report_0_1_2_rssi_3_dbm)
        "(min {0} / max {1})  trail {2} fixes, span {3} m" -> UiText.text(R.string.report_min_0_max_1_trail_2_fixes_span_3_m)
        "Possible trackers with you (finder tags, whole sit — yours or planted before you started)" -> UiText.text(R.string.report_possible_trackers_with_you_finder_tags_whole_sit_yours_or_planted)
        "Possible tail (finder tags, first heard after this sit started, then stayed)" -> UiText.text(R.string.report_possible_tail_finder_tags_first_heard_after_this_sit_started_then)
        "Retail beacons with you (iBeacon / Minew / Estimote / Kontakt.io / Target Atrius basket — fixtures; a pushed cart will co-travel)" -> UiText.text(R.string.report_retail_beacons_with_you_ibeacon_minew_estimote_kontakt_io_target_)
        "Wearables with you (Garmin / Fitbit / Oura — usually own kit or a companion)" -> UiText.text(R.string.report_wearables_with_you_garmin_fitbit_oura_usually_own_kit_or_a_compan)
        "Operator GPS path too short ({0} m) to test following." -> UiText.text(R.string.report_operator_gps_path_too_short_0_m_to_test_following)
        "Heard, but not at two GPS points. Cannot test co-travel." -> UiText.text(R.string.report_heard_but_not_at_two_gps_points_cannot_test_co_travel)
        "Heard along {0} m of your {1} m path and still loud ({2} dBm). " -> UiText.text(R.string.report_heard_along_0_m_of_your_1_m_path_and_still_loud_2_dbm)
        "Heard near one place ({0} m span) while you moved {1} m. Looks stationary — you walked away from it." -> UiText.text(R.string.report_heard_near_one_place_0_m_span_while_you_moved_1_m_looks_stationar)
        "Moved {0} m with you, already on the air when this 15-minute window opened, strong ({1} dBm). " -> UiText.text(R.string.report_moved_0_m_with_you_already_on_the_air_when_this_15_minute_window_)
        "GPS samples span {0} m along your path ({1} fixes). Already on the air when this window opened and still here. " -> UiText.text(R.string.report_gps_samples_span_0_m_along_your_path_1_fixes_already_on_the_air_w)
        "Heard along {0} m ({1} GPS stamps) but did not stay loud on you. Neighborhood arc / pass-by, not a tail." -> UiText.text(R.string.report_heard_along_0_m_1_gps_stamps_but_did_not_stay_loud_on_you_neighbo)
        "Stayed loud with you the whole sit ({0} to {1} dBm, {2} GPS stamps). " -> UiText.text(R.string.report_stayed_loud_with_you_the_whole_sit_0_to_1_dbm_2_gps_stamps)
        "Decoded: {0}." -> UiText.text(R.string.report_decoded_0)
        "With you the whole sit — yours or planted before you started. Account for it." -> UiText.text(R.string.report_with_you_the_whole_sit_yours_or_planted_before_you_started_accoun)
        "Location beacons do not typically move with you. Account for it (own test tag, badge, or a short overlap with a fixture)." -> UiText.text(R.string.report_location_beacons_do_not_typically_move_with_you_account_for_it_ow)
        "Typical of a watch or ring you or a companion are wearing. Not typically a planted tracker." -> UiText.text(R.string.report_typical_of_a_watch_or_ring_you_or_a_companion_are_wearing_not_typ)
        "{0} Find My / iPhone addresses rotate; this MAC is this session." -> UiText.text(R.string.report_0_find_my_iphone_addresses_rotate_this_mac_is_this_session)
        "Appeared after the sit started, but last GPS stamp was {0} dBm after a loudest of {1} dBm (−{2} dB). Looks like you walked away from a fixture, not a tail." -> UiText.text(R.string.report_appeared_after_the_sit_started_but_last_gps_stamp_was_0_dbm_after)
        "Appeared after the sit started and GPS span was {0} m, but only {1}/{2} stamps were loud (−75 dBm+). Looks like a pass-by, not a tail." -> UiText.text(R.string.report_appeared_after_the_sit_started_and_gps_span_was_0_m_but_only_1_2_)
        "Appeared after the sit started, but was only heard along {0} m of your {1} m path ({2}%). Neighborhood arc / pass-by, not a tail." -> UiText.text(R.string.report_appeared_after_the_sit_started_but_was_only_heard_along_0_m_of_yo)
        "Appeared after the sit started, then stayed loud with you across {0} m " -> UiText.text(R.string.report_appeared_after_the_sit_started_then_stayed_loud_with_you_across_0)
        "({0} m of your {1} m path, {2}%; " -> UiText.text(R.string.report_0_m_of_your_1_m_path_2)
        "{0}/{1} GPS stamps ≥ −75 dBm). " -> UiText.text(R.string.report_0_1_gps_stamps_75_dbm)
        "Treat as a possible tail until you visually account for it." -> UiText.text(R.string.report_treat_as_a_possible_tail_until_you_visually_account_for_it)
        "Unusual for a retail/location beacon — they do not typically move with you. Account for it; not the same as a Find My tail." -> UiText.text(R.string.report_unusual_for_a_retail_location_beacon_they_do_not_typically_move_w)
        "Typical of a watch that joined the sit (you put it on, or someone walking with you). Not typically a planted tracker." -> UiText.text(R.string.report_typical_of_a_watch_that_joined_the_sit_you_put_it_on_or_someone_w)
        "In sit {0}" -> UiText.text(R.string.report_in_sit_0)
        "In the last 15 minutes" -> UiText.text(R.string.report_in_the_last_15_minutes)
        "{0} Fieldwatch heard {1} Wi-Fi access points and {2} BLE advertisers" -> UiText.text(R.string.report_0_fieldwatch_heard_1_wi_fi_access_points_and_2_ble_advertisers)
        " ({0} signature-matched, {1} hidden SSIDs, {2} randomized BLE). " -> UiText.text(R.string.report_0_signature_matched_1_hidden_ssids_2_randomized_ble)
        "Overall distance traveled: {0} along the GPS path (straight-line span {1}). " -> UiText.text(R.string.report_overall_distance_traveled_0_along_the_gps_path_straight_line_span)
        "Stops / area: {0}. " -> UiText.text(R.string.report_stops_area_0)
        "TRACKING NOTE. " -> UiText.text(R.string.report_tracking_note)
        "{0} finder tag(s) with you the whole sit (your kit or planted before you started): " -> UiText.text(R.string.report_0_finder_tag_s_with_you_the_whole_sit_your_kit_or_planted_before_)
        "{0} possible tail(s) first heard after this sit started: " -> UiText.text(R.string.report_0_possible_tail_s_first_heard_after_this_sit_started)
        "Account for every MAC — Fieldwatch cannot tell yours from a plant. " -> UiText.text(R.string.report_account_for_every_mac_fieldwatch_cannot_tell_yours_from_a_plant)
        "GPS tagging is off, so a following test was not performed. Enable “Tag detections with GPS” and walk to test. " -> UiText.text(R.string.report_gps_tagging_is_off_so_a_following_test_was_not_performed_enable_t)
        "GPS displacement was only {0} m — too short to test whether a tracker is following. Walk farther with tagging on. " -> UiText.text(R.string.report_gps_displacement_was_only_0_m_too_short_to_test_whether_a_tracker)
        "No finder tag clearly stayed with the GPS path in this window. " -> UiText.text(R.string.report_no_finder_tag_clearly_stayed_with_the_gps_path_in_this_window)
        "Retail beacon(s) also stayed with the path (unusual — fixtures do not typically move with you): " -> UiText.text(R.string.report_retail_beacon_s_also_stayed_with_the_path_unusual_fixtures_do_not)
        "Wearable(s) stayed with the path (usually your watch/ring or a companion): " -> UiText.text(R.string.report_wearable_s_stayed_with_the_path_usually_your_watch_ring_or_a_comp)
        "GPS tagging is OFF. Fieldwatch cannot test whether a radio moved with you." -> UiText.text(R.string.report_gps_tagging_is_off_fieldwatch_cannot_test_whether_a_radio_moved_w)
        "Turn on Settings → Tag detections with GPS, walk or drive 50+ m, then run Debrief again." -> UiText.text(R.string.report_turn_on_settings_tag_detections_with_gps_walk_or_drive_50_m_then_)
        "Overall distance traveled: {0} along the GPS path ({1} samples). Straight-line span {2}." -> UiText.text(R.string.report_overall_distance_traveled_0_along_the_gps_path_1_samples_straight)
        "Co-travel is split by class: finder tags (AirTag / Find My, SmartTag, Tile, Chipolo, Pebblebee, loud pocket Apple), retail beacons (iBeacon, Minew, Estimote, Kontakt.io, Target Atrius basket), and wearables (Garmin, Fitbit, Oura)." -> UiText.text(R.string.report_co_travel_is_split_by_class_finder_tags_airtag_find_my_smarttag_t)
        "Insufficient movement to distinguish a radio that stayed with you from one you passed. Walk or drive farther and re-run." -> UiText.text(R.string.report_insufficient_movement_to_distinguish_a_radio_that_stayed_with_you)
        "No finder tag, retail beacon, or wearable stayed with you. House tags and other radios you only passed are not listed." -> UiText.text(R.string.report_no_finder_tag_retail_beacon_or_wearable_stayed_with_you_house_tag)
        "Callouts below are only radios that stayed with the path. Radios you passed (store fixtures, house tags) are omitted." -> UiText.text(R.string.report_callouts_below_are_only_radios_that_stayed_with_the_path_radios_y)
        "Your captions on radios heard in this window. Same KIND+MAC as Named radios. Not catalog Notes." -> UiText.text(R.string.report_your_captions_on_radios_heard_in_this_window_same_kind_mac_as_nam)
        "  · {0}  {1}  {2}  {3} dBm" -> UiText.text(R.string.report_0_1_2_3_dbm)
        "    {0}  {1}  RSSI {2} dBm (min {3} / max {4})" -> UiText.text(R.string.report_0_1_rssi_2_dbm_min_3_max_4)
        "Phone GPS at hear-time, not the other radio’s location and not a camera pole. Stays are clusters within about 40 m; hops between them are transit. Coordinates are not repeated on every Wi-Fi/BLE line." -> UiText.text(R.string.report_phone_gps_at_hear_time_not_the_other_radio_s_location_and_not_a_c)
        "GPS tagging is OFF. Turn on Settings → Tag detections with GPS to record where you were when radios were heard." -> UiText.text(R.string.report_gps_tagging_is_off_turn_on_settings_tag_detections_with_gps_to_re)
        "GPS tagging is on, but this window has no fixes yet." -> UiText.text(R.string.report_gps_tagging_is_on_but_this_window_has_no_fixes_yet)
        "Overall: {0} along-track, span {1}, {2} fixes." -> UiText.text(R.string.report_overall_0_along_track_span_1_2_fixes)
        "Street names are approximate. Do not treat a street as the location of a matched camera or tag." -> UiText.text(R.string.report_street_names_are_approximate_do_not_treat_a_street_as_the_locatio)
        "No path legs." -> UiText.text(R.string.report_no_path_legs)
        "Stops: " -> UiText.text(R.string.report_stops)
        "{0}. Stay  {1}–{2} UTC  ({3})" -> UiText.text(R.string.report_0_stay_1_2_utc_3)
        "   Heard here: {0} AP(s), {1} BLE" -> UiText.text(R.string.report_heard_here_0_ap_s_1_ble)
        "   · {0}  {1}  {2} dBm" -> UiText.text(R.string.report_0_1_2_dbm_167)
        "   · No GPS-stamped radios tied to this stay (tagging may have started after they were first heard)." -> UiText.text(R.string.report_no_gps_stamped_radios_tied_to_this_stay_tagging_may_have_started_)
        "{0}. Transit  {1}–{2} UTC  " -> UiText.text(R.string.report_0_transit_1_2_utc)
        "{0} along track" -> UiText.text(R.string.report_0_along_track)
        "One stay — you did not move far enough in this window to split locations." -> UiText.text(R.string.report_one_stay_you_did_not_move_far_enough_in_this_window_to_split_loca)
        "In motion (walk/vehicle) through mixed RF." -> UiText.text(R.string.report_in_motion_walk_vehicle_through_mixed_rf)
        "Likely a dwelling or small office — few sitting APs, limited BLE." -> UiText.text(R.string.report_likely_a_dwelling_or_small_office_few_sitting_aps_limited_ble)
        "Dense public / retail / street: many APs and phone-like randomized BLE." -> UiText.text(R.string.report_dense_public_retail_street_many_aps_and_phone_like_randomized_ble)
        "Likely a building with standing infrastructure APs plus patrons." -> UiText.text(R.string.report_likely_a_building_with_standing_infrastructure_aps_plus_patrons)
        "Mixed or under-sampled environment." -> UiText.text(R.string.report_mixed_or_under_sampled_environment)
        "{0}  ({1} APs, {2} BLE, {3} persistent APs, traveled {4}, span {5}.)" -> UiText.text(R.string.report_0_1_aps_2_ble_3_persistent_aps_traveled_4_span_5)
        "  ch " -> UiText.text(R.string.report_ch)
        "  hidden" -> UiText.text(R.string.report_hidden)
        "  dwell " -> UiText.text(R.string.report_dwell)
        "Google Fast Pair in pairing mode: " -> UiText.text(R.string.report_google_fast_pair_in_pairing_mode)
        "Very strong unnamed radios (≥ −50 dBm): " -> UiText.text(R.string.report_very_strong_unnamed_radios_50_dbm)
        "{0} {1} dBm" -> UiText.text(R.string.report_0_1_dbm)
        "High randomized BLE ({0}) — typical of phones, not a tracking finding." -> UiText.text(R.string.report_high_randomized_ble_0_typical_of_phones_not_a_tracking_finding)
        "A passive observer with the same radios would see {0} named/hidden APs " -> UiText.text(R.string.report_a_passive_observer_with_the_same_radios_would_see_0_named_hidden_)
        "and {0} BLE advertisers ({1} randomized). " -> UiText.text(R.string.report_and_0_ble_advertisers_1_randomized)
        "Hidden SSIDs still beacon and identify the AP by BSSID. " -> UiText.text(R.string.report_hidden_ssids_still_beacon_and_identify_the_ap_by_bssid)
        "This debrief includes operator GPS samples used for distance and the following test. " -> UiText.text(R.string.report_this_debrief_includes_operator_gps_samples_used_for_distance_and_)
        "This debrief includes advertised aircraft positions from radios that broadcast a latitude and longitude. " -> UiText.text(R.string.report_this_debrief_includes_advertised_aircraft_positions_from_radios_t)
        "Street names came from the phone’s system geocoder while online. " -> UiText.text(R.string.report_street_names_came_from_the_phone_s_system_geocoder_while_online)
        "Do not share this file off-device without redaction." -> UiText.text(R.string.report_do_not_share_this_file_off_device_without_redaction)
        "Possible tail (appeared after this sit started): {0}. Pause Live, open detail, note RSSI while you walk a dog-leg. Do not disable someone else’s tag." -> UiText.text(R.string.report_possible_tail_appeared_after_this_sit_started_0_pause_live_open_d)
        "Possible trackers with you: {0}. " -> UiText.text(R.string.report_possible_trackers_with_you_0)
        "Could be yours or planted in the car/bag/on you before you started. Account for each MAC — do not dismiss as yours." -> UiText.text(R.string.report_could_be_yours_or_planted_in_the_car_bag_on_you_before_you_starte)
        "Retail beacons with you (unusual — fixtures do not typically move with you): " -> UiText.text(R.string.report_retail_beacons_with_you_unusual_fixtures_do_not_typically_move_wi)
        ". Account for a test tag or badge before treating it as a follower." -> UiText.text(R.string.report_account_for_a_test_tag_or_badge_before_treating_it_as_a_follower)
        "Wearables with you (usually own kit or a companion): " -> UiText.text(R.string.report_wearables_with_you_usually_own_kit_or_a_companion)
        "Enable Tag detections with GPS and walk 50+ m, then run Debrief again for a following test." -> UiText.text(R.string.report_enable_tag_detections_with_gps_and_walk_50_m_then_run_debrief_aga)
        "Walk farther (50+ m) with GPS tagging on, then re-run Debrief." -> UiText.text(R.string.report_walk_farther_50_m_with_gps_tagging_on_then_re_run_debrief)
        "Use Live → Pause to inspect a busy list. Watch tracker signatures if this sit was noisy." -> UiText.text(R.string.report_use_live_pause_to_inspect_a_busy_list_watch_tracker_signatures_if)
        "Station-side Wi-Fi (probes/clients) still needs a dedicated sniffer — Fieldwatch cannot see them." -> UiText.text(R.string.report_station_side_wi_fi_probes_clients_still_needs_a_dedicated_sniffer)
        " Retail beacon(s) also with the path (unusual): " -> UiText.text(R.string.report_retail_beacon_s_also_with_the_path_unusual)
        " Wearable(s) with the path (usually own kit): " -> UiText.text(R.string.report_wearable_s_with_the_path_usually_own_kit)
        "Possible tail (appeared after sit started): {0}. " -> UiText.text(R.string.report_possible_tail_appeared_after_sit_started_0)
        "Also finder tags with you (yours or planted before): {0}. Account for every MAC." -> UiText.text(R.string.report_also_finder_tags_with_you_yours_or_planted_before_0_account_for_e)
        "Possible tail (appeared after this sit started): {0}. Account for it on the person/vehicle." -> UiText.text(R.string.report_possible_tail_appeared_after_this_sit_started_0_account_for_it_on)
        "Turn on GPS tagging and walk before you can test whether a tracker is following you." -> UiText.text(R.string.report_turn_on_gps_tagging_and_walk_before_you_can_test_whether_a_tracke)
        "Not enough GPS movement ({0} m) to test following; walk and re-run Debrief." -> UiText.text(R.string.report_not_enough_gps_movement_0_m_to_test_following_walk_and_re_run_deb)
        "Finder tags with you (yours or planted before you started): {0}. No new arrival this window. Account for each MAC — do not dismiss as yours." -> UiText.text(R.string.report_finder_tags_with_you_yours_or_planted_before_you_started_0_no_new)
        "No finder tag stayed with the path." -> UiText.text(R.string.report_no_finder_tag_stayed_with_the_path)
        "No signature hits and no GPS co-travel of trackers in this 15-minute window." -> UiText.text(R.string.report_no_signature_hits_and_no_gps_co_travel_of_trackers_in_this_15_min)
        "No finder tag, retail beacon, or wearable clearly stayed with your GPS path in this window." -> UiText.text(R.string.report_no_finder_tag_retail_beacon_or_wearable_clearly_stayed_with_your_)
        " and {0} more" -> UiText.text(R.string.report_and_0_more)
        " Advertised position: {0}{1}." -> UiText.text(R.string.report_advertised_position_0_1)
        "{0}h{1}m" -> UiText.text(R.string.report_0_h_1_m)
        "{0}m{1}s" -> UiText.text(R.string.report_0_m_1_s)
        "You are a field RF analyst for the operator who collected this sit. Fieldwatch is a stock-Android, receive-only Wi-Fi access-point + BLE-advertiser listener." -> UiText.text(R.string.report_you_are_a_field_rf_analyst_for_the_operator_who_collected_this_si)
        "The **onboard Debrief** (verbatim below) already tabulated the sit: counts, Where you were, tracking callouts, inventories, Extra attention, takeaway. **Do not rewrite that report. Do not reprint inventories or stay lists.** Your job is an addendum the phone cannot write: rates, competing hypotheses, and a stress-test of the onboard tracking callouts." -> UiText.text(R.string.report_the_onboard_debrief_verbatim_below_already_tabulated_the_sit_coun)
        "Constraints you must respect:" -> UiText.text(R.string.report_constraints_you_must_respect)
        "- Hear-only. Wi-Fi rows are access points only. BLE rows are advertisers. Kind + MAC. BLE rotation is a new row and will not stitch." -> UiText.text(R.string.report_hear_only_wi_fi_rows_are_access_points_only_ble_rows_are_advertis)
        "- Signature / OUI / company matches are hypotheses, not identity, not a person or vehicle." -> UiText.text(R.string.report_signature_oui_company_matches_are_hypotheses_not_identity_not_a_p)
        "- GPS stamps (if present) are this phone at hear-time, not the other radio. Do not place a camera or tag at the GPS pin." -> UiText.text(R.string.report_gps_stamps_if_present_are_this_phone_at_hear_time_not_the_other_r)
        "- Place names (if present) are system reverse-geocode of those stamps." -> UiText.text(R.string.report_place_names_if_present_are_system_reverse_geocode_of_those_stamps)
        "- RSSI is loudness at the phone, not meters." -> UiText.text(R.string.report_rssi_is_loudness_at_the_phone_not_meters)
        "- Live RAM cap is about 400 radios; unnamed BLE evicts after ~3 min. A named sit keeps more. This is not a complete capture." -> UiText.text(R.string.report_live_ram_cap_is_about_400_radios_unnamed_ble_evicts_after_3_min_a)
        "- Do not claim a tracker is following unless the onboard GPS co-travel section supports it. A radio with you the whole sit is not automatically yours — it may be planted. Do not dismiss it. Do not invent a tail the onboard test did not flag. Do not treat a retail beacon as a Find My tail." -> UiText.text(R.string.report_do_not_claim_a_tracker_is_following_unless_the_onboard_gps_co_tra)
        "- A decoded live value on a tracking row is catalog text for that advertisement. Quote the catalog sentence when the onboard report includes one. Do not stitch that value onto a different MAC." -> UiText.text(R.string.report_a_decoded_live_value_on_a_tracking_row_is_catalog_text_for_that_a)
        "- An aircraft block and an amber track are positions the radio advertised. Trails with the same UAS id are one aircraft. They are not this phone's GPS and they are not a finding that the aircraft followed the operator." -> UiText.text(R.string.report_an_aircraft_block_and_an_amber_track_are_positions_the_radio_adve)
        "- Do not give safety advice. Do not tell the operator they are safe or in danger." -> UiText.text(R.string.report_do_not_give_safety_advice_do_not_tell_the_operator_they_are_safe_)
        "- Treat this paste as operationally sensitive." -> UiText.text(R.string.report_treat_this_paste_as_operationally_sensitive)
        "## Your output (required — this is the addendum the operator reads)" -> UiText.text(R.string.report_your_output_required_this_is_the_addendum_the_operator_reads)
        "Write complete sentences. Headings as below. Short bullets only for Extra attention and tracking rows from the working table. No markdown tables. No code fences. No dump of the onboard inventories." -> UiText.text(R.string.report_write_complete_sentences_headings_as_below_short_bullets_only_for)
        "1. **Disclaimer** — Repeat the experimental-use disclaimer first." -> UiText.text(R.string.report_1_disclaimer_repeat_the_experimental_use_disclaimer_first)
        "2. **What the onboard Debrief already established** — 3–5 sentences. Counts, distance, tracking callouts, Extra attention hits, Observer notes if any. Do not reprint inventories." -> UiText.text(R.string.report_2_what_the_onboard_debrief_already_established_3_5_sentences_coun)
        "3. **What the numbers add** — 5- vs 15-minute counts, RSSI bands, RAND BLE percent, arrivals per minute, persistent vs gone, signature-family mix. Say street vs dwelling vs retail vs vehicle, and 5-minute vs 15-minute change (denser, quieter, stable). Confidence. If GPS ran, path length/span from the working table — do not pin a radio to a stay." -> UiText.text(R.string.report_3_what_the_numbers_add_5_vs_15_minute_counts_rssi_bands_rand_ble_)
        "4. **Extra attention and tracking callouts** — Full identifiers from the working table (complete MAC, name, RSSI min/max, signatures, dwell). Stress-test onboard Possible trackers with you / Possible tail / Retail beacons / Wearables. Agree, qualify, or say the data are too thin. Pattern match, not identity. If none, say none." -> UiText.text(R.string.report_4_extra_attention_and_tracking_callouts_full_identifiers_from_the)
        "5. **What another sit or Hunt would shrink** — Concrete in-app next steps only (Hunt on one Extra attention row, a longer GPS path, Compare sits, Filters). No safety advice. No “call the police.”" -> UiText.text(R.string.report_5_what_another_sit_or_hunt_would_shrink_concrete_in_app_next_step)
        "**Takeaway (required, last line).** One sentence starting with `Takeaway:` that adds *one number the onboard takeaway does not already say* (a rate, RAND percent, 5- vs 15-minute change, path span). Not a moral. Not a threat level." -> UiText.text(R.string.report_takeaway_required_last_line_one_sentence_starting_with_takeaway_t)
        "## Collection context" -> UiText.text(R.string.report_collection_context)
        "- Tool: Fieldwatch (app.fieldwatch), receive-only, no association / injection / cloud." -> UiText.text(R.string.report_tool_fieldwatch_app_fieldwatch_receive_only_no_association_inject)
        "- Window: sit **{0}** ({1} → {2} UTC), with a 5-minute recent slice." -> UiText.text(R.string.report_window_sit_0_1_2_utc_with_a_5_minute_recent_slice)
        "- Window: last **15 minutes** ({0} → {1} UTC), with a **5-minute** recent slice." -> UiText.text(R.string.report_window_last_15_minutes_0_1_utc_with_a_5_minute_recent_slice)
        "- Scan intensity: {0}. Stale after {1}s." -> UiText.text(R.string.report_scan_intensity_0_stale_after_1_s)
        "- Location tags: {0}. Online place names: {1}." -> UiText.text(R.string.report_location_tags_0_online_place_names_1)
        "## Onboard Debrief (verbatim — already shown to the operator; do not rewrite)" -> UiText.text(R.string.report_onboard_debrief_verbatim_already_shown_to_the_operator_do_not_rew)
        "## Working data (for the addendum — do not copy rosters into the answer)" -> UiText.text(R.string.report_working_data_for_the_addendum_do_not_copy_rosters_into_the_answer)
        "15 min: Wi-Fi {0}  BLE {1}  signed {2}  hidden SSIDs {3}  " -> UiText.text(R.string.report_15_min_wi_fi_0_ble_1_signed_2_hidden_ssids_3)
        "RAND BLE {0}/{1} ({2}%)  " -> UiText.text(R.string.report_rand_ble_0_1_2)
        "first-seen {0} ({1}/min)  persistent {2}  gone/quiet {3}" -> UiText.text(R.string.report_first_seen_0_1_min_persistent_2_gone_quiet_3)
        "5 min: Wi-Fi {0}  BLE {1}  " -> UiText.text(R.string.report_5_min_wi_fi_0_ble_1)
        "signed {0}  first-seen {1}" -> UiText.text(R.string.report_signed_0_first_seen_1)
        "BLE RSSI (n={0}): ≥−50 {1}  −51..−70 {2}  " -> UiText.text(R.string.report_ble_rssi_n_0_50_1_51_70_2)
        "Wi-Fi RSSI (n={0}): ≥−50 {1}  −51..−70 {2}  " -> UiText.text(R.string.report_wi_fi_rssi_n_0_50_1_51_70_2)
        "Signature families: none." -> UiText.text(R.string.report_signature_families_none)
        "Signature families (count): " -> UiText.text(R.string.report_signature_families_count)
        "GPS path: tagging {0}  " -> UiText.text(R.string.report_gps_path_tagging_0)
        "fixes {0}  length {1} m  span {2} m  " -> UiText.text(R.string.report_fixes_0_length_1_m_span_2_m)
        "places {0}" -> UiText.text(R.string.report_places_0)
        "Extra attention:" -> UiText.text(R.string.report_extra_attention_259)
        "- None." -> UiText.text(R.string.report_none_260)
        "Observer notes:" -> UiText.text(R.string.report_observer_notes_261)
        "Finder-tag-like radios (for stress-test of onboard tracking; not a tail list):" -> UiText.text(R.string.report_finder_tag_like_radios_for_stress_test_of_onboard_tracking_not_a_)
        " rssiMin=" -> UiText.text(R.string.report_rssimin)
        " rssiMax=" -> UiText.text(R.string.report_rssimax)
        "## End of working data" -> UiText.text(R.string.report_end_of_working_data)
        "Write the addendum now, following **Your output** at the top. Do not rewrite the onboard Debrief." -> UiText.text(R.string.report_write_the_addendum_now_following_your_output_at_the_top_do_not_re)
        "\n\n[truncated for share-sheet size]\n" -> UiText.text(R.string.report_truncated_for_share_sheet_size)
        "  Observer: " -> UiText.text(R.string.report_observer)
        " rssi=" -> UiText.text(R.string.report_rssi)
        " RAND" -> UiText.text(R.string.report_rand)
        " sig=" -> UiText.text(R.string.report_sig)
        " decoded=" -> UiText.text(R.string.report_decoded)
        " decodeNote=" -> UiText.text(R.string.report_decodenote)
        " dwell=" -> UiText.text(R.string.report_dwell_274)
        "Last 15 minutes is the Live RAM set (about 400 radios). " -> UiText.text(R.string.report_last_15_minutes_is_the_live_ram_set_about_400_radios)
        "A named sit keeps up to {0}. Counts are not the same net." -> UiText.text(R.string.report_a_named_sit_keeps_up_to_0_counts_are_not_the_same_net)
        "Windows" -> UiText.text(R.string.report_windows)
        "This sit" -> UiText.text(R.string.report_this_sit)
        "Second sit" -> UiText.text(R.string.report_second_sit)
        "Radios this phone heard. Kind + MAC. BLE rotation is a new row. Not a radio fix." -> UiText.text(R.string.report_radios_this_phone_heard_kind_mac_ble_rotation_is_a_new_row_not_a_)
        "Only in this sit ({0})" -> UiText.text(R.string.report_only_in_this_sit_0)
        "Only in second sit ({0})" -> UiText.text(R.string.report_only_in_second_sit_0)
        "In both ({0})" -> UiText.text(R.string.report_in_both_0)
        "This radios" -> UiText.text(R.string.report_this_radios)
        "Second radios" -> UiText.text(R.string.report_second_radios)
        "Caps" -> UiText.text(R.string.report_caps)
        "RAM ~400 vs sit {0}" -> UiText.text(R.string.report_ram_400_vs_sit_0)
        "{0} vs {1}" -> UiText.text(R.string.report_0_vs_1)
        "{0} only in this sit · {1} only in the second · {2} in both." -> UiText.text(R.string.report_0_only_in_this_sit_1_only_in_the_second_2_in_both)
        "FIELDWATCH SIT COMPARE" -> UiText.text(R.string.report_fieldwatch_sit_compare)
        "SIT COMPARE" -> UiText.text(R.string.report_sit_compare)
        "Sit compare" -> UiText.text(R.string.report_sit_compare_292)
        "A MAC alert or a signature alert is drawn once. A decoded latitude and longitude is the last advertised position. Anything else is the strongest hear. A number is that place (Path key)." -> UiText.text(R.string.report_a_mac_alert_or_a_signature_alert_is_drawn_once_a_decoded_latitude)
        "Two walks on one north-up frame. Green = this sit. Slate = second sit. {0}" -> UiText.text(R.string.report_two_walks_on_one_north_up_frame_green_this_sit_slate_second_sit_0)
        "North-up. Line is this phone. {0}" -> UiText.text(R.string.report_north_up_line_is_this_phone_0)
        "OPERATOR PATHS" -> UiText.text(R.string.report_operator_paths)
        "last 15 minutes in memory (about 400 radios)" -> UiText.text(R.string.report_last_15_minutes_in_memory_about_400_radios)
        "named window (up to {0})" -> UiText.text(R.string.report_named_window_up_to_0)
        "{0}: {1}\n{2} radios · {3}\n" -> UiText.text(R.string.report_0_1_2_radios_3)
        "Only in this sit." -> UiText.text(R.string.report_only_in_this_sit)
        "Only in second sit." -> UiText.text(R.string.report_only_in_second_sit)
        "(none)" -> UiText.text(R.string.report_none_302)
        "  decoded value changed: " -> UiText.text(R.string.report_decoded_value_changed)
        "  Extra attention" -> UiText.text(R.string.report_extra_attention_304)
        "both" -> UiText.text(R.string.report_both)
        "this sit" -> UiText.text(R.string.report_this_sit_306)
        "second sit" -> UiText.text(R.string.report_second_sit_307)
        "Your captions on radios heard in either window. Same KIND+MAC as Named radios. Not catalog Notes." -> UiText.text(R.string.report_your_captions_on_radios_heard_in_either_window_same_kind_mac_as_n)
        "Only in this sit" -> UiText.text(R.string.report_only_in_this_sit_309)
        "Only in second sit" -> UiText.text(R.string.report_only_in_second_sit_310)
        "You are a field RF analyst for the operator who compared two Fieldwatch sits. Fieldwatch is a stock-Android, receive-only Wi-Fi access-point + BLE-advertiser listener." -> UiText.text(R.string.report_you_are_a_field_rf_analyst_for_the_operator_who_compared_two_fiel)
        "The **onboard Compare** (verbatim below) already split presence: only in this sit, only in the second, in both. **Do not rewrite that report. Do not reprint those lists.** Your job is an addendum the phone cannot write: what kind of change this is, and how much of it is real." -> UiText.text(R.string.report_the_onboard_compare_verbatim_below_already_split_presence_only_in)
        "- Hear-only. Kind + MAC. BLE rotation is a new row and will not stitch." -> UiText.text(R.string.report_hear_only_kind_mac_ble_rotation_is_a_new_row_and_will_not_stitch)
        "- Wi-Fi rows are access points only. Associated clients are invisible." -> UiText.text(R.string.report_wi_fi_rows_are_access_points_only_associated_clients_are_invisibl)
        "- Extra attention / signature matches are hypotheses, not identity, not a person or vehicle." -> UiText.text(R.string.report_extra_attention_signature_matches_are_hypotheses_not_identity_not)
        "- GPS stamps (if present) are this phone at hear-time, not the other radio." -> UiText.text(R.string.report_gps_stamps_if_present_are_this_phone_at_hear_time_not_the_other_r_316)
        "- Last 15 minutes vs a named sit is not the same net (RAM about 400 vs sit {0}). Missing BLE on the RAM side can be eviction, not gone." -> UiText.text(R.string.report_last_15_minutes_vs_a_named_sit_is_not_the_same_net_ram_about_400_)
        "- Presence is not co-travel. Do not invent a tail, a follower, or a camera location." -> UiText.text(R.string.report_presence_is_not_co_travel_do_not_invent_a_tail_a_follower_or_a_ca)
        "- A decoded live value on a row is catalog text for that kind + MAC. If the onboard compare says that value changed, state the change. Do not stitch that value onto a different MAC." -> UiText.text(R.string.report_a_decoded_live_value_on_a_row_is_catalog_text_for_that_kind_mac_i)
        "- An aircraft block is positions the radio advertised, joined by UAS id. If the onboard compare says the status changed, state the change. That track is not this phone's GPS." -> UiText.text(R.string.report_an_aircraft_block_is_positions_the_radio_advertised_joined_by_uas)
        "Write complete sentences. Headings as below. Short bullets only for exclusive Extra attention / Named radios. No markdown tables. No code fences. No dump of the onboard lists." -> UiText.text(R.string.report_write_complete_sentences_headings_as_below_short_bullets_only_for_321)
        "2. **What the onboard compare already established** — 3–5 sentences. Window names, counts, Extra attention exclusives, Observer notes if any. Do not reprint inventories." -> UiText.text(R.string.report_2_what_the_onboard_compare_already_established_3_5_sentences_wind)
        "3. **What the numbers add** — Overlap (both/union as a percent), Wi-Fi vs BLE in each bucket, how much exclusive BLE is RAND. Say whether this looks like fixtures, a different stall/hour, or a cap artifact. Confidence. Use the working table; do not invent rates." -> UiText.text(R.string.report_3_what_the_numbers_add_overlap_both_union_as_a_percent_wi_fi_vs_b)
        "4. **Exclusive Extra attention and Named radios** — Full identifiers from the working table (complete MAC, name, signatures, which window). Pattern match, not identity. If none, say none." -> UiText.text(R.string.report_4_exclusive_extra_attention_and_named_radios_full_identifiers_fro)
        "5. **What another sit or Hunt would shrink** — Concrete in-app next steps only (a third sit at the same stall, Hunt on one exclusive Extra attention row, Filters). No safety advice. No “call the police.”" -> UiText.text(R.string.report_5_what_another_sit_or_hunt_would_shrink_concrete_in_app_next_step_325)
        "**Takeaway (required, last line).** One sentence starting with `Takeaway:` that adds *one number the onboard takeaway does not already say* (overlap percent, exclusive Extra attention count, or RAND fraction of exclusive BLE). Not a moral. Not a threat level." -> UiText.text(R.string.report_takeaway_required_last_line_one_sentence_starting_with_takeaway_t_326)
        "## Onboard Compare (verbatim — already shown to the operator; do not rewrite)" -> UiText.text(R.string.report_onboard_compare_verbatim_already_shown_to_the_operator_do_not_rew)
        "This sit: {0} ({1} radios{2})" -> UiText.text(R.string.report_this_sit_0_1_radios_2)
        "Second sit: {0} ({1} radios{2})" -> UiText.text(R.string.report_second_sit_0_1_radios_2)
        "Only in this sit: {0}  Only in second: {1}  In both: {2}  Union: {3}  Overlap: {4}%" -> UiText.text(R.string.report_only_in_this_sit_0_only_in_second_1_in_both_2_union_3_overlap_4)
        "Only in this sit by radio: Wi-Fi {0}  BLE {1}  RAND BLE {2}" -> UiText.text(R.string.report_only_in_this_sit_by_radio_wi_fi_0_ble_1_rand_ble_2)
        "Only in second sit by radio: Wi-Fi {0}  BLE {1}  RAND BLE {2}" -> UiText.text(R.string.report_only_in_second_sit_by_radio_wi_fi_0_ble_1_rand_ble_2)
        "In both by radio: Wi-Fi {0}  BLE {1}  RAND BLE {2}" -> UiText.text(R.string.report_in_both_by_radio_wi_fi_0_ble_1_rand_ble_2)
        "Cap note: last 15 minutes is Live RAM (about 400). A named sit keeps up to {0}. Counts are not the same net." -> UiText.text(R.string.report_cap_note_last_15_minutes_is_live_ram_about_400_a_named_sit_keeps_)
        "Exclusive Extra attention:" -> UiText.text(R.string.report_exclusive_extra_attention)
        "Exclusive Named radios:" -> UiText.text(R.string.report_exclusive_named_radios)
        "In both" -> UiText.text(R.string.report_in_both)
        "Write the addendum now, following **Your output** at the top. Do not rewrite the onboard Compare." -> UiText.text(R.string.report_write_the_addendum_now_following_your_output_at_the_top_do_not_re_338)
        "Privacy mode: MAC tails are **:**:**. GPS coordinates are masked. Logs on the phone are unchanged.\n\n{0}" -> UiText.text(R.string.report_privacy_mode_mac_tails_are_gps_coordinates_are_masked_logs_on_the)
        "  Last {0}" -> UiText.text(R.string.report_last_0)
        "course {0}°" -> UiText.text(R.string.report_course_0)
        "1 advertised fix" -> UiText.text(R.string.report_1_advertised_fix)
        "{0} advertised fixes, {1}" -> UiText.text(R.string.report_0_advertised_fixes_1)
        "  Pilot {0}" -> UiText.text(R.string.report_pilot_0)
        "{0} more aircraft tracks are listed here and left off the map." -> UiText.text(R.string.report_0_more_aircraft_tracks_are_listed_here_and_left_off_the_map)
        "These positions were broadcast by the radio. They are not this phone's GPS." -> UiText.text(R.string.report_these_positions_were_broadcast_by_the_radio_they_are_not_this_pho)
        "  Status changed: {0} → {1}" -> UiText.text(R.string.report_status_changed_0_1)
        "{0}, no UAS id: {1} ({2})" -> UiText.text(R.string.report_0_no_uas_id_1_2)
        "Pilot" -> UiText.text(R.string.report_pilot)
        "second sit’s advertised track" -> UiText.text(R.string.report_second_sit_s_advertised_track)
        " A blue dotted line is the second sit’s advertised track within 2 km of this path." -> UiText.text(R.string.report_a_blue_dotted_line_is_the_second_sit_s_advertised_track_within_2_)
        "black dotted line is an advertised track" -> UiText.text(R.string.report_black_dotted_line_is_an_advertised_track)
        " A black dotted line is an advertised track within 2 km of this path." -> UiText.text(R.string.report_a_black_dotted_line_is_an_advertised_track_within_2_km_of_this_pa)
        "North-up. Black dots are this sit. Blue dots are the second sit. The marker is the last advertised position." -> UiText.text(R.string.report_north_up_black_dots_are_this_sit_blue_dots_are_the_second_sit_the)
        "North-up. The blue dotted line is the advertised track for {0}. The marker is the last advertised position." -> UiText.text(R.string.report_north_up_the_blue_dotted_line_is_the_advertised_track_for_0_the_m)
        "Last advertised position for {0}. The marker is that position." -> UiText.text(R.string.report_last_advertised_position_for_0_the_marker_is_that_position)
        "North-up. The black dotted line is the advertised track for {0}. The marker is the last advertised position." -> UiText.text(R.string.report_north_up_the_black_dotted_line_is_the_advertised_track_for_0_the_)
        "UAS {0}" -> UiText.text(R.string.report_uas_0)
        "last {0}" -> UiText.text(R.string.report_last_0_359)
        "pilot {0}" -> UiText.text(R.string.report_pilot_0_360)
        "Advertised position" -> UiText.text(R.string.report_advertised_position)
        " last {0}" -> UiText.text(R.string.report_last_0_362)
        "1 fix" -> UiText.text(R.string.report_1_fix)
        "{0} fixes" -> UiText.text(R.string.report_0_fixes)
        "named sit “{0}” (radios heard in that window; Live list cap still applied while watching). " -> UiText.text(R.string.report_named_sit_0_radios_heard_in_that_window_live_list_cap_still_appli)
        "the in-memory live set (last 15 minutes, cap about 400). " -> UiText.text(R.string.report_the_in_memory_live_set_last_15_minutes_cap_about_400)
        "This sit report is from {0}" -> UiText.text(R.string.report_this_sit_report_is_from_0)
        "Do not use it in any situation where safety is in question." -> UiText.text(R.string.report_do_not_use_it_in_any_situation_where_safety_is_in_question)
        "This compare is two windows of radios this phone heard (kind + MAC). " -> UiText.text(R.string.report_this_compare_is_two_windows_of_radios_this_phone_heard_kind_mac)
        "BLE rotation is a new row. Do not use it in any situation where safety is in question." -> UiText.text(R.string.report_ble_rotation_is_a_new_row_do_not_use_it_in_any_situation_where_sa)
        "## Disclaimer (repeat this in your answer)" -> UiText.text(R.string.report_disclaimer_repeat_this_in_your_answer)
        "Do not use Fieldwatch, this paste, or your analysis in any situation where safety is in question." -> UiText.text(R.string.report_do_not_use_fieldwatch_this_paste_or_your_analysis_in_any_situatio)
        "Begin your reply with this disclaimer. Do not give safety advice." -> UiText.text(R.string.report_begin_your_reply_with_this_disclaimer_do_not_give_safety_advice)
        "Online lookup failed silently. Coordinates only." -> UiText.text(R.string.report_online_lookup_failed_silently_coordinates_only)
        "Online lookup skipped: no working internet. Coordinates only." -> UiText.text(R.string.report_online_lookup_skipped_no_working_internet_coordinates_only)
        "Online lookup skipped: this phone has no system geocoder (needs Google Play / network location). Coordinates only." -> UiText.text(R.string.report_online_lookup_skipped_this_phone_has_no_system_geocoder_needs_goo)
        "Online lookup on, but this sit had no GPS stamps to name." -> UiText.text(R.string.report_online_lookup_on_but_this_sit_had_no_gps_stamps_to_name)
        "Looking up place names (%1\$s of %2\$s)…" -> UiText.text(R.string.report_looking_up_place_names_1_s_of_2_s)
        "  · {0}  {1}  (no name returned)" -> UiText.text(R.string.report_0_1_no_name_returned)
        "Online lookup: system geocoder named {0} distinct GPS cell(s). Street names are from the phone’s network geocoder, not a Fieldwatch cloud. Approximate." -> UiText.text(R.string.report_online_lookup_system_geocoder_named_0_distinct_gps_cell_s_street_)
        "Online lookup ran, but the system geocoder returned no street names. Coordinates only." -> UiText.text(R.string.report_online_lookup_ran_but_the_system_geocoder_returned_no_street_name)
        "Stay {0}" -> UiText.text(R.string.report_stay_0)
        "Transit from" -> UiText.text(R.string.report_transit_from)
        "Transit to" -> UiText.text(R.string.report_transit_to)
        "Path start" -> UiText.text(R.string.report_path_start)
        "Path end" -> UiText.text(R.string.report_path_end)
        "Disclaimer" -> UiText.text(R.string.report_disclaimer_387)
        "Start" -> UiText.text(R.string.report_start)
        "End" -> UiText.text(R.string.report_end)
        "Stay" -> UiText.text(R.string.report_stay)
        "Phone GPS" -> UiText.text(R.string.report_phone_gps)
        "Transit" -> UiText.text(R.string.report_transit)
        "Advertised" -> UiText.text(R.string.report_advertised)
        "Second advertised" -> UiText.text(R.string.report_second_advertised)
        "MAC alert" -> UiText.text(R.string.report_mac_alert)
        "Signature alert" -> UiText.text(R.string.report_signature_alert)
        "Path key" -> UiText.text(R.string.report_path_key)
        "Observer: %1\$s" -> UiText.text(R.string.report_observer_1_s)
        "%1\$s radios at this stop — %2\$s" -> UiText.text(R.string.report_1_s_radios_at_this_stop_2_s)
        "Pattern match, not identity. Not a safety finding." -> UiText.text(R.string.report_pattern_match_not_identity_not_a_safety_finding)
        "EXTRA ATTENTION  ·  %1\$s" -> UiText.text(R.string.report_extra_attention_1_s)
        "TAKEAWAY" -> UiText.text(R.string.report_takeaway)
        "Off Grid Pete LLC  ·  operationally sensitive" -> UiText.text(R.string.report_off_grid_pete_llc_operationally_sensitive)
        "AIRCRAFT" -> UiText.text(R.string.report_aircraft_404)
        "%1\$s km span" -> UiText.text(R.string.report_1_s_km_span)
        "%1\$s m span" -> UiText.text(R.string.report_1_s_m_span)
        "%1\$s km path" -> UiText.text(R.string.report_1_s_km_path)
        "%1\$s m path" -> UiText.text(R.string.report_1_s_m_path)
        "balanced" -> UiText.text(R.string.report_balanced)
        "saver" -> UiText.text(R.string.report_saver)
        "performance" -> UiText.text(R.string.report_performance)
        "yes" -> UiText.text(R.string.report_yes)
        "no" -> UiText.text(R.string.report_no)
        "true" -> UiText.text(R.string.report_true)
        "false" -> UiText.text(R.string.report_false)
        ", RAM ~400" -> UiText.text(R.string.report_ram_400)
        ", named sit up to {0}" -> UiText.text(R.string.report_named_sit_up_to_0)
        "This is a hobby project, provided as-is under the MIT License. Use at your own risk." -> UiText.text(R.string.report_this_is_a_hobby_project_provided_as_is_under_the_mit_license_use_)
        "Detections, pattern matches, “Moving with you” / “possible tail,” Debrief text, and AI Export are hypotheses — not identity, not a legal finding, and not a complete RF capture. Radios that are off, asleep, randomized, cellular-only, or hidden by the OS will not appear." -> UiText.text(R.string.report_detections_pattern_matches_moving_with_you_possible_tail_debrief_)
        "You are solely responsible for how you use this app and for following local law. To the maximum extent permitted by law, Off Grid Pete LLC is not liable for indirect, incidental, special, consequential, or punitive damages arising from its use." -> UiText.text(R.string.report_you_are_solely_responsible_for_how_you_use_this_app_and_for_follo)
        "GPS stamps are this phone at hear-time, not the other radio, unless a decode map advertises its own latitude/longitude (Remote ID Location). Sharing a Debrief, sit compare, AI Export (sit or one radio), radio-detail Share as text, or log can take that path off the device. A TAK/CoT feed, when you turn it on, sends markers onto the LAN; that is on the operator." -> UiText.text(R.string.report_gps_stamps_are_this_phone_at_hear_time_not_the_other_radio_unless)
        "{0} km" -> UiText.text(R.string.report_distance_km)
        "{0} m" -> UiText.text(R.string.report_distance_m)
        "{0}s" -> UiText.text(R.string.report_duration_seconds)
        "{0}  ({1}, operator phone)" -> UiText.text(R.string.report_named_operator_phone)
        "{0}  (operator phone; no street name this export)" -> UiText.text(R.string.report_operator_phone_no_street)
        "{0}  (operator phone)" -> UiText.text(R.string.report_operator_phone)
        else -> source
    }
}
