package app.fieldwatch

internal object UiV99Text {
    fun text(source: String): String = when (source) {
        "NIO vehicle" -> UiText.text(R.string.catalog_v99_0)
        "NIO / ONVO phone-as-key digital key: company identifiers 432E / 4663 / 0B48 or the fixed Apple iBeacon UUID 9F0891D0-… observed on NIO keys. Pattern match, not a model, owner or key state." -> UiText.text(R.string.catalog_v99_1)
        "D-platform digital key (Neta / multi-OEM)" -> UiText.text(R.string.catalog_v99_2)
        "N9D* / OEM-code (06D / 0PD / 1RD / 2HD / 2PD / 36DB / 3QDB / 0KD / N4D / N7D / N8D prefixes; 3rd char always D, J + 4 digits at the end) BLE names identify shared digital-key platform keys (Neta N9D observed). The platform's 128-bit UUID is the standard Nordic UART service that plain nRF dev boards also advertise, so the UUID is not used as a standalone condition; its E0A9-E50E24DCCA9E suffix is shared with the BYD AUTO (42594420-…) and smart_ebike (86912001-…) platform UUIDs — one key vendor serves many brands." -> UiText.text(R.string.catalog_v99_3)
        "XPeng vehicle" -> UiText.text(R.string.catalog_v99_4)
        "XPED-* BLE name is an XPeng digital-key code; the advertised service UUID embeds the same code. Key hardware OUI 00:60:37 is shared with BYD / GAC keys." -> UiText.text(R.string.catalog_v99_5)
        "Xiaomi EV" -> UiText.text(R.string.catalog_v99_6)
        "MiCar* BLE name or the E4:01 locally-administered address prefix observed on every sampled Xiaomi EV key." -> UiText.text(R.string.catalog_v99_7)
        "GAC vehicle" -> UiText.text(R.string.catalog_v99_8)
        "GAC-prefixed BLE names are GAC / Yingjie (InGeek) digital-key vehicle codes (GACAB34N5…, GAC1S59T1…, GACA020LG…). Key hardware OUI 00:60:37 is shared with BYD / XPeng keys. Pattern match, not a model or owner." -> UiText.text(R.string.catalog_v99_9)
        "GWM vehicle" -> UiText.text(R.string.catalog_v99_10)
        "GWM-prefixed BLE names are Great Wall Motor digital-key vehicle codes (GWMVA73TH514551 observed). Pattern match, not a model or owner." -> UiText.text(R.string.catalog_v99_11)
        "Geely vehicle" -> UiText.text(R.string.catalog_v99_12)
        "GeelyVehicle* / GEL_Car BLE names identify Geely-group digital-key radios. Company identifier 01FE (Radio Systems Corporation, SIG-registered) is a group-platform marker also seen on ZEEKR keys and plain Radio Systems modules, so the company id alone is not assigned; the ZEEKR row labels those keys by name." -> UiText.text(R.string.catalog_v99_13)
        "Lynk & Co vehicle" -> UiText.text(R.string.catalog_v99_14)
        "Lynk&CoVehicle* BLE name; its Apple iBeacon UUID carries the ASCII vehicle code (6T79XEZ4RE008849 observed). Pattern match, not an owner." -> UiText.text(R.string.catalog_v99_15)
        "SAIC vehicle" -> UiText.text(R.string.catalog_v99_16)
        "SGM-prefixed BLE name observed once (SGMd9eb6f); the SAIC (Shanghai Automobile) association is unconfirmed." -> UiText.text(R.string.catalog_v99_17)
        "FPH vehicle code (brand unconfirmed)" -> UiText.text(R.string.catalog_v99_18)
        "FPH4-prefixed vehicle code (FPH4APP1T1A12837 observed) with company identifier 6748; brand association (Foton) unconfirmed." -> UiText.text(R.string.catalog_v99_19)
        "CZCC vehicle (brand unconfirmed)" -> UiText.text(R.string.catalog_v99_20)
        "CZCC-?????? BLE code observed once (CZCC-CC4806); brand association unconfirmed." -> UiText.text(R.string.catalog_v99_21)
        "CARKEY digital key (brand unconfirmed)" -> UiText.text(R.string.catalog_v99_22)
        "CARKEY + 3-digit BLE name observed on generic digital keys; brand unconfirmed." -> UiText.text(R.string.catalog_v99_23)
        "MTC vehicle device (purpose unconfirmed)" -> UiText.text(R.string.catalog_v99_24)
        "MTC + 12-hex BLE code (MTC71EFA72D8B1A observed) on address prefix 40:99:F6, also seen on GAC keys; purpose unconfirmed." -> UiText.text(R.string.catalog_v99_25)
        "03HPB vehicle code (brand unconfirmed)" -> UiText.text(R.string.catalog_v99_26)
        "03HPB0LE0000ZTG… style factory code (03HPB0LE0000ZTG250000314 observed) with company identifier A279; brand unconfirmed." -> UiText.text(R.string.catalog_v99_27)
        "F301 factory code (brand unconfirmed)" -> UiText.text(R.string.catalog_v99_28)
        "F301… BLE name embeds a plaintext production date (F30141501001202509240031 = made 2025-09-24). Device family unconfirmed." -> UiText.text(R.string.catalog_v99_29)
        "Yadea vehicle" -> UiText.text(R.string.catalog_v99_30)
        "Yadea e-bike / e-scooter radio: company identifier 5944 (ASCII 'YD'), YD+8-hex and YD_+4-hex (Alipay fleet) names, or the E7810BD2 / D20B81E7 / E7810B92 Apple iBeacon UUID firmware generations carried in company 004C manufacturer data (an iBeacon UUID is not a service UUID). Raw manufacturer data carries lock state and battery level. Pattern match, not a rider or a lock state." -> UiText.text(R.string.catalog_v99_31)
        "XiaoDao vehicle" -> UiText.text(R.string.catalog_v99_32)
        "XiaoDao_* BLE name points to a Xiaodao e-bike radio. The suffix does not identify a rider or a lock state." -> UiText.text(R.string.catalog_v99_33)
        "smart_ebike (shared key platform)" -> UiText.text(R.string.catalog_v99_34)
        "smart_ebike BLE name or platform UUID 86912001-B5A3-F393-E0A9-E50E24DCCA9E. The E0A9-E50E24DCCA9E suffix is the same key-vendor platform used by the D-platform vehicle keys and BYD AUTO." -> UiText.text(R.string.catalog_v99_35)
        "ZEEHO motorcycle" -> UiText.text(R.string.catalog_v99_36)
        "ZEEHO-* BLE name points to a ZEEHO electric motorcycle radio. The suffix is not a verified model or vehicle identity." -> UiText.text(R.string.catalog_v99_37)
        "XSUN motorcycle" -> UiText.text(R.string.catalog_v99_38)
        "XSUN + 4-hex BLE name (XSUN285B observed) points to an XSUN electric motorcycle radio." -> UiText.text(R.string.catalog_v99_39)
        "QBIKE vehicle" -> UiText.text(R.string.catalog_v99_40)
        "QBIKE_ + 16-hex BLE name observed on a shared e-bike radio; operator unconfirmed." -> UiText.text(R.string.catalog_v99_41)
        "TL_GPSJLXW fleet GPS" -> UiText.text(R.string.catalog_v99_42)
        "TL_GPSJLXW_ + 6-digit fleet GPS tracker name. Raw manufacturer data embeds a BCD real-time-clock date (20 26 04 28 = 2026-04-28 observed). Pattern match, not a vehicle or a driver." -> UiText.text(R.string.catalog_v99_43)
        "WTTB logistics tag (purpose unconfirmed)" -> UiText.text(R.string.catalog_v99_44)
        "WTTB + digits BLE name observed once (WTTB02230407379); logistics / asset-tag association unconfirmed." -> UiText.text(R.string.catalog_v99_45)
        "PKE keyless entry" -> UiText.text(R.string.catalog_v99_46)
        "PKE-???? BLE name observed once (PKE-2580) on a passive keyless-entry module; vehicle brand unconfirmed." -> UiText.text(R.string.catalog_v99_47)
        "ETC-JL unit" -> UiText.text(R.string.catalog_v99_48)
        "ETC-JL-???? BLE name observed once (ETC-JL-6981) on an in-vehicle ETC unit; operator unconfirmed." -> UiText.text(R.string.catalog_v99_49)
        "MIFOB key fob (purpose unconfirmed)" -> UiText.text(R.string.catalog_v99_50)
        "MIFOB_PE BLE name observed once; a Xiaomi-ecosystem key fob is suspected but unconfirmed." -> UiText.text(R.string.catalog_v99_51)
        "CM device (NetEase?)" -> UiText.text(R.string.catalog_v99_52)
        "CM-???? BLE name (CM-8E09 observed) whose Apple iBeacon UUID is the ASCII NETEASE…easefm string (NetEase Cloud Music). Device type unconfirmed; not a vehicle." -> UiText.text(R.string.catalog_v99_53)
        "ChinaNet (ChinaNetcom ONT)" -> UiText.text(R.string.catalog_v99_54)
        "ChinaNet-* default SSID of a ChinaNetcom (Unicom) optical modem / ONT. The SSID is operator-set and can be renamed; no router model is established." -> UiText.text(R.string.catalog_v99_55)
        "NuoXc Wi-Fi" -> UiText.text(R.string.catalog_v99_56)
        "IEEE prefix 68:89:75 is registered to NuoXc (Shenzhen, Longgang); 6A:89:75 carried the same registration in the 2026-08 IEEE feed and was dropped from the current one. The two prefixes form one sequential dual-radio home AP (observed hidden-SSID). Older OUI feeds registered this pair to MERCURY, so legacy logs label it that way; no exact model is established." -> UiText.text(R.string.catalog_v99_57)
        "eg AC (hanging) radio" -> UiText.text(R.string.catalog_v99_58)
        "eg_ac_* BLE names advertise a wall-hung (hanging) air-conditioner unit; the 'eg' brand prefix is unverified. Company 3838 with a 2D-11… unit code; the radio is a Huizhou Gaoshengda module. No temperature or operating state is revealed." -> UiText.text(R.string.catalog_v99_59)
        "Ziroom smart-home AP" -> UiText.text(R.string.catalog_v99_60)
        "ziroom* / ZR_* SSIDs and the Deqing Dusun IEEE prefix (public 30:AE:7B and locally-administered 32:AE:7B) identify Ziroom (自如) furnished-apartment in-unit radios. The SSID suffix is a room / unit code, not a person." -> UiText.text(R.string.catalog_v99_61)
        "Huawei Super Device beacon" -> UiText.text(R.string.catalog_v99_62)
        "FDEE is the SIG-assigned Huawei 16-bit service. Huawei phones and wearables advertise it with an empty name, randomized MAC and company 027D; the payload is a Super Device / Huawei Share discovery beacon, not a product or a person." -> UiText.text(R.string.catalog_v99_63)
        "Xiaomi / Redmi phone beacon" -> UiText.text(R.string.catalog_v99_64)
        "FCC0 is the SIG-assigned Xiaomi 16-bit service. Observed on Xiaomi 17 / REDMI K80 / Redmi Note 13 Pro phones: randomized MAC, no local name, and a device code plus the plaintext model name in the service data (Find-Device style broadcast). No user or location is revealed." -> UiText.text(R.string.catalog_v99_65)
        "China Mobile CPE (CMCC)" -> UiText.text(R.string.catalog_v99_66)
        "CMCC* SSID is the operator-default name of a China Mobile broadband CPE / 5G CPE; the suffix (e.g. CMCC-Xiao-Apple) is user-chosen. Some CPEs carry an Espressif 2.4 GHz radio. No exact model is established." -> UiText.text(R.string.catalog_v99_67)
        "Smart TV built-in AP" -> UiText.text(R.string.catalog_v99_68)
        "SmartTVAP SSID is the built-in access point a smart TV opens for casting / companion-phone pairing (Chongqing QingJia ODM prefix observed). Not a router; no viewing state is revealed." -> UiText.text(R.string.catalog_v99_69)
        "Cellular IoT radio (ICCID name)" -> UiText.text(R.string.catalog_v99_70)
        "BT_ + 15-digit name is the SIM ICCID: a cellular (4G) IoT device such as a tracker / DTU named after its SIM. The 8663 prefix suggests a China Unicom IoT card (unverified). No location, operator account or vehicle is inferred." -> UiText.text(R.string.catalog_v99_71)
        "jida_bike bike radio" -> UiText.text(R.string.catalog_v99_72)
        "jida_bike BLE name on company 1010 with sync-byte framed frames (lock / controller style). Shared-operator association is unverified; no rider or lock state is inferred." -> UiText.text(R.string.catalog_v99_73)
        "XD e-bike radio" -> UiText.text(R.string.catalog_v99_74)
        "Company 4458 is ASCII 'XD' (the Yadea 'YD' 5944 pattern) and xcdc* names carry a J28… serial (xcdcJ28000032190 observed). Shared e-bike / scooter association is likely but unverified; no rider or lock state is inferred." -> UiText.text(R.string.catalog_v99_75)
        "OPPO device beacon" -> UiText.text(R.string.catalog_v99_76)
        "Company 079A is SIG-assigned to OPPO. OPPO phones and wearables advertise it (two units with an identical ten-byte payload observed) together with service 686B, which is not locally vendor-registered. The payload is a discovery beacon, not a product or a person." -> UiText.text(R.string.catalog_v99_77)
        "Alipay BLE radio (BLE_DK)" -> UiText.text(R.string.catalog_v99_78)
        "BLE_DK_<serial> advertised names plus a 128-bit service UUID carrying ASCII 'alipay' identify Alipay-ecosystem radios (tap / digital-key style). The product line is not confirmed; no account or payment state is revealed." -> UiText.text(R.string.catalog_v99_79)
        "MERCURY Wi-Fi" -> UiText.text(R.string.catalog_v99_80)
        "MERCURY* Wi-Fi name identifies a Mercury network family. IEEE prefixes 4C:77:66 / BC:54:FC are both registered to Shenzhen Mercury Communications; the SSID is user-set (a phone number observed). The former 68:89:75 / 6A:89:75 pair is now IEEE-registered to NuoXc and lives on the NuoXc row, not here." -> UiText.text(R.string.catalog_v99_81)
        "EZVIZ device" -> UiText.text(R.string.catalog_v99_82)
        "IEEE 94:EC:13 identifies an EZVIZ device family on Wi-Fi or a public stable BLE address. EZVIZ BLE radios also carry company 2B19 (primary) plus a 2B18 block with an ASCII EZVIZ marker (BD2260002 'bl702l' build observed); neither company id is SIG-registered, so the marker confirms the vendor. It does not prove the device is a camera." -> UiText.text(R.string.catalog_v99_83)
        "Haier appliance radio" -> UiText.text(R.string.catalog_v99_84)
        "IEEE prefixes registered to Qingdao Haier Technology identify a Haier radio family on Wi-Fi or a stable public BLE address. U-AC / U-GW style BLE names observed on these prefixes are Haier appliance units (air conditioners and gateways); the name alone on an unregistered address is not assigned. Appliance type and exact model are not established." -> UiText.text(R.string.catalog_v99_85)
        "Mi ecosystem door lock" -> UiText.text(R.string.catalog_v99_86)
        "Xiaomi ecosystem door-lock family. MiBeacon product headers distinguish known partner models (1B01 = 'Mi Automatic Smart Door Lock', classic company 004C v3 header); the advertised model name also identifies the lock. They do not identify an owner or prove a locked or unlocked state." -> UiText.text(R.string.catalog_v99_87)
        else -> UiV100Text.text(source)
    }
}
