package app.fieldwatch

internal object UiV95Text {
    fun text(source: String): String = when (source) {
        "Mesh key refresh (advertised, unverified)" -> UiText.text(R.string.information_v95_0)
        "Key refresh phase 2" -> UiText.text(R.string.information_v95_1)
        "Not in key refresh phase 2" -> UiText.text(R.string.information_v95_2)
        "Mesh IV update (advertised, unverified)" -> UiText.text(R.string.information_v95_3)
        "IV update in progress" -> UiText.text(R.string.information_v95_4)
        "Normal IV operation" -> UiText.text(R.string.information_v95_5)
        "Encrypted or unsupported telemetry version; readings unavailable" -> UiText.text(R.string.information_v95_6)
        "Malformed telemetry length; readings unavailable" -> UiText.text(R.string.information_v95_7)
        "Beacon battery voltage" -> UiText.text(R.string.information_v95_8)
        "Not supported" -> UiText.text(R.string.information_v95_9)
        "Beacon temperature" -> UiText.text(R.string.information_v95_10)
        "Beacon transmitted advertisement count" -> UiText.text(R.string.information_v95_11)
        "Beacon time since power-on or reboot" -> UiText.text(R.string.information_v95_12)
        "WMM parse status" -> UiText.text(R.string.information_v95_13)
        "Unsupported WMM subtype" -> UiText.text(R.string.information_v95_14)
        "Malformed or unsupported WMM element" -> UiText.text(R.string.information_v95_15)
        "WMM traffic prioritization (advertised)" -> UiText.text(R.string.information_v95_16)
        "Access point advertises WMM; this does not measure throughput or latency." -> UiText.text(R.string.information_v95_17)
        "WMM client power saving (U-APSD, advertised)" -> UiText.text(R.string.information_v95_18)
        "Supported; client support and negotiation are required" -> UiText.text(R.string.information_v95_19)
        "Not advertised in this element" -> UiText.text(R.string.information_v95_20)
        "WPS setup methods (advertised)" -> UiText.text(R.string.information_v95_21)
        "USB" -> UiText.text(R.string.information_v95_22)
        "Ethernet" -> UiText.text(R.string.information_v95_23)
        "Printed PIN label" -> UiText.text(R.string.information_v95_24)
        "Displayed PIN" -> UiText.text(R.string.information_v95_25)
        "External NFC token" -> UiText.text(R.string.information_v95_26)
        "Integrated NFC token" -> UiText.text(R.string.information_v95_27)
        "NFC interface" -> UiText.text(R.string.information_v95_28)
        "Push button" -> UiText.text(R.string.information_v95_29)
        "PIN keypad" -> UiText.text(R.string.information_v95_30)
        "Wi-Fi Direct services" -> UiText.text(R.string.information_v95_31)
        "Virtual push button" -> UiText.text(R.string.information_v95_32)
        "Physical push button" -> UiText.text(R.string.information_v95_33)
        "Virtual PIN display" -> UiText.text(R.string.information_v95_34)
        "Physical PIN display" -> UiText.text(R.string.information_v95_35)
        "No known setup method" -> UiText.text(R.string.information_v95_36)
        "Advertised capability only; not proof that setup is currently allowed." -> UiText.text(R.string.information_v95_37)
        "Computer" -> UiText.text(R.string.information_v95_38)
        "Input device" -> UiText.text(R.string.information_v95_39)
        "Printer / scanner" -> UiText.text(R.string.information_v95_40)
        "Camera" -> UiText.text(R.string.information_v95_41)
        "Storage device" -> UiText.text(R.string.information_v95_42)
        "Network infrastructure" -> UiText.text(R.string.information_v95_43)
        "Display" -> UiText.text(R.string.information_v95_44)
        "Multimedia device" -> UiText.text(R.string.information_v95_45)
        "Gaming device" -> UiText.text(R.string.information_v95_46)
        "Telephone" -> UiText.text(R.string.information_v95_47)
        "Audio device" -> UiText.text(R.string.information_v95_48)
        else -> UiV96Text.text(source)
    }
}
