package app.fieldwatch

/** Authored v93 labels only; observed values remain unchanged. */
internal object UiV93Text {
    fun text(source: String): String = when (source) {
        "HID input service (brand unconfirmed)" -> UiText.text(R.string.discovery_v93_0)
        "Possible remote control (Mixin name)" -> UiText.text(R.string.discovery_v93_1)
        "Possible iKF-King Pro headphones" -> UiText.text(R.string.discovery_v93_2)
        "Possible Leapmotor digital key (advertised name)" -> UiText.text(R.string.discovery_v93_3)
        "InGeek LEX ecosystem (purpose unconfirmed)" -> UiText.text(R.string.discovery_v93_4)
        "Apple AWDL connection protocol" -> UiText.text(R.string.discovery_v93_5)
        "Skyworth registered Wi-Fi interface (type unknown)" -> UiText.text(R.string.discovery_v93_6)
        "YOUHUA registered Wi-Fi interface (type unknown)" -> UiText.text(R.string.discovery_v93_7)
        "Tianyi Comheart registered Wi-Fi interface (type unknown)" -> UiText.text(R.string.discovery_v93_8)
        "Tianyi Terminals registered Wi-Fi interface (type unknown)" -> UiText.text(R.string.discovery_v93_9)
        "China Mobile registered Wi-Fi interface (type unknown)" -> UiText.text(R.string.discovery_v93_10)
        "Gubei / BroadLink registered Wi-Fi interface (type unknown)" -> UiText.text(R.string.discovery_v93_11)
        "BLE service 1812 is the standard human-interface service for keyboards, mice, remotes and similar inputs. It does not identify a brand; Generic Keyring appearance alone is not HID evidence." -> UiText.text(R.string.discovery_v93_12)
        "The exact BLE name Mixin Remote Control suggests a remote control. The name is a broadcast claim; brand and exact product are unconfirmed." -> UiText.text(R.string.discovery_v93_13)
        "The iKF-King Pro BLE pairing-name family matches the manufacturer's headphone documentation. A suffix does not establish a product generation or operating state." -> UiText.text(R.string.discovery_v93_14)
        "The exact BLE name Leapmotor_DigitalKey claims a Leapmotor digital key. The name does not establish a vehicle model, owner or unlock state." -> UiText.text(R.string.discovery_v93_15)
        "LEX name plus InGeek company identifier 0759 and service 5810BBC0 identifies an InGeek ecosystem radio. InGeek supplies digital-key platforms; this record does not establish the product purpose, car brand or model." -> UiText.text(R.string.discovery_v93_16)
        "A complete Apple Continuity type 16 message with eight payload bytes advertises AWDL connection data. Its format is undocumented; it does not identify an exact product or expose battery or activity." -> UiText.text(R.string.discovery_v93_17)
        "IEEE address prefixes are registered to Shenzhen Skyworth Digital. They identify a Wi-Fi interface registration; finished-product brand, model and purpose are unconfirmed." -> UiText.text(R.string.discovery_v93_18)
        "IEEE address prefixes are registered to Shenzhen YOUHUA Technology. They identify a Wi-Fi interface registration; finished-product brand, model and purpose are unconfirmed." -> UiText.text(R.string.discovery_v93_19)
        "IEEE address prefixes are registered to Sichuan Tianyi Comheart Telecom. They identify a Wi-Fi interface registration; finished-product brand, model and purpose are unconfirmed." -> UiText.text(R.string.discovery_v93_20)
        "IEEE address prefixes are registered to Tianyi Telecom Terminals. They identify a Wi-Fi interface registration; finished-product brand, model and purpose are unconfirmed." -> UiText.text(R.string.discovery_v93_21)
        "IEEE address prefixes are registered to China Mobile Group Device or China Mobile IOT. They identify a Wi-Fi interface registration; finished-product brand, model and purpose are unconfirmed." -> UiText.text(R.string.discovery_v93_22)
        "IEEE address prefixes are registered to HangZhou Gubei Electronics Technology (BroadLink). They identify a Wi-Fi interface registration; finished-product brand, model and purpose are unconfirmed." -> UiText.text(R.string.discovery_v93_23)
        "AirPlay target" -> UiText.text(R.string.discovery_v93_24)
        "an AirPlay target" -> UiText.text(R.string.discovery_v93_25)
        "AirPlay target advertisement; product model is unconfirmed." -> UiText.text(R.string.discovery_v93_26)
        "Unsupported or malformed AirPlay target length" -> UiText.text(R.string.discovery_v93_27)
        "Advertised network endpoint; not location information." -> UiText.text(R.string.discovery_v93_28)
        "AirPlay flags (raw)" -> UiText.text(R.string.discovery_v93_29)
        "AirPlay seed (raw)" -> UiText.text(R.string.discovery_v93_30)
        "AirPlay advertised IPv4" -> UiText.text(R.string.discovery_v93_31)
        "AirPlay advertised port" -> UiText.text(R.string.discovery_v93_32)
        "AirPlay default port (not advertised)" -> UiText.text(R.string.discovery_v93_33)
        "AWDL connection message" -> UiText.text(R.string.discovery_v93_34)
        "Unsupported or malformed AWDL message length" -> UiText.text(R.string.discovery_v93_35)
        "Undocumented connection data; battery and activity are not decoded." -> UiText.text(R.string.discovery_v93_36)
        "AWDL flags (raw)" -> UiText.text(R.string.discovery_v93_37)
        "AWDL message (raw)" -> UiText.text(R.string.discovery_v93_38)
        "WPS attribute version (not firmware)" -> UiText.text(R.string.discovery_v93_39)
        "WPS AP setup locked" -> UiText.text(R.string.discovery_v93_40)
        "WPS selected registrar" -> UiText.text(R.string.discovery_v93_41)
        "WPS RF bands" -> UiText.text(R.string.discovery_v93_42)
        "WPS configuration methods (advertised mask)" -> UiText.text(R.string.discovery_v93_43)
        "a HID input device (brand unconfirmed)" -> UiText.text(R.string.discovery_v93_44)
        "a possible remote control (brand unconfirmed)" -> UiText.text(R.string.discovery_v93_45)
        "possible iKF-King Pro headphones" -> UiText.text(R.string.discovery_v93_46)
        "a possible Leapmotor digital-key radio" -> UiText.text(R.string.discovery_v93_47)
        "an InGeek ecosystem radio (purpose unconfirmed)" -> UiText.text(R.string.discovery_v93_48)
        "an AWDL protocol advertiser (product unconfirmed)" -> UiText.text(R.string.discovery_v93_49)
        "Apple Continuity type %1\$s" -> UiText.text(R.string.discovery_v93_50)
        else -> source
    }
}
